// Code generated by ent, DO NOT EDIT.

package adminnotificationread

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the adminnotificationread type in the database.
	Label = "admin_notification_read"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNotificationID holds the string denoting the notification_id field in the database.
	FieldNotificationID = "notification_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldReadAt holds the string denoting the read_at field in the database.
	FieldReadAt = "read_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeNotification holds the string denoting the notification edge name in mutations.
	EdgeNotification = "notification"
	// Table holds the table name of the adminnotificationread in the database.
	Table = "admin_notification_reads"
	// NotificationTable is the table that holds the notification relation/edge.
	NotificationTable = "admin_notification_reads"
	// NotificationInverseTable is the table name for the AdminNotification entity.
	// It exists in this package in order to avoid circular dependency with the "adminnotification" package.
	NotificationInverseTable = "admin_notifications"
	// NotificationColumn is the table column denoting the notification relation/edge.
	NotificationColumn = "notification_id"
)

// Columns holds all SQL columns for adminnotificationread fields.
var Columns = []string{
	FieldID,
	FieldNotificationID,
	FieldUserID,
	FieldReadAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultReadAt holds the default value on creation for the "read_at" field.
	DefaultReadAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the AdminNotificationRead queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNotificationID orders the results by the notification_id field.
func ByNotificationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotificationID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByReadAt orders the results by the read_at field.
func ByReadAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReadAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByNotificationField orders the results by notification field.
func ByNotificationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNotificationStep(), sql.OrderByField(field, opts...))
	}
}
func newNotificationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NotificationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, NotificationTable, NotificationColumn),
	)
}
