// Code generated by ent, DO NOT EDIT.

package upstreampricesource

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldPlatform, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldBaseURL, v))
}

// PricingEndpoint applies equality check predicate on the "pricing_endpoint" field. It's identical to PricingEndpointEQ.
func PricingEndpoint(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldPricingEndpoint, v))
}

// APIKey applies equality check predicate on the "api_key" field. It's identical to APIKeyEQ.
func APIKey(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldAPIKey, v))
}

// ParserType applies equality check predicate on the "parser_type" field. It's identical to ParserTypeEQ.
func ParserType(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldParserType, v))
}

// SyncIntervalMinutes applies equality check predicate on the "sync_interval_minutes" field. It's identical to SyncIntervalMinutesEQ.
func SyncIntervalMinutes(v int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldSyncIntervalMinutes, v))
}

// AlertThresholdPct applies equality check predicate on the "alert_threshold_pct" field. It's identical to AlertThresholdPctEQ.
func AlertThresholdPct(v float64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldAlertThresholdPct, v))
}

// CooldownMinutes applies equality check predicate on the "cooldown_minutes" field. It's identical to CooldownMinutesEQ.
func CooldownMinutes(v int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldCooldownMinutes, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldEnabled, v))
}

// LastSyncAt applies equality check predicate on the "last_sync_at" field. It's identical to LastSyncAtEQ.
func LastSyncAt(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastSyncStatus applies equality check predicate on the "last_sync_status" field. It's identical to LastSyncStatusEQ.
func LastSyncStatus(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldLastSyncStatus, v))
}

// LastSyncError applies equality check predicate on the "last_sync_error" field. It's identical to LastSyncErrorEQ.
func LastSyncError(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldLastSyncError, v))
}

// LastHash applies equality check predicate on the "last_hash" field. It's identical to LastHashEQ.
func LastHash(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldLastHash, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContainsFold(FieldName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContainsFold(FieldPlatform, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContainsFold(FieldBaseURL, v))
}

// PricingEndpointEQ applies the EQ predicate on the "pricing_endpoint" field.
func PricingEndpointEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldPricingEndpoint, v))
}

// PricingEndpointNEQ applies the NEQ predicate on the "pricing_endpoint" field.
func PricingEndpointNEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldPricingEndpoint, v))
}

// PricingEndpointIn applies the In predicate on the "pricing_endpoint" field.
func PricingEndpointIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldPricingEndpoint, vs...))
}

// PricingEndpointNotIn applies the NotIn predicate on the "pricing_endpoint" field.
func PricingEndpointNotIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldPricingEndpoint, vs...))
}

// PricingEndpointGT applies the GT predicate on the "pricing_endpoint" field.
func PricingEndpointGT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldPricingEndpoint, v))
}

// PricingEndpointGTE applies the GTE predicate on the "pricing_endpoint" field.
func PricingEndpointGTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldPricingEndpoint, v))
}

// PricingEndpointLT applies the LT predicate on the "pricing_endpoint" field.
func PricingEndpointLT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldPricingEndpoint, v))
}

// PricingEndpointLTE applies the LTE predicate on the "pricing_endpoint" field.
func PricingEndpointLTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldPricingEndpoint, v))
}

// PricingEndpointContains applies the Contains predicate on the "pricing_endpoint" field.
func PricingEndpointContains(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContains(FieldPricingEndpoint, v))
}

// PricingEndpointHasPrefix applies the HasPrefix predicate on the "pricing_endpoint" field.
func PricingEndpointHasPrefix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasPrefix(FieldPricingEndpoint, v))
}

// PricingEndpointHasSuffix applies the HasSuffix predicate on the "pricing_endpoint" field.
func PricingEndpointHasSuffix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasSuffix(FieldPricingEndpoint, v))
}

// PricingEndpointEqualFold applies the EqualFold predicate on the "pricing_endpoint" field.
func PricingEndpointEqualFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEqualFold(FieldPricingEndpoint, v))
}

// PricingEndpointContainsFold applies the ContainsFold predicate on the "pricing_endpoint" field.
func PricingEndpointContainsFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContainsFold(FieldPricingEndpoint, v))
}

// APIKeyEQ applies the EQ predicate on the "api_key" field.
func APIKeyEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldAPIKey, v))
}

// APIKeyNEQ applies the NEQ predicate on the "api_key" field.
func APIKeyNEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldAPIKey, v))
}

// APIKeyIn applies the In predicate on the "api_key" field.
func APIKeyIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldAPIKey, vs...))
}

// APIKeyNotIn applies the NotIn predicate on the "api_key" field.
func APIKeyNotIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldAPIKey, vs...))
}

// APIKeyGT applies the GT predicate on the "api_key" field.
func APIKeyGT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldAPIKey, v))
}

// APIKeyGTE applies the GTE predicate on the "api_key" field.
func APIKeyGTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldAPIKey, v))
}

// APIKeyLT applies the LT predicate on the "api_key" field.
func APIKeyLT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldAPIKey, v))
}

// APIKeyLTE applies the LTE predicate on the "api_key" field.
func APIKeyLTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldAPIKey, v))
}

// APIKeyContains applies the Contains predicate on the "api_key" field.
func APIKeyContains(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContains(FieldAPIKey, v))
}

// APIKeyHasPrefix applies the HasPrefix predicate on the "api_key" field.
func APIKeyHasPrefix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasPrefix(FieldAPIKey, v))
}

// APIKeyHasSuffix applies the HasSuffix predicate on the "api_key" field.
func APIKeyHasSuffix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasSuffix(FieldAPIKey, v))
}

// APIKeyIsNil applies the IsNil predicate on the "api_key" field.
func APIKeyIsNil() predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIsNull(FieldAPIKey))
}

// APIKeyNotNil applies the NotNil predicate on the "api_key" field.
func APIKeyNotNil() predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotNull(FieldAPIKey))
}

// APIKeyEqualFold applies the EqualFold predicate on the "api_key" field.
func APIKeyEqualFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEqualFold(FieldAPIKey, v))
}

// APIKeyContainsFold applies the ContainsFold predicate on the "api_key" field.
func APIKeyContainsFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContainsFold(FieldAPIKey, v))
}

// ParserTypeEQ applies the EQ predicate on the "parser_type" field.
func ParserTypeEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldParserType, v))
}

// ParserTypeNEQ applies the NEQ predicate on the "parser_type" field.
func ParserTypeNEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldParserType, v))
}

// ParserTypeIn applies the In predicate on the "parser_type" field.
func ParserTypeIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldParserType, vs...))
}

// ParserTypeNotIn applies the NotIn predicate on the "parser_type" field.
func ParserTypeNotIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldParserType, vs...))
}

// ParserTypeGT applies the GT predicate on the "parser_type" field.
func ParserTypeGT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldParserType, v))
}

// ParserTypeGTE applies the GTE predicate on the "parser_type" field.
func ParserTypeGTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldParserType, v))
}

// ParserTypeLT applies the LT predicate on the "parser_type" field.
func ParserTypeLT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldParserType, v))
}

// ParserTypeLTE applies the LTE predicate on the "parser_type" field.
func ParserTypeLTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldParserType, v))
}

// ParserTypeContains applies the Contains predicate on the "parser_type" field.
func ParserTypeContains(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContains(FieldParserType, v))
}

// ParserTypeHasPrefix applies the HasPrefix predicate on the "parser_type" field.
func ParserTypeHasPrefix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasPrefix(FieldParserType, v))
}

// ParserTypeHasSuffix applies the HasSuffix predicate on the "parser_type" field.
func ParserTypeHasSuffix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasSuffix(FieldParserType, v))
}

// ParserTypeEqualFold applies the EqualFold predicate on the "parser_type" field.
func ParserTypeEqualFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEqualFold(FieldParserType, v))
}

// ParserTypeContainsFold applies the ContainsFold predicate on the "parser_type" field.
func ParserTypeContainsFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContainsFold(FieldParserType, v))
}

// ParserConfigIsNil applies the IsNil predicate on the "parser_config" field.
func ParserConfigIsNil() predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIsNull(FieldParserConfig))
}

// ParserConfigNotNil applies the NotNil predicate on the "parser_config" field.
func ParserConfigNotNil() predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotNull(FieldParserConfig))
}

// ModelAliasMapIsNil applies the IsNil predicate on the "model_alias_map" field.
func ModelAliasMapIsNil() predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIsNull(FieldModelAliasMap))
}

// ModelAliasMapNotNil applies the NotNil predicate on the "model_alias_map" field.
func ModelAliasMapNotNil() predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotNull(FieldModelAliasMap))
}

// SyncIntervalMinutesEQ applies the EQ predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesEQ(v int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldSyncIntervalMinutes, v))
}

// SyncIntervalMinutesNEQ applies the NEQ predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesNEQ(v int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldSyncIntervalMinutes, v))
}

// SyncIntervalMinutesIn applies the In predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesIn(vs ...int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldSyncIntervalMinutes, vs...))
}

// SyncIntervalMinutesNotIn applies the NotIn predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesNotIn(vs ...int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldSyncIntervalMinutes, vs...))
}

// SyncIntervalMinutesGT applies the GT predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesGT(v int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldSyncIntervalMinutes, v))
}

// SyncIntervalMinutesGTE applies the GTE predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesGTE(v int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldSyncIntervalMinutes, v))
}

// SyncIntervalMinutesLT applies the LT predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesLT(v int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldSyncIntervalMinutes, v))
}

// SyncIntervalMinutesLTE applies the LTE predicate on the "sync_interval_minutes" field.
func SyncIntervalMinutesLTE(v int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldSyncIntervalMinutes, v))
}

// AlertThresholdPctEQ applies the EQ predicate on the "alert_threshold_pct" field.
func AlertThresholdPctEQ(v float64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldAlertThresholdPct, v))
}

// AlertThresholdPctNEQ applies the NEQ predicate on the "alert_threshold_pct" field.
func AlertThresholdPctNEQ(v float64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldAlertThresholdPct, v))
}

// AlertThresholdPctIn applies the In predicate on the "alert_threshold_pct" field.
func AlertThresholdPctIn(vs ...float64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldAlertThresholdPct, vs...))
}

// AlertThresholdPctNotIn applies the NotIn predicate on the "alert_threshold_pct" field.
func AlertThresholdPctNotIn(vs ...float64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldAlertThresholdPct, vs...))
}

// AlertThresholdPctGT applies the GT predicate on the "alert_threshold_pct" field.
func AlertThresholdPctGT(v float64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldAlertThresholdPct, v))
}

// AlertThresholdPctGTE applies the GTE predicate on the "alert_threshold_pct" field.
func AlertThresholdPctGTE(v float64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldAlertThresholdPct, v))
}

// AlertThresholdPctLT applies the LT predicate on the "alert_threshold_pct" field.
func AlertThresholdPctLT(v float64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldAlertThresholdPct, v))
}

// AlertThresholdPctLTE applies the LTE predicate on the "alert_threshold_pct" field.
func AlertThresholdPctLTE(v float64) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldAlertThresholdPct, v))
}

// CooldownMinutesEQ applies the EQ predicate on the "cooldown_minutes" field.
func CooldownMinutesEQ(v int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldCooldownMinutes, v))
}

// CooldownMinutesNEQ applies the NEQ predicate on the "cooldown_minutes" field.
func CooldownMinutesNEQ(v int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldCooldownMinutes, v))
}

// CooldownMinutesIn applies the In predicate on the "cooldown_minutes" field.
func CooldownMinutesIn(vs ...int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldCooldownMinutes, vs...))
}

// CooldownMinutesNotIn applies the NotIn predicate on the "cooldown_minutes" field.
func CooldownMinutesNotIn(vs ...int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldCooldownMinutes, vs...))
}

// CooldownMinutesGT applies the GT predicate on the "cooldown_minutes" field.
func CooldownMinutesGT(v int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldCooldownMinutes, v))
}

// CooldownMinutesGTE applies the GTE predicate on the "cooldown_minutes" field.
func CooldownMinutesGTE(v int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldCooldownMinutes, v))
}

// CooldownMinutesLT applies the LT predicate on the "cooldown_minutes" field.
func CooldownMinutesLT(v int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldCooldownMinutes, v))
}

// CooldownMinutesLTE applies the LTE predicate on the "cooldown_minutes" field.
func CooldownMinutesLTE(v int) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldCooldownMinutes, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldEnabled, v))
}

// LastSyncAtEQ applies the EQ predicate on the "last_sync_at" field.
func LastSyncAtEQ(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastSyncAtNEQ applies the NEQ predicate on the "last_sync_at" field.
func LastSyncAtNEQ(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldLastSyncAt, v))
}

// LastSyncAtIn applies the In predicate on the "last_sync_at" field.
func LastSyncAtIn(vs ...time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldLastSyncAt, vs...))
}

// LastSyncAtNotIn applies the NotIn predicate on the "last_sync_at" field.
func LastSyncAtNotIn(vs ...time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldLastSyncAt, vs...))
}

// LastSyncAtGT applies the GT predicate on the "last_sync_at" field.
func LastSyncAtGT(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldLastSyncAt, v))
}

// LastSyncAtGTE applies the GTE predicate on the "last_sync_at" field.
func LastSyncAtGTE(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldLastSyncAt, v))
}

// LastSyncAtLT applies the LT predicate on the "last_sync_at" field.
func LastSyncAtLT(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldLastSyncAt, v))
}

// LastSyncAtLTE applies the LTE predicate on the "last_sync_at" field.
func LastSyncAtLTE(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldLastSyncAt, v))
}

// LastSyncAtIsNil applies the IsNil predicate on the "last_sync_at" field.
func LastSyncAtIsNil() predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIsNull(FieldLastSyncAt))
}

// LastSyncAtNotNil applies the NotNil predicate on the "last_sync_at" field.
func LastSyncAtNotNil() predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotNull(FieldLastSyncAt))
}

// LastSyncStatusEQ applies the EQ predicate on the "last_sync_status" field.
func LastSyncStatusEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldLastSyncStatus, v))
}

// LastSyncStatusNEQ applies the NEQ predicate on the "last_sync_status" field.
func LastSyncStatusNEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldLastSyncStatus, v))
}

// LastSyncStatusIn applies the In predicate on the "last_sync_status" field.
func LastSyncStatusIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldLastSyncStatus, vs...))
}

// LastSyncStatusNotIn applies the NotIn predicate on the "last_sync_status" field.
func LastSyncStatusNotIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldLastSyncStatus, vs...))
}

// LastSyncStatusGT applies the GT predicate on the "last_sync_status" field.
func LastSyncStatusGT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldLastSyncStatus, v))
}

// LastSyncStatusGTE applies the GTE predicate on the "last_sync_status" field.
func LastSyncStatusGTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldLastSyncStatus, v))
}

// LastSyncStatusLT applies the LT predicate on the "last_sync_status" field.
func LastSyncStatusLT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldLastSyncStatus, v))
}

// LastSyncStatusLTE applies the LTE predicate on the "last_sync_status" field.
func LastSyncStatusLTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldLastSyncStatus, v))
}

// LastSyncStatusContains applies the Contains predicate on the "last_sync_status" field.
func LastSyncStatusContains(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContains(FieldLastSyncStatus, v))
}

// LastSyncStatusHasPrefix applies the HasPrefix predicate on the "last_sync_status" field.
func LastSyncStatusHasPrefix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasPrefix(FieldLastSyncStatus, v))
}

// LastSyncStatusHasSuffix applies the HasSuffix predicate on the "last_sync_status" field.
func LastSyncStatusHasSuffix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasSuffix(FieldLastSyncStatus, v))
}

// LastSyncStatusEqualFold applies the EqualFold predicate on the "last_sync_status" field.
func LastSyncStatusEqualFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEqualFold(FieldLastSyncStatus, v))
}

// LastSyncStatusContainsFold applies the ContainsFold predicate on the "last_sync_status" field.
func LastSyncStatusContainsFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContainsFold(FieldLastSyncStatus, v))
}

// LastSyncErrorEQ applies the EQ predicate on the "last_sync_error" field.
func LastSyncErrorEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldLastSyncError, v))
}

// LastSyncErrorNEQ applies the NEQ predicate on the "last_sync_error" field.
func LastSyncErrorNEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldLastSyncError, v))
}

// LastSyncErrorIn applies the In predicate on the "last_sync_error" field.
func LastSyncErrorIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldLastSyncError, vs...))
}

// LastSyncErrorNotIn applies the NotIn predicate on the "last_sync_error" field.
func LastSyncErrorNotIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldLastSyncError, vs...))
}

// LastSyncErrorGT applies the GT predicate on the "last_sync_error" field.
func LastSyncErrorGT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldLastSyncError, v))
}

// LastSyncErrorGTE applies the GTE predicate on the "last_sync_error" field.
func LastSyncErrorGTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldLastSyncError, v))
}

// LastSyncErrorLT applies the LT predicate on the "last_sync_error" field.
func LastSyncErrorLT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldLastSyncError, v))
}

// LastSyncErrorLTE applies the LTE predicate on the "last_sync_error" field.
func LastSyncErrorLTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldLastSyncError, v))
}

// LastSyncErrorContains applies the Contains predicate on the "last_sync_error" field.
func LastSyncErrorContains(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContains(FieldLastSyncError, v))
}

// LastSyncErrorHasPrefix applies the HasPrefix predicate on the "last_sync_error" field.
func LastSyncErrorHasPrefix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasPrefix(FieldLastSyncError, v))
}

// LastSyncErrorHasSuffix applies the HasSuffix predicate on the "last_sync_error" field.
func LastSyncErrorHasSuffix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasSuffix(FieldLastSyncError, v))
}

// LastSyncErrorIsNil applies the IsNil predicate on the "last_sync_error" field.
func LastSyncErrorIsNil() predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIsNull(FieldLastSyncError))
}

// LastSyncErrorNotNil applies the NotNil predicate on the "last_sync_error" field.
func LastSyncErrorNotNil() predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotNull(FieldLastSyncError))
}

// LastSyncErrorEqualFold applies the EqualFold predicate on the "last_sync_error" field.
func LastSyncErrorEqualFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEqualFold(FieldLastSyncError, v))
}

// LastSyncErrorContainsFold applies the ContainsFold predicate on the "last_sync_error" field.
func LastSyncErrorContainsFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContainsFold(FieldLastSyncError, v))
}

// LastHashEQ applies the EQ predicate on the "last_hash" field.
func LastHashEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldLastHash, v))
}

// LastHashNEQ applies the NEQ predicate on the "last_hash" field.
func LastHashNEQ(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldLastHash, v))
}

// LastHashIn applies the In predicate on the "last_hash" field.
func LastHashIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldLastHash, vs...))
}

// LastHashNotIn applies the NotIn predicate on the "last_hash" field.
func LastHashNotIn(vs ...string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldLastHash, vs...))
}

// LastHashGT applies the GT predicate on the "last_hash" field.
func LastHashGT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldLastHash, v))
}

// LastHashGTE applies the GTE predicate on the "last_hash" field.
func LastHashGTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldLastHash, v))
}

// LastHashLT applies the LT predicate on the "last_hash" field.
func LastHashLT(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldLastHash, v))
}

// LastHashLTE applies the LTE predicate on the "last_hash" field.
func LastHashLTE(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldLastHash, v))
}

// LastHashContains applies the Contains predicate on the "last_hash" field.
func LastHashContains(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContains(FieldLastHash, v))
}

// LastHashHasPrefix applies the HasPrefix predicate on the "last_hash" field.
func LastHashHasPrefix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasPrefix(FieldLastHash, v))
}

// LastHashHasSuffix applies the HasSuffix predicate on the "last_hash" field.
func LastHashHasSuffix(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldHasSuffix(FieldLastHash, v))
}

// LastHashIsNil applies the IsNil predicate on the "last_hash" field.
func LastHashIsNil() predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIsNull(FieldLastHash))
}

// LastHashNotNil applies the NotNil predicate on the "last_hash" field.
func LastHashNotNil() predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotNull(FieldLastHash))
}

// LastHashEqualFold applies the EqualFold predicate on the "last_hash" field.
func LastHashEqualFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEqualFold(FieldLastHash, v))
}

// LastHashContainsFold applies the ContainsFold predicate on the "last_hash" field.
func LastHashContainsFold(v string) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldContainsFold(FieldLastHash, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPrices applies the HasEdge predicate on the "prices" edge.
func HasPrices() predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PricesTable, PricesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPricesWith applies the HasEdge predicate on the "prices" edge with a given conditions (other predicates).
func HasPricesWith(preds ...predicate.UpstreamModelPrice) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(func(s *sql.Selector) {
		step := newPricesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChanges applies the HasEdge predicate on the "changes" edge.
func HasChanges() predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChangesTable, ChangesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChangesWith applies the HasEdge predicate on the "changes" edge with a given conditions (other predicates).
func HasChangesWith(preds ...predicate.UpstreamPriceChange) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(func(s *sql.Selector) {
		step := newChangesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamPriceSource) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamPriceSource) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamPriceSource) predicate.UpstreamPriceSource {
	return predicate.UpstreamPriceSource(sql.NotPredicates(p))
}
