// Code generated by ent, DO NOT EDIT.

package upstreammodelprice

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLTE(FieldID, id))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldSourceID, v))
}

// ModelName applies equality check predicate on the "model_name" field. It's identical to ModelNameEQ.
func ModelName(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldModelName, v))
}

// LocalModelName applies equality check predicate on the "local_model_name" field. It's identical to LocalModelNameEQ.
func LocalModelName(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldLocalModelName, v))
}

// InputPrice applies equality check predicate on the "input_price" field. It's identical to InputPriceEQ.
func InputPrice(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldInputPrice, v))
}

// OutputPrice applies equality check predicate on the "output_price" field. It's identical to OutputPriceEQ.
func OutputPrice(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldOutputPrice, v))
}

// CacheWritePrice applies equality check predicate on the "cache_write_price" field. It's identical to CacheWritePriceEQ.
func CacheWritePrice(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldCacheWritePrice, v))
}

// CacheReadPrice applies equality check predicate on the "cache_read_price" field. It's identical to CacheReadPriceEQ.
func CacheReadPrice(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldCacheReadPrice, v))
}

// ImageOutputPrice applies equality check predicate on the "image_output_price" field. It's identical to ImageOutputPriceEQ.
func ImageOutputPrice(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldImageOutputPrice, v))
}

// PerRequestPrice applies equality check predicate on the "per_request_price" field. It's identical to PerRequestPriceEQ.
func PerRequestPrice(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldPerRequestPrice, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldCurrency, v))
}

// FetchedAt applies equality check predicate on the "fetched_at" field. It's identical to FetchedAtEQ.
func FetchedAt(v time.Time) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldFetchedAt, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotIn(FieldSourceID, vs...))
}

// ModelNameEQ applies the EQ predicate on the "model_name" field.
func ModelNameEQ(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldModelName, v))
}

// ModelNameNEQ applies the NEQ predicate on the "model_name" field.
func ModelNameNEQ(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNEQ(FieldModelName, v))
}

// ModelNameIn applies the In predicate on the "model_name" field.
func ModelNameIn(vs ...string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIn(FieldModelName, vs...))
}

// ModelNameNotIn applies the NotIn predicate on the "model_name" field.
func ModelNameNotIn(vs ...string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotIn(FieldModelName, vs...))
}

// ModelNameGT applies the GT predicate on the "model_name" field.
func ModelNameGT(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGT(FieldModelName, v))
}

// ModelNameGTE applies the GTE predicate on the "model_name" field.
func ModelNameGTE(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGTE(FieldModelName, v))
}

// ModelNameLT applies the LT predicate on the "model_name" field.
func ModelNameLT(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLT(FieldModelName, v))
}

// ModelNameLTE applies the LTE predicate on the "model_name" field.
func ModelNameLTE(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLTE(FieldModelName, v))
}

// ModelNameContains applies the Contains predicate on the "model_name" field.
func ModelNameContains(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldContains(FieldModelName, v))
}

// ModelNameHasPrefix applies the HasPrefix predicate on the "model_name" field.
func ModelNameHasPrefix(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldHasPrefix(FieldModelName, v))
}

// ModelNameHasSuffix applies the HasSuffix predicate on the "model_name" field.
func ModelNameHasSuffix(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldHasSuffix(FieldModelName, v))
}

// ModelNameEqualFold applies the EqualFold predicate on the "model_name" field.
func ModelNameEqualFold(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEqualFold(FieldModelName, v))
}

// ModelNameContainsFold applies the ContainsFold predicate on the "model_name" field.
func ModelNameContainsFold(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldContainsFold(FieldModelName, v))
}

// LocalModelNameEQ applies the EQ predicate on the "local_model_name" field.
func LocalModelNameEQ(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldLocalModelName, v))
}

// LocalModelNameNEQ applies the NEQ predicate on the "local_model_name" field.
func LocalModelNameNEQ(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNEQ(FieldLocalModelName, v))
}

// LocalModelNameIn applies the In predicate on the "local_model_name" field.
func LocalModelNameIn(vs ...string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIn(FieldLocalModelName, vs...))
}

// LocalModelNameNotIn applies the NotIn predicate on the "local_model_name" field.
func LocalModelNameNotIn(vs ...string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotIn(FieldLocalModelName, vs...))
}

// LocalModelNameGT applies the GT predicate on the "local_model_name" field.
func LocalModelNameGT(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGT(FieldLocalModelName, v))
}

// LocalModelNameGTE applies the GTE predicate on the "local_model_name" field.
func LocalModelNameGTE(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGTE(FieldLocalModelName, v))
}

// LocalModelNameLT applies the LT predicate on the "local_model_name" field.
func LocalModelNameLT(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLT(FieldLocalModelName, v))
}

// LocalModelNameLTE applies the LTE predicate on the "local_model_name" field.
func LocalModelNameLTE(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLTE(FieldLocalModelName, v))
}

// LocalModelNameContains applies the Contains predicate on the "local_model_name" field.
func LocalModelNameContains(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldContains(FieldLocalModelName, v))
}

// LocalModelNameHasPrefix applies the HasPrefix predicate on the "local_model_name" field.
func LocalModelNameHasPrefix(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldHasPrefix(FieldLocalModelName, v))
}

// LocalModelNameHasSuffix applies the HasSuffix predicate on the "local_model_name" field.
func LocalModelNameHasSuffix(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldHasSuffix(FieldLocalModelName, v))
}

// LocalModelNameIsNil applies the IsNil predicate on the "local_model_name" field.
func LocalModelNameIsNil() predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIsNull(FieldLocalModelName))
}

// LocalModelNameNotNil applies the NotNil predicate on the "local_model_name" field.
func LocalModelNameNotNil() predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotNull(FieldLocalModelName))
}

// LocalModelNameEqualFold applies the EqualFold predicate on the "local_model_name" field.
func LocalModelNameEqualFold(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEqualFold(FieldLocalModelName, v))
}

// LocalModelNameContainsFold applies the ContainsFold predicate on the "local_model_name" field.
func LocalModelNameContainsFold(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldContainsFold(FieldLocalModelName, v))
}

// InputPriceEQ applies the EQ predicate on the "input_price" field.
func InputPriceEQ(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldInputPrice, v))
}

// InputPriceNEQ applies the NEQ predicate on the "input_price" field.
func InputPriceNEQ(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNEQ(FieldInputPrice, v))
}

// InputPriceIn applies the In predicate on the "input_price" field.
func InputPriceIn(vs ...float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIn(FieldInputPrice, vs...))
}

// InputPriceNotIn applies the NotIn predicate on the "input_price" field.
func InputPriceNotIn(vs ...float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotIn(FieldInputPrice, vs...))
}

// InputPriceGT applies the GT predicate on the "input_price" field.
func InputPriceGT(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGT(FieldInputPrice, v))
}

// InputPriceGTE applies the GTE predicate on the "input_price" field.
func InputPriceGTE(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGTE(FieldInputPrice, v))
}

// InputPriceLT applies the LT predicate on the "input_price" field.
func InputPriceLT(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLT(FieldInputPrice, v))
}

// InputPriceLTE applies the LTE predicate on the "input_price" field.
func InputPriceLTE(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLTE(FieldInputPrice, v))
}

// OutputPriceEQ applies the EQ predicate on the "output_price" field.
func OutputPriceEQ(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldOutputPrice, v))
}

// OutputPriceNEQ applies the NEQ predicate on the "output_price" field.
func OutputPriceNEQ(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNEQ(FieldOutputPrice, v))
}

// OutputPriceIn applies the In predicate on the "output_price" field.
func OutputPriceIn(vs ...float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIn(FieldOutputPrice, vs...))
}

// OutputPriceNotIn applies the NotIn predicate on the "output_price" field.
func OutputPriceNotIn(vs ...float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotIn(FieldOutputPrice, vs...))
}

// OutputPriceGT applies the GT predicate on the "output_price" field.
func OutputPriceGT(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGT(FieldOutputPrice, v))
}

// OutputPriceGTE applies the GTE predicate on the "output_price" field.
func OutputPriceGTE(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGTE(FieldOutputPrice, v))
}

// OutputPriceLT applies the LT predicate on the "output_price" field.
func OutputPriceLT(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLT(FieldOutputPrice, v))
}

// OutputPriceLTE applies the LTE predicate on the "output_price" field.
func OutputPriceLTE(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLTE(FieldOutputPrice, v))
}

// CacheWritePriceEQ applies the EQ predicate on the "cache_write_price" field.
func CacheWritePriceEQ(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldCacheWritePrice, v))
}

// CacheWritePriceNEQ applies the NEQ predicate on the "cache_write_price" field.
func CacheWritePriceNEQ(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNEQ(FieldCacheWritePrice, v))
}

// CacheWritePriceIn applies the In predicate on the "cache_write_price" field.
func CacheWritePriceIn(vs ...float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIn(FieldCacheWritePrice, vs...))
}

// CacheWritePriceNotIn applies the NotIn predicate on the "cache_write_price" field.
func CacheWritePriceNotIn(vs ...float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotIn(FieldCacheWritePrice, vs...))
}

// CacheWritePriceGT applies the GT predicate on the "cache_write_price" field.
func CacheWritePriceGT(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGT(FieldCacheWritePrice, v))
}

// CacheWritePriceGTE applies the GTE predicate on the "cache_write_price" field.
func CacheWritePriceGTE(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGTE(FieldCacheWritePrice, v))
}

// CacheWritePriceLT applies the LT predicate on the "cache_write_price" field.
func CacheWritePriceLT(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLT(FieldCacheWritePrice, v))
}

// CacheWritePriceLTE applies the LTE predicate on the "cache_write_price" field.
func CacheWritePriceLTE(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLTE(FieldCacheWritePrice, v))
}

// CacheWritePriceIsNil applies the IsNil predicate on the "cache_write_price" field.
func CacheWritePriceIsNil() predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIsNull(FieldCacheWritePrice))
}

// CacheWritePriceNotNil applies the NotNil predicate on the "cache_write_price" field.
func CacheWritePriceNotNil() predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotNull(FieldCacheWritePrice))
}

// CacheReadPriceEQ applies the EQ predicate on the "cache_read_price" field.
func CacheReadPriceEQ(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldCacheReadPrice, v))
}

// CacheReadPriceNEQ applies the NEQ predicate on the "cache_read_price" field.
func CacheReadPriceNEQ(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNEQ(FieldCacheReadPrice, v))
}

// CacheReadPriceIn applies the In predicate on the "cache_read_price" field.
func CacheReadPriceIn(vs ...float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIn(FieldCacheReadPrice, vs...))
}

// CacheReadPriceNotIn applies the NotIn predicate on the "cache_read_price" field.
func CacheReadPriceNotIn(vs ...float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotIn(FieldCacheReadPrice, vs...))
}

// CacheReadPriceGT applies the GT predicate on the "cache_read_price" field.
func CacheReadPriceGT(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGT(FieldCacheReadPrice, v))
}

// CacheReadPriceGTE applies the GTE predicate on the "cache_read_price" field.
func CacheReadPriceGTE(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGTE(FieldCacheReadPrice, v))
}

// CacheReadPriceLT applies the LT predicate on the "cache_read_price" field.
func CacheReadPriceLT(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLT(FieldCacheReadPrice, v))
}

// CacheReadPriceLTE applies the LTE predicate on the "cache_read_price" field.
func CacheReadPriceLTE(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLTE(FieldCacheReadPrice, v))
}

// CacheReadPriceIsNil applies the IsNil predicate on the "cache_read_price" field.
func CacheReadPriceIsNil() predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIsNull(FieldCacheReadPrice))
}

// CacheReadPriceNotNil applies the NotNil predicate on the "cache_read_price" field.
func CacheReadPriceNotNil() predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotNull(FieldCacheReadPrice))
}

// ImageOutputPriceEQ applies the EQ predicate on the "image_output_price" field.
func ImageOutputPriceEQ(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldImageOutputPrice, v))
}

// ImageOutputPriceNEQ applies the NEQ predicate on the "image_output_price" field.
func ImageOutputPriceNEQ(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNEQ(FieldImageOutputPrice, v))
}

// ImageOutputPriceIn applies the In predicate on the "image_output_price" field.
func ImageOutputPriceIn(vs ...float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIn(FieldImageOutputPrice, vs...))
}

// ImageOutputPriceNotIn applies the NotIn predicate on the "image_output_price" field.
func ImageOutputPriceNotIn(vs ...float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotIn(FieldImageOutputPrice, vs...))
}

// ImageOutputPriceGT applies the GT predicate on the "image_output_price" field.
func ImageOutputPriceGT(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGT(FieldImageOutputPrice, v))
}

// ImageOutputPriceGTE applies the GTE predicate on the "image_output_price" field.
func ImageOutputPriceGTE(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGTE(FieldImageOutputPrice, v))
}

// ImageOutputPriceLT applies the LT predicate on the "image_output_price" field.
func ImageOutputPriceLT(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLT(FieldImageOutputPrice, v))
}

// ImageOutputPriceLTE applies the LTE predicate on the "image_output_price" field.
func ImageOutputPriceLTE(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLTE(FieldImageOutputPrice, v))
}

// ImageOutputPriceIsNil applies the IsNil predicate on the "image_output_price" field.
func ImageOutputPriceIsNil() predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIsNull(FieldImageOutputPrice))
}

// ImageOutputPriceNotNil applies the NotNil predicate on the "image_output_price" field.
func ImageOutputPriceNotNil() predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotNull(FieldImageOutputPrice))
}

// PerRequestPriceEQ applies the EQ predicate on the "per_request_price" field.
func PerRequestPriceEQ(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldPerRequestPrice, v))
}

// PerRequestPriceNEQ applies the NEQ predicate on the "per_request_price" field.
func PerRequestPriceNEQ(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNEQ(FieldPerRequestPrice, v))
}

// PerRequestPriceIn applies the In predicate on the "per_request_price" field.
func PerRequestPriceIn(vs ...float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIn(FieldPerRequestPrice, vs...))
}

// PerRequestPriceNotIn applies the NotIn predicate on the "per_request_price" field.
func PerRequestPriceNotIn(vs ...float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotIn(FieldPerRequestPrice, vs...))
}

// PerRequestPriceGT applies the GT predicate on the "per_request_price" field.
func PerRequestPriceGT(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGT(FieldPerRequestPrice, v))
}

// PerRequestPriceGTE applies the GTE predicate on the "per_request_price" field.
func PerRequestPriceGTE(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGTE(FieldPerRequestPrice, v))
}

// PerRequestPriceLT applies the LT predicate on the "per_request_price" field.
func PerRequestPriceLT(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLT(FieldPerRequestPrice, v))
}

// PerRequestPriceLTE applies the LTE predicate on the "per_request_price" field.
func PerRequestPriceLTE(v float64) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLTE(FieldPerRequestPrice, v))
}

// PerRequestPriceIsNil applies the IsNil predicate on the "per_request_price" field.
func PerRequestPriceIsNil() predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIsNull(FieldPerRequestPrice))
}

// PerRequestPriceNotNil applies the NotNil predicate on the "per_request_price" field.
func PerRequestPriceNotNil() predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotNull(FieldPerRequestPrice))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldContainsFold(FieldCurrency, v))
}

// RawPayloadIsNil applies the IsNil predicate on the "raw_payload" field.
func RawPayloadIsNil() predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIsNull(FieldRawPayload))
}

// RawPayloadNotNil applies the NotNil predicate on the "raw_payload" field.
func RawPayloadNotNil() predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotNull(FieldRawPayload))
}

// FetchedAtEQ applies the EQ predicate on the "fetched_at" field.
func FetchedAtEQ(v time.Time) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldEQ(FieldFetchedAt, v))
}

// FetchedAtNEQ applies the NEQ predicate on the "fetched_at" field.
func FetchedAtNEQ(v time.Time) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNEQ(FieldFetchedAt, v))
}

// FetchedAtIn applies the In predicate on the "fetched_at" field.
func FetchedAtIn(vs ...time.Time) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldIn(FieldFetchedAt, vs...))
}

// FetchedAtNotIn applies the NotIn predicate on the "fetched_at" field.
func FetchedAtNotIn(vs ...time.Time) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldNotIn(FieldFetchedAt, vs...))
}

// FetchedAtGT applies the GT predicate on the "fetched_at" field.
func FetchedAtGT(v time.Time) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGT(FieldFetchedAt, v))
}

// FetchedAtGTE applies the GTE predicate on the "fetched_at" field.
func FetchedAtGTE(v time.Time) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldGTE(FieldFetchedAt, v))
}

// FetchedAtLT applies the LT predicate on the "fetched_at" field.
func FetchedAtLT(v time.Time) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLT(FieldFetchedAt, v))
}

// FetchedAtLTE applies the LTE predicate on the "fetched_at" field.
func FetchedAtLTE(v time.Time) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.FieldLTE(FieldFetchedAt, v))
}

// HasSource applies the HasEdge predicate on the "source" edge.
func HasSource() predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceTable, SourceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceWith applies the HasEdge predicate on the "source" edge with a given conditions (other predicates).
func HasSourceWith(preds ...predicate.UpstreamPriceSource) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(func(s *sql.Selector) {
		step := newSourceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamModelPrice) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamModelPrice) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamModelPrice) predicate.UpstreamModelPrice {
	return predicate.UpstreamModelPrice(sql.NotPredicates(p))
}
