// Code generated by ent, DO NOT EDIT.

package bundleplangroupquota

import (
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLTE(FieldID, id))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldPlanID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldGroupID, v))
}

// QuotaScope applies equality check predicate on the "quota_scope" field. It's identical to QuotaScopeEQ.
func QuotaScope(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldQuotaScope, v))
}

// ModelPattern applies equality check predicate on the "model_pattern" field. It's identical to ModelPatternEQ.
func ModelPattern(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldModelPattern, v))
}

// DailyLimitUsd applies equality check predicate on the "daily_limit_usd" field. It's identical to DailyLimitUsdEQ.
func DailyLimitUsd(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldDailyLimitUsd, v))
}

// WeeklyLimitUsd applies equality check predicate on the "weekly_limit_usd" field. It's identical to WeeklyLimitUsdEQ.
func WeeklyLimitUsd(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldWeeklyLimitUsd, v))
}

// MonthlyLimitUsd applies equality check predicate on the "monthly_limit_usd" field. It's identical to MonthlyLimitUsdEQ.
func MonthlyLimitUsd(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldMonthlyLimitUsd, v))
}

// DailyImageLimitCount applies equality check predicate on the "daily_image_limit_count" field. It's identical to DailyImageLimitCountEQ.
func DailyImageLimitCount(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldDailyImageLimitCount, v))
}

// WeeklyImageLimitCount applies equality check predicate on the "weekly_image_limit_count" field. It's identical to WeeklyImageLimitCountEQ.
func WeeklyImageLimitCount(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldWeeklyImageLimitCount, v))
}

// MonthlyImageLimitCount applies equality check predicate on the "monthly_image_limit_count" field. It's identical to MonthlyImageLimitCountEQ.
func MonthlyImageLimitCount(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldMonthlyImageLimitCount, v))
}

// DailyVideoLimitCount applies equality check predicate on the "daily_video_limit_count" field. It's identical to DailyVideoLimitCountEQ.
func DailyVideoLimitCount(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldDailyVideoLimitCount, v))
}

// WeeklyVideoLimitCount applies equality check predicate on the "weekly_video_limit_count" field. It's identical to WeeklyVideoLimitCountEQ.
func WeeklyVideoLimitCount(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldWeeklyVideoLimitCount, v))
}

// MonthlyVideoLimitCount applies equality check predicate on the "monthly_video_limit_count" field. It's identical to MonthlyVideoLimitCountEQ.
func MonthlyVideoLimitCount(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldMonthlyVideoLimitCount, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNotIn(FieldPlanID, vs...))
}

// PlanIDGT applies the GT predicate on the "plan_id" field.
func PlanIDGT(v int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGT(FieldPlanID, v))
}

// PlanIDGTE applies the GTE predicate on the "plan_id" field.
func PlanIDGTE(v int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGTE(FieldPlanID, v))
}

// PlanIDLT applies the LT predicate on the "plan_id" field.
func PlanIDLT(v int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLT(FieldPlanID, v))
}

// PlanIDLTE applies the LTE predicate on the "plan_id" field.
func PlanIDLTE(v int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLTE(FieldPlanID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLTE(FieldGroupID, v))
}

// QuotaScopeEQ applies the EQ predicate on the "quota_scope" field.
func QuotaScopeEQ(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldQuotaScope, v))
}

// QuotaScopeNEQ applies the NEQ predicate on the "quota_scope" field.
func QuotaScopeNEQ(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNEQ(FieldQuotaScope, v))
}

// QuotaScopeIn applies the In predicate on the "quota_scope" field.
func QuotaScopeIn(vs ...string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldIn(FieldQuotaScope, vs...))
}

// QuotaScopeNotIn applies the NotIn predicate on the "quota_scope" field.
func QuotaScopeNotIn(vs ...string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNotIn(FieldQuotaScope, vs...))
}

// QuotaScopeGT applies the GT predicate on the "quota_scope" field.
func QuotaScopeGT(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGT(FieldQuotaScope, v))
}

// QuotaScopeGTE applies the GTE predicate on the "quota_scope" field.
func QuotaScopeGTE(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGTE(FieldQuotaScope, v))
}

// QuotaScopeLT applies the LT predicate on the "quota_scope" field.
func QuotaScopeLT(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLT(FieldQuotaScope, v))
}

// QuotaScopeLTE applies the LTE predicate on the "quota_scope" field.
func QuotaScopeLTE(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLTE(FieldQuotaScope, v))
}

// QuotaScopeContains applies the Contains predicate on the "quota_scope" field.
func QuotaScopeContains(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldContains(FieldQuotaScope, v))
}

// QuotaScopeHasPrefix applies the HasPrefix predicate on the "quota_scope" field.
func QuotaScopeHasPrefix(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldHasPrefix(FieldQuotaScope, v))
}

// QuotaScopeHasSuffix applies the HasSuffix predicate on the "quota_scope" field.
func QuotaScopeHasSuffix(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldHasSuffix(FieldQuotaScope, v))
}

// QuotaScopeEqualFold applies the EqualFold predicate on the "quota_scope" field.
func QuotaScopeEqualFold(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEqualFold(FieldQuotaScope, v))
}

// QuotaScopeContainsFold applies the ContainsFold predicate on the "quota_scope" field.
func QuotaScopeContainsFold(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldContainsFold(FieldQuotaScope, v))
}

// ModelPatternEQ applies the EQ predicate on the "model_pattern" field.
func ModelPatternEQ(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldModelPattern, v))
}

// ModelPatternNEQ applies the NEQ predicate on the "model_pattern" field.
func ModelPatternNEQ(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNEQ(FieldModelPattern, v))
}

// ModelPatternIn applies the In predicate on the "model_pattern" field.
func ModelPatternIn(vs ...string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldIn(FieldModelPattern, vs...))
}

// ModelPatternNotIn applies the NotIn predicate on the "model_pattern" field.
func ModelPatternNotIn(vs ...string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNotIn(FieldModelPattern, vs...))
}

// ModelPatternGT applies the GT predicate on the "model_pattern" field.
func ModelPatternGT(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGT(FieldModelPattern, v))
}

// ModelPatternGTE applies the GTE predicate on the "model_pattern" field.
func ModelPatternGTE(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGTE(FieldModelPattern, v))
}

// ModelPatternLT applies the LT predicate on the "model_pattern" field.
func ModelPatternLT(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLT(FieldModelPattern, v))
}

// ModelPatternLTE applies the LTE predicate on the "model_pattern" field.
func ModelPatternLTE(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLTE(FieldModelPattern, v))
}

// ModelPatternContains applies the Contains predicate on the "model_pattern" field.
func ModelPatternContains(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldContains(FieldModelPattern, v))
}

// ModelPatternHasPrefix applies the HasPrefix predicate on the "model_pattern" field.
func ModelPatternHasPrefix(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldHasPrefix(FieldModelPattern, v))
}

// ModelPatternHasSuffix applies the HasSuffix predicate on the "model_pattern" field.
func ModelPatternHasSuffix(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldHasSuffix(FieldModelPattern, v))
}

// ModelPatternEqualFold applies the EqualFold predicate on the "model_pattern" field.
func ModelPatternEqualFold(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEqualFold(FieldModelPattern, v))
}

// ModelPatternContainsFold applies the ContainsFold predicate on the "model_pattern" field.
func ModelPatternContainsFold(v string) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldContainsFold(FieldModelPattern, v))
}

// DailyLimitUsdEQ applies the EQ predicate on the "daily_limit_usd" field.
func DailyLimitUsdEQ(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldDailyLimitUsd, v))
}

// DailyLimitUsdNEQ applies the NEQ predicate on the "daily_limit_usd" field.
func DailyLimitUsdNEQ(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNEQ(FieldDailyLimitUsd, v))
}

// DailyLimitUsdIn applies the In predicate on the "daily_limit_usd" field.
func DailyLimitUsdIn(vs ...float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldIn(FieldDailyLimitUsd, vs...))
}

// DailyLimitUsdNotIn applies the NotIn predicate on the "daily_limit_usd" field.
func DailyLimitUsdNotIn(vs ...float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNotIn(FieldDailyLimitUsd, vs...))
}

// DailyLimitUsdGT applies the GT predicate on the "daily_limit_usd" field.
func DailyLimitUsdGT(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGT(FieldDailyLimitUsd, v))
}

// DailyLimitUsdGTE applies the GTE predicate on the "daily_limit_usd" field.
func DailyLimitUsdGTE(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGTE(FieldDailyLimitUsd, v))
}

// DailyLimitUsdLT applies the LT predicate on the "daily_limit_usd" field.
func DailyLimitUsdLT(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLT(FieldDailyLimitUsd, v))
}

// DailyLimitUsdLTE applies the LTE predicate on the "daily_limit_usd" field.
func DailyLimitUsdLTE(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLTE(FieldDailyLimitUsd, v))
}

// WeeklyLimitUsdEQ applies the EQ predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdEQ(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdNEQ applies the NEQ predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNEQ(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNEQ(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdIn applies the In predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdIn(vs ...float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldIn(FieldWeeklyLimitUsd, vs...))
}

// WeeklyLimitUsdNotIn applies the NotIn predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNotIn(vs ...float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNotIn(FieldWeeklyLimitUsd, vs...))
}

// WeeklyLimitUsdGT applies the GT predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdGT(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGT(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdGTE applies the GTE predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdGTE(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGTE(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdLT applies the LT predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdLT(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLT(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdLTE applies the LTE predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdLTE(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLTE(FieldWeeklyLimitUsd, v))
}

// MonthlyLimitUsdEQ applies the EQ predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdEQ(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdNEQ applies the NEQ predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNEQ(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNEQ(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdIn applies the In predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdIn(vs ...float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldIn(FieldMonthlyLimitUsd, vs...))
}

// MonthlyLimitUsdNotIn applies the NotIn predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNotIn(vs ...float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNotIn(FieldMonthlyLimitUsd, vs...))
}

// MonthlyLimitUsdGT applies the GT predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdGT(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGT(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdGTE applies the GTE predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdGTE(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGTE(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdLT applies the LT predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdLT(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLT(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdLTE applies the LTE predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdLTE(v float64) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLTE(FieldMonthlyLimitUsd, v))
}

// DailyImageLimitCountEQ applies the EQ predicate on the "daily_image_limit_count" field.
func DailyImageLimitCountEQ(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldDailyImageLimitCount, v))
}

// DailyImageLimitCountNEQ applies the NEQ predicate on the "daily_image_limit_count" field.
func DailyImageLimitCountNEQ(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNEQ(FieldDailyImageLimitCount, v))
}

// DailyImageLimitCountIn applies the In predicate on the "daily_image_limit_count" field.
func DailyImageLimitCountIn(vs ...int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldIn(FieldDailyImageLimitCount, vs...))
}

// DailyImageLimitCountNotIn applies the NotIn predicate on the "daily_image_limit_count" field.
func DailyImageLimitCountNotIn(vs ...int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNotIn(FieldDailyImageLimitCount, vs...))
}

// DailyImageLimitCountGT applies the GT predicate on the "daily_image_limit_count" field.
func DailyImageLimitCountGT(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGT(FieldDailyImageLimitCount, v))
}

// DailyImageLimitCountGTE applies the GTE predicate on the "daily_image_limit_count" field.
func DailyImageLimitCountGTE(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGTE(FieldDailyImageLimitCount, v))
}

// DailyImageLimitCountLT applies the LT predicate on the "daily_image_limit_count" field.
func DailyImageLimitCountLT(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLT(FieldDailyImageLimitCount, v))
}

// DailyImageLimitCountLTE applies the LTE predicate on the "daily_image_limit_count" field.
func DailyImageLimitCountLTE(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLTE(FieldDailyImageLimitCount, v))
}

// WeeklyImageLimitCountEQ applies the EQ predicate on the "weekly_image_limit_count" field.
func WeeklyImageLimitCountEQ(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldWeeklyImageLimitCount, v))
}

// WeeklyImageLimitCountNEQ applies the NEQ predicate on the "weekly_image_limit_count" field.
func WeeklyImageLimitCountNEQ(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNEQ(FieldWeeklyImageLimitCount, v))
}

// WeeklyImageLimitCountIn applies the In predicate on the "weekly_image_limit_count" field.
func WeeklyImageLimitCountIn(vs ...int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldIn(FieldWeeklyImageLimitCount, vs...))
}

// WeeklyImageLimitCountNotIn applies the NotIn predicate on the "weekly_image_limit_count" field.
func WeeklyImageLimitCountNotIn(vs ...int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNotIn(FieldWeeklyImageLimitCount, vs...))
}

// WeeklyImageLimitCountGT applies the GT predicate on the "weekly_image_limit_count" field.
func WeeklyImageLimitCountGT(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGT(FieldWeeklyImageLimitCount, v))
}

// WeeklyImageLimitCountGTE applies the GTE predicate on the "weekly_image_limit_count" field.
func WeeklyImageLimitCountGTE(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGTE(FieldWeeklyImageLimitCount, v))
}

// WeeklyImageLimitCountLT applies the LT predicate on the "weekly_image_limit_count" field.
func WeeklyImageLimitCountLT(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLT(FieldWeeklyImageLimitCount, v))
}

// WeeklyImageLimitCountLTE applies the LTE predicate on the "weekly_image_limit_count" field.
func WeeklyImageLimitCountLTE(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLTE(FieldWeeklyImageLimitCount, v))
}

// MonthlyImageLimitCountEQ applies the EQ predicate on the "monthly_image_limit_count" field.
func MonthlyImageLimitCountEQ(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldMonthlyImageLimitCount, v))
}

// MonthlyImageLimitCountNEQ applies the NEQ predicate on the "monthly_image_limit_count" field.
func MonthlyImageLimitCountNEQ(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNEQ(FieldMonthlyImageLimitCount, v))
}

// MonthlyImageLimitCountIn applies the In predicate on the "monthly_image_limit_count" field.
func MonthlyImageLimitCountIn(vs ...int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldIn(FieldMonthlyImageLimitCount, vs...))
}

// MonthlyImageLimitCountNotIn applies the NotIn predicate on the "monthly_image_limit_count" field.
func MonthlyImageLimitCountNotIn(vs ...int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNotIn(FieldMonthlyImageLimitCount, vs...))
}

// MonthlyImageLimitCountGT applies the GT predicate on the "monthly_image_limit_count" field.
func MonthlyImageLimitCountGT(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGT(FieldMonthlyImageLimitCount, v))
}

// MonthlyImageLimitCountGTE applies the GTE predicate on the "monthly_image_limit_count" field.
func MonthlyImageLimitCountGTE(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGTE(FieldMonthlyImageLimitCount, v))
}

// MonthlyImageLimitCountLT applies the LT predicate on the "monthly_image_limit_count" field.
func MonthlyImageLimitCountLT(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLT(FieldMonthlyImageLimitCount, v))
}

// MonthlyImageLimitCountLTE applies the LTE predicate on the "monthly_image_limit_count" field.
func MonthlyImageLimitCountLTE(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLTE(FieldMonthlyImageLimitCount, v))
}

// DailyVideoLimitCountEQ applies the EQ predicate on the "daily_video_limit_count" field.
func DailyVideoLimitCountEQ(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldDailyVideoLimitCount, v))
}

// DailyVideoLimitCountNEQ applies the NEQ predicate on the "daily_video_limit_count" field.
func DailyVideoLimitCountNEQ(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNEQ(FieldDailyVideoLimitCount, v))
}

// DailyVideoLimitCountIn applies the In predicate on the "daily_video_limit_count" field.
func DailyVideoLimitCountIn(vs ...int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldIn(FieldDailyVideoLimitCount, vs...))
}

// DailyVideoLimitCountNotIn applies the NotIn predicate on the "daily_video_limit_count" field.
func DailyVideoLimitCountNotIn(vs ...int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNotIn(FieldDailyVideoLimitCount, vs...))
}

// DailyVideoLimitCountGT applies the GT predicate on the "daily_video_limit_count" field.
func DailyVideoLimitCountGT(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGT(FieldDailyVideoLimitCount, v))
}

// DailyVideoLimitCountGTE applies the GTE predicate on the "daily_video_limit_count" field.
func DailyVideoLimitCountGTE(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGTE(FieldDailyVideoLimitCount, v))
}

// DailyVideoLimitCountLT applies the LT predicate on the "daily_video_limit_count" field.
func DailyVideoLimitCountLT(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLT(FieldDailyVideoLimitCount, v))
}

// DailyVideoLimitCountLTE applies the LTE predicate on the "daily_video_limit_count" field.
func DailyVideoLimitCountLTE(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLTE(FieldDailyVideoLimitCount, v))
}

// WeeklyVideoLimitCountEQ applies the EQ predicate on the "weekly_video_limit_count" field.
func WeeklyVideoLimitCountEQ(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldWeeklyVideoLimitCount, v))
}

// WeeklyVideoLimitCountNEQ applies the NEQ predicate on the "weekly_video_limit_count" field.
func WeeklyVideoLimitCountNEQ(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNEQ(FieldWeeklyVideoLimitCount, v))
}

// WeeklyVideoLimitCountIn applies the In predicate on the "weekly_video_limit_count" field.
func WeeklyVideoLimitCountIn(vs ...int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldIn(FieldWeeklyVideoLimitCount, vs...))
}

// WeeklyVideoLimitCountNotIn applies the NotIn predicate on the "weekly_video_limit_count" field.
func WeeklyVideoLimitCountNotIn(vs ...int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNotIn(FieldWeeklyVideoLimitCount, vs...))
}

// WeeklyVideoLimitCountGT applies the GT predicate on the "weekly_video_limit_count" field.
func WeeklyVideoLimitCountGT(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGT(FieldWeeklyVideoLimitCount, v))
}

// WeeklyVideoLimitCountGTE applies the GTE predicate on the "weekly_video_limit_count" field.
func WeeklyVideoLimitCountGTE(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGTE(FieldWeeklyVideoLimitCount, v))
}

// WeeklyVideoLimitCountLT applies the LT predicate on the "weekly_video_limit_count" field.
func WeeklyVideoLimitCountLT(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLT(FieldWeeklyVideoLimitCount, v))
}

// WeeklyVideoLimitCountLTE applies the LTE predicate on the "weekly_video_limit_count" field.
func WeeklyVideoLimitCountLTE(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLTE(FieldWeeklyVideoLimitCount, v))
}

// MonthlyVideoLimitCountEQ applies the EQ predicate on the "monthly_video_limit_count" field.
func MonthlyVideoLimitCountEQ(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldEQ(FieldMonthlyVideoLimitCount, v))
}

// MonthlyVideoLimitCountNEQ applies the NEQ predicate on the "monthly_video_limit_count" field.
func MonthlyVideoLimitCountNEQ(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNEQ(FieldMonthlyVideoLimitCount, v))
}

// MonthlyVideoLimitCountIn applies the In predicate on the "monthly_video_limit_count" field.
func MonthlyVideoLimitCountIn(vs ...int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldIn(FieldMonthlyVideoLimitCount, vs...))
}

// MonthlyVideoLimitCountNotIn applies the NotIn predicate on the "monthly_video_limit_count" field.
func MonthlyVideoLimitCountNotIn(vs ...int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldNotIn(FieldMonthlyVideoLimitCount, vs...))
}

// MonthlyVideoLimitCountGT applies the GT predicate on the "monthly_video_limit_count" field.
func MonthlyVideoLimitCountGT(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGT(FieldMonthlyVideoLimitCount, v))
}

// MonthlyVideoLimitCountGTE applies the GTE predicate on the "monthly_video_limit_count" field.
func MonthlyVideoLimitCountGTE(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldGTE(FieldMonthlyVideoLimitCount, v))
}

// MonthlyVideoLimitCountLT applies the LT predicate on the "monthly_video_limit_count" field.
func MonthlyVideoLimitCountLT(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLT(FieldMonthlyVideoLimitCount, v))
}

// MonthlyVideoLimitCountLTE applies the LTE predicate on the "monthly_video_limit_count" field.
func MonthlyVideoLimitCountLTE(v int) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.FieldLTE(FieldMonthlyVideoLimitCount, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BundlePlanGroupQuota) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BundlePlanGroupQuota) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BundlePlanGroupQuota) predicate.BundlePlanGroupQuota {
	return predicate.BundlePlanGroupQuota(sql.NotPredicates(p))
}
