// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/adminnotification"
)

// AdminNotification is the model entity for the AdminNotification schema.
type AdminNotification struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 通知类型: system / price_change / ops_alert 等
	Type string `json:"type,omitempty"`
	// 通知标题
	Title string `json:"title,omitempty"`
	// 通知内容（支持 Markdown）
	Content string `json:"content,omitempty"`
	// 严重级别: info / warning / critical
	Severity string `json:"severity,omitempty"`
	// 关联跳转链接（可空）
	TargetLink string `json:"target_link,omitempty"`
	// 关联实体ID列表（JSON 数组）
	RelatedIds []int64 `json:"related_ids,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdminNotificationQuery when eager-loading is set.
	Edges        AdminNotificationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AdminNotificationEdges holds the relations/edges for other nodes in the graph.
type AdminNotificationEdges struct {
	// Reads holds the value of the reads edge.
	Reads []*AdminNotificationRead `json:"reads,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ReadsOrErr returns the Reads value or an error if the edge
// was not loaded in eager-loading.
func (e AdminNotificationEdges) ReadsOrErr() ([]*AdminNotificationRead, error) {
	if e.loadedTypes[0] {
		return e.Reads, nil
	}
	return nil, &NotLoadedError{edge: "reads"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdminNotification) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adminnotification.FieldRelatedIds:
			values[i] = new([]byte)
		case adminnotification.FieldID:
			values[i] = new(sql.NullInt64)
		case adminnotification.FieldType, adminnotification.FieldTitle, adminnotification.FieldContent, adminnotification.FieldSeverity, adminnotification.FieldTargetLink:
			values[i] = new(sql.NullString)
		case adminnotification.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdminNotification fields.
func (_m *AdminNotification) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adminnotification.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case adminnotification.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case adminnotification.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case adminnotification.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case adminnotification.FieldSeverity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				_m.Severity = value.String
			}
		case adminnotification.FieldTargetLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_link", values[i])
			} else if value.Valid {
				_m.TargetLink = value.String
			}
		case adminnotification.FieldRelatedIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field related_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RelatedIds); err != nil {
					return fmt.Errorf("unmarshal field related_ids: %w", err)
				}
			}
		case adminnotification.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdminNotification.
// This includes values selected through modifiers, order, etc.
func (_m *AdminNotification) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryReads queries the "reads" edge of the AdminNotification entity.
func (_m *AdminNotification) QueryReads() *AdminNotificationReadQuery {
	return NewAdminNotificationClient(_m.config).QueryReads(_m)
}

// Update returns a builder for updating this AdminNotification.
// Note that you need to call AdminNotification.Unwrap() before calling this method if this AdminNotification
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdminNotification) Update() *AdminNotificationUpdateOne {
	return NewAdminNotificationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdminNotification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdminNotification) Unwrap() *AdminNotification {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdminNotification is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdminNotification) String() string {
	var builder strings.Builder
	builder.WriteString("AdminNotification(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("severity=")
	builder.WriteString(_m.Severity)
	builder.WriteString(", ")
	builder.WriteString("target_link=")
	builder.WriteString(_m.TargetLink)
	builder.WriteString(", ")
	builder.WriteString("related_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.RelatedIds))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AdminNotifications is a parsable slice of AdminNotification.
type AdminNotifications []*AdminNotification
