// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/adminnotification"
	"github.com/Wei-Shaw/sub2api/ent/adminnotificationread"
)

// AdminNotificationRead is the model entity for the AdminNotificationRead schema.
type AdminNotificationRead struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// NotificationID holds the value of the "notification_id" field.
	NotificationID int64 `json:"notification_id,omitempty"`
	// 已读用户ID（管理员）
	UserID int64 `json:"user_id,omitempty"`
	// 用户首次已读时间
	ReadAt time.Time `json:"read_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdminNotificationReadQuery when eager-loading is set.
	Edges        AdminNotificationReadEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AdminNotificationReadEdges holds the relations/edges for other nodes in the graph.
type AdminNotificationReadEdges struct {
	// Notification holds the value of the notification edge.
	Notification *AdminNotification `json:"notification,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NotificationOrErr returns the Notification value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdminNotificationReadEdges) NotificationOrErr() (*AdminNotification, error) {
	if e.Notification != nil {
		return e.Notification, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: adminnotification.Label}
	}
	return nil, &NotLoadedError{edge: "notification"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdminNotificationRead) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adminnotificationread.FieldID, adminnotificationread.FieldNotificationID, adminnotificationread.FieldUserID:
			values[i] = new(sql.NullInt64)
		case adminnotificationread.FieldReadAt, adminnotificationread.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdminNotificationRead fields.
func (_m *AdminNotificationRead) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adminnotificationread.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case adminnotificationread.FieldNotificationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field notification_id", values[i])
			} else if value.Valid {
				_m.NotificationID = value.Int64
			}
		case adminnotificationread.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case adminnotificationread.FieldReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field read_at", values[i])
			} else if value.Valid {
				_m.ReadAt = value.Time
			}
		case adminnotificationread.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdminNotificationRead.
// This includes values selected through modifiers, order, etc.
func (_m *AdminNotificationRead) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryNotification queries the "notification" edge of the AdminNotificationRead entity.
func (_m *AdminNotificationRead) QueryNotification() *AdminNotificationQuery {
	return NewAdminNotificationReadClient(_m.config).QueryNotification(_m)
}

// Update returns a builder for updating this AdminNotificationRead.
// Note that you need to call AdminNotificationRead.Unwrap() before calling this method if this AdminNotificationRead
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdminNotificationRead) Update() *AdminNotificationReadUpdateOne {
	return NewAdminNotificationReadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdminNotificationRead entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdminNotificationRead) Unwrap() *AdminNotificationRead {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdminNotificationRead is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdminNotificationRead) String() string {
	var builder strings.Builder
	builder.WriteString("AdminNotificationRead(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("notification_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.NotificationID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("read_at=")
	builder.WriteString(_m.ReadAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AdminNotificationReads is a parsable slice of AdminNotificationRead.
type AdminNotificationReads []*AdminNotificationRead
