// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adminnotification"
	"github.com/Wei-Shaw/sub2api/ent/adminnotificationread"
)

// AdminNotificationReadCreate is the builder for creating a AdminNotificationRead entity.
type AdminNotificationReadCreate struct {
	config
	mutation *AdminNotificationReadMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNotificationID sets the "notification_id" field.
func (_c *AdminNotificationReadCreate) SetNotificationID(v int64) *AdminNotificationReadCreate {
	_c.mutation.SetNotificationID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AdminNotificationReadCreate) SetUserID(v int64) *AdminNotificationReadCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetReadAt sets the "read_at" field.
func (_c *AdminNotificationReadCreate) SetReadAt(v time.Time) *AdminNotificationReadCreate {
	_c.mutation.SetReadAt(v)
	return _c
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_c *AdminNotificationReadCreate) SetNillableReadAt(v *time.Time) *AdminNotificationReadCreate {
	if v != nil {
		_c.SetReadAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdminNotificationReadCreate) SetCreatedAt(v time.Time) *AdminNotificationReadCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdminNotificationReadCreate) SetNillableCreatedAt(v *time.Time) *AdminNotificationReadCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetNotification sets the "notification" edge to the AdminNotification entity.
func (_c *AdminNotificationReadCreate) SetNotification(v *AdminNotification) *AdminNotificationReadCreate {
	return _c.SetNotificationID(v.ID)
}

// Mutation returns the AdminNotificationReadMutation object of the builder.
func (_c *AdminNotificationReadCreate) Mutation() *AdminNotificationReadMutation {
	return _c.mutation
}

// Save creates the AdminNotificationRead in the database.
func (_c *AdminNotificationReadCreate) Save(ctx context.Context) (*AdminNotificationRead, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdminNotificationReadCreate) SaveX(ctx context.Context) *AdminNotificationRead {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminNotificationReadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminNotificationReadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdminNotificationReadCreate) defaults() {
	if _, ok := _c.mutation.ReadAt(); !ok {
		v := adminnotificationread.DefaultReadAt()
		_c.mutation.SetReadAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := adminnotificationread.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdminNotificationReadCreate) check() error {
	if _, ok := _c.mutation.NotificationID(); !ok {
		return &ValidationError{Name: "notification_id", err: errors.New(`ent: missing required field "AdminNotificationRead.notification_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AdminNotificationRead.user_id"`)}
	}
	if _, ok := _c.mutation.ReadAt(); !ok {
		return &ValidationError{Name: "read_at", err: errors.New(`ent: missing required field "AdminNotificationRead.read_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminNotificationRead.created_at"`)}
	}
	if len(_c.mutation.NotificationIDs()) == 0 {
		return &ValidationError{Name: "notification", err: errors.New(`ent: missing required edge "AdminNotificationRead.notification"`)}
	}
	return nil
}

func (_c *AdminNotificationReadCreate) sqlSave(ctx context.Context) (*AdminNotificationRead, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdminNotificationReadCreate) createSpec() (*AdminNotificationRead, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminNotificationRead{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adminnotificationread.Table, sqlgraph.NewFieldSpec(adminnotificationread.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(adminnotificationread.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ReadAt(); ok {
		_spec.SetField(adminnotificationread.FieldReadAt, field.TypeTime, value)
		_node.ReadAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adminnotificationread.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.NotificationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminnotificationread.NotificationTable,
			Columns: []string{adminnotificationread.NotificationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminnotification.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NotificationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdminNotificationRead.Create().
//		SetNotificationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdminNotificationReadUpsert) {
//			SetNotificationID(v+v).
//		}).
//		Exec(ctx)
func (_c *AdminNotificationReadCreate) OnConflict(opts ...sql.ConflictOption) *AdminNotificationReadUpsertOne {
	_c.conflict = opts
	return &AdminNotificationReadUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdminNotificationRead.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdminNotificationReadCreate) OnConflictColumns(columns ...string) *AdminNotificationReadUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdminNotificationReadUpsertOne{
		create: _c,
	}
}

type (
	// AdminNotificationReadUpsertOne is the builder for "upsert"-ing
	//  one AdminNotificationRead node.
	AdminNotificationReadUpsertOne struct {
		create *AdminNotificationReadCreate
	}

	// AdminNotificationReadUpsert is the "OnConflict" setter.
	AdminNotificationReadUpsert struct {
		*sql.UpdateSet
	}
)

// SetNotificationID sets the "notification_id" field.
func (u *AdminNotificationReadUpsert) SetNotificationID(v int64) *AdminNotificationReadUpsert {
	u.Set(adminnotificationread.FieldNotificationID, v)
	return u
}

// UpdateNotificationID sets the "notification_id" field to the value that was provided on create.
func (u *AdminNotificationReadUpsert) UpdateNotificationID() *AdminNotificationReadUpsert {
	u.SetExcluded(adminnotificationread.FieldNotificationID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AdminNotificationReadUpsert) SetUserID(v int64) *AdminNotificationReadUpsert {
	u.Set(adminnotificationread.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdminNotificationReadUpsert) UpdateUserID() *AdminNotificationReadUpsert {
	u.SetExcluded(adminnotificationread.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *AdminNotificationReadUpsert) AddUserID(v int64) *AdminNotificationReadUpsert {
	u.Add(adminnotificationread.FieldUserID, v)
	return u
}

// SetReadAt sets the "read_at" field.
func (u *AdminNotificationReadUpsert) SetReadAt(v time.Time) *AdminNotificationReadUpsert {
	u.Set(adminnotificationread.FieldReadAt, v)
	return u
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *AdminNotificationReadUpsert) UpdateReadAt() *AdminNotificationReadUpsert {
	u.SetExcluded(adminnotificationread.FieldReadAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AdminNotificationRead.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdminNotificationReadUpsertOne) UpdateNewValues() *AdminNotificationReadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(adminnotificationread.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdminNotificationRead.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AdminNotificationReadUpsertOne) Ignore() *AdminNotificationReadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdminNotificationReadUpsertOne) DoNothing() *AdminNotificationReadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdminNotificationReadCreate.OnConflict
// documentation for more info.
func (u *AdminNotificationReadUpsertOne) Update(set func(*AdminNotificationReadUpsert)) *AdminNotificationReadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdminNotificationReadUpsert{UpdateSet: update})
	}))
	return u
}

// SetNotificationID sets the "notification_id" field.
func (u *AdminNotificationReadUpsertOne) SetNotificationID(v int64) *AdminNotificationReadUpsertOne {
	return u.Update(func(s *AdminNotificationReadUpsert) {
		s.SetNotificationID(v)
	})
}

// UpdateNotificationID sets the "notification_id" field to the value that was provided on create.
func (u *AdminNotificationReadUpsertOne) UpdateNotificationID() *AdminNotificationReadUpsertOne {
	return u.Update(func(s *AdminNotificationReadUpsert) {
		s.UpdateNotificationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AdminNotificationReadUpsertOne) SetUserID(v int64) *AdminNotificationReadUpsertOne {
	return u.Update(func(s *AdminNotificationReadUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AdminNotificationReadUpsertOne) AddUserID(v int64) *AdminNotificationReadUpsertOne {
	return u.Update(func(s *AdminNotificationReadUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdminNotificationReadUpsertOne) UpdateUserID() *AdminNotificationReadUpsertOne {
	return u.Update(func(s *AdminNotificationReadUpsert) {
		s.UpdateUserID()
	})
}

// SetReadAt sets the "read_at" field.
func (u *AdminNotificationReadUpsertOne) SetReadAt(v time.Time) *AdminNotificationReadUpsertOne {
	return u.Update(func(s *AdminNotificationReadUpsert) {
		s.SetReadAt(v)
	})
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *AdminNotificationReadUpsertOne) UpdateReadAt() *AdminNotificationReadUpsertOne {
	return u.Update(func(s *AdminNotificationReadUpsert) {
		s.UpdateReadAt()
	})
}

// Exec executes the query.
func (u *AdminNotificationReadUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdminNotificationReadCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdminNotificationReadUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AdminNotificationReadUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AdminNotificationReadUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AdminNotificationReadCreateBulk is the builder for creating many AdminNotificationRead entities in bulk.
type AdminNotificationReadCreateBulk struct {
	config
	err      error
	builders []*AdminNotificationReadCreate
	conflict []sql.ConflictOption
}

// Save creates the AdminNotificationRead entities in the database.
func (_c *AdminNotificationReadCreateBulk) Save(ctx context.Context) ([]*AdminNotificationRead, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdminNotificationRead, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminNotificationReadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdminNotificationReadCreateBulk) SaveX(ctx context.Context) []*AdminNotificationRead {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminNotificationReadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminNotificationReadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdminNotificationRead.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdminNotificationReadUpsert) {
//			SetNotificationID(v+v).
//		}).
//		Exec(ctx)
func (_c *AdminNotificationReadCreateBulk) OnConflict(opts ...sql.ConflictOption) *AdminNotificationReadUpsertBulk {
	_c.conflict = opts
	return &AdminNotificationReadUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdminNotificationRead.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdminNotificationReadCreateBulk) OnConflictColumns(columns ...string) *AdminNotificationReadUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdminNotificationReadUpsertBulk{
		create: _c,
	}
}

// AdminNotificationReadUpsertBulk is the builder for "upsert"-ing
// a bulk of AdminNotificationRead nodes.
type AdminNotificationReadUpsertBulk struct {
	create *AdminNotificationReadCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AdminNotificationRead.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdminNotificationReadUpsertBulk) UpdateNewValues() *AdminNotificationReadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(adminnotificationread.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdminNotificationRead.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AdminNotificationReadUpsertBulk) Ignore() *AdminNotificationReadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdminNotificationReadUpsertBulk) DoNothing() *AdminNotificationReadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdminNotificationReadCreateBulk.OnConflict
// documentation for more info.
func (u *AdminNotificationReadUpsertBulk) Update(set func(*AdminNotificationReadUpsert)) *AdminNotificationReadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdminNotificationReadUpsert{UpdateSet: update})
	}))
	return u
}

// SetNotificationID sets the "notification_id" field.
func (u *AdminNotificationReadUpsertBulk) SetNotificationID(v int64) *AdminNotificationReadUpsertBulk {
	return u.Update(func(s *AdminNotificationReadUpsert) {
		s.SetNotificationID(v)
	})
}

// UpdateNotificationID sets the "notification_id" field to the value that was provided on create.
func (u *AdminNotificationReadUpsertBulk) UpdateNotificationID() *AdminNotificationReadUpsertBulk {
	return u.Update(func(s *AdminNotificationReadUpsert) {
		s.UpdateNotificationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AdminNotificationReadUpsertBulk) SetUserID(v int64) *AdminNotificationReadUpsertBulk {
	return u.Update(func(s *AdminNotificationReadUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AdminNotificationReadUpsertBulk) AddUserID(v int64) *AdminNotificationReadUpsertBulk {
	return u.Update(func(s *AdminNotificationReadUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AdminNotificationReadUpsertBulk) UpdateUserID() *AdminNotificationReadUpsertBulk {
	return u.Update(func(s *AdminNotificationReadUpsert) {
		s.UpdateUserID()
	})
}

// SetReadAt sets the "read_at" field.
func (u *AdminNotificationReadUpsertBulk) SetReadAt(v time.Time) *AdminNotificationReadUpsertBulk {
	return u.Update(func(s *AdminNotificationReadUpsert) {
		s.SetReadAt(v)
	})
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *AdminNotificationReadUpsertBulk) UpdateReadAt() *AdminNotificationReadUpsertBulk {
	return u.Update(func(s *AdminNotificationReadUpsert) {
		s.UpdateReadAt()
	})
}

// Exec executes the query.
func (u *AdminNotificationReadUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AdminNotificationReadCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdminNotificationReadCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdminNotificationReadUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
