// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/bundleplangroupquota"
)

// BundlePlanGroupQuota is the model entity for the BundlePlanGroupQuota schema.
type BundlePlanGroupQuota struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// → BundlePlan
	PlanID int64 `json:"plan_id,omitempty"`
	// → Group（复用现有 Group）
	GroupID int64 `json:"group_id,omitempty"`
	// 额度粒度: platform/model
	QuotaScope string `json:"quota_scope,omitempty"`
	// 仅 model 级别生效，glob 模式
	ModelPattern string `json:"model_pattern,omitempty"`
	// 日额度（0=不限）
	DailyLimitUsd float64 `json:"daily_limit_usd,omitempty"`
	// 周额度（0=不限）
	WeeklyLimitUsd float64 `json:"weekly_limit_usd,omitempty"`
	// 月额度（0=不限）
	MonthlyLimitUsd float64 `json:"monthly_limit_usd,omitempty"`
	selectValues    sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BundlePlanGroupQuota) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bundleplangroupquota.FieldDailyLimitUsd, bundleplangroupquota.FieldWeeklyLimitUsd, bundleplangroupquota.FieldMonthlyLimitUsd:
			values[i] = new(sql.NullFloat64)
		case bundleplangroupquota.FieldID, bundleplangroupquota.FieldPlanID, bundleplangroupquota.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case bundleplangroupquota.FieldQuotaScope, bundleplangroupquota.FieldModelPattern:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BundlePlanGroupQuota fields.
func (_m *BundlePlanGroupQuota) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bundleplangroupquota.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case bundleplangroupquota.FieldPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = value.Int64
			}
		case bundleplangroupquota.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case bundleplangroupquota.FieldQuotaScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quota_scope", values[i])
			} else if value.Valid {
				_m.QuotaScope = value.String
			}
		case bundleplangroupquota.FieldModelPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_pattern", values[i])
			} else if value.Valid {
				_m.ModelPattern = value.String
			}
		case bundleplangroupquota.FieldDailyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_limit_usd", values[i])
			} else if value.Valid {
				_m.DailyLimitUsd = value.Float64
			}
		case bundleplangroupquota.FieldWeeklyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_limit_usd", values[i])
			} else if value.Valid {
				_m.WeeklyLimitUsd = value.Float64
			}
		case bundleplangroupquota.FieldMonthlyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_limit_usd", values[i])
			} else if value.Valid {
				_m.MonthlyLimitUsd = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BundlePlanGroupQuota.
// This includes values selected through modifiers, order, etc.
func (_m *BundlePlanGroupQuota) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BundlePlanGroupQuota.
// Note that you need to call BundlePlanGroupQuota.Unwrap() before calling this method if this BundlePlanGroupQuota
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BundlePlanGroupQuota) Update() *BundlePlanGroupQuotaUpdateOne {
	return NewBundlePlanGroupQuotaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BundlePlanGroupQuota entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BundlePlanGroupQuota) Unwrap() *BundlePlanGroupQuota {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BundlePlanGroupQuota is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BundlePlanGroupQuota) String() string {
	var builder strings.Builder
	builder.WriteString("BundlePlanGroupQuota(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("plan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlanID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("quota_scope=")
	builder.WriteString(_m.QuotaScope)
	builder.WriteString(", ")
	builder.WriteString("model_pattern=")
	builder.WriteString(_m.ModelPattern)
	builder.WriteString(", ")
	builder.WriteString("daily_limit_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyLimitUsd))
	builder.WriteString(", ")
	builder.WriteString("weekly_limit_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.WeeklyLimitUsd))
	builder.WriteString(", ")
	builder.WriteString("monthly_limit_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyLimitUsd))
	builder.WriteByte(')')
	return builder.String()
}

// BundlePlanGroupQuotaSlice is a parsable slice of BundlePlanGroupQuota.
type BundlePlanGroupQuotaSlice []*BundlePlanGroupQuota
