// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bundleplangroupquota"
)

// BundlePlanGroupQuotaCreate is the builder for creating a BundlePlanGroupQuota entity.
type BundlePlanGroupQuotaCreate struct {
	config
	mutation *BundlePlanGroupQuotaMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPlanID sets the "plan_id" field.
func (_c *BundlePlanGroupQuotaCreate) SetPlanID(v int64) *BundlePlanGroupQuotaCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *BundlePlanGroupQuotaCreate) SetGroupID(v int64) *BundlePlanGroupQuotaCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetQuotaScope sets the "quota_scope" field.
func (_c *BundlePlanGroupQuotaCreate) SetQuotaScope(v string) *BundlePlanGroupQuotaCreate {
	_c.mutation.SetQuotaScope(v)
	return _c
}

// SetNillableQuotaScope sets the "quota_scope" field if the given value is not nil.
func (_c *BundlePlanGroupQuotaCreate) SetNillableQuotaScope(v *string) *BundlePlanGroupQuotaCreate {
	if v != nil {
		_c.SetQuotaScope(*v)
	}
	return _c
}

// SetModelPattern sets the "model_pattern" field.
func (_c *BundlePlanGroupQuotaCreate) SetModelPattern(v string) *BundlePlanGroupQuotaCreate {
	_c.mutation.SetModelPattern(v)
	return _c
}

// SetNillableModelPattern sets the "model_pattern" field if the given value is not nil.
func (_c *BundlePlanGroupQuotaCreate) SetNillableModelPattern(v *string) *BundlePlanGroupQuotaCreate {
	if v != nil {
		_c.SetModelPattern(*v)
	}
	return _c
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_c *BundlePlanGroupQuotaCreate) SetDailyLimitUsd(v float64) *BundlePlanGroupQuotaCreate {
	_c.mutation.SetDailyLimitUsd(v)
	return _c
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_c *BundlePlanGroupQuotaCreate) SetNillableDailyLimitUsd(v *float64) *BundlePlanGroupQuotaCreate {
	if v != nil {
		_c.SetDailyLimitUsd(*v)
	}
	return _c
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (_c *BundlePlanGroupQuotaCreate) SetWeeklyLimitUsd(v float64) *BundlePlanGroupQuotaCreate {
	_c.mutation.SetWeeklyLimitUsd(v)
	return _c
}

// SetNillableWeeklyLimitUsd sets the "weekly_limit_usd" field if the given value is not nil.
func (_c *BundlePlanGroupQuotaCreate) SetNillableWeeklyLimitUsd(v *float64) *BundlePlanGroupQuotaCreate {
	if v != nil {
		_c.SetWeeklyLimitUsd(*v)
	}
	return _c
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_c *BundlePlanGroupQuotaCreate) SetMonthlyLimitUsd(v float64) *BundlePlanGroupQuotaCreate {
	_c.mutation.SetMonthlyLimitUsd(v)
	return _c
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_c *BundlePlanGroupQuotaCreate) SetNillableMonthlyLimitUsd(v *float64) *BundlePlanGroupQuotaCreate {
	if v != nil {
		_c.SetMonthlyLimitUsd(*v)
	}
	return _c
}

// Mutation returns the BundlePlanGroupQuotaMutation object of the builder.
func (_c *BundlePlanGroupQuotaCreate) Mutation() *BundlePlanGroupQuotaMutation {
	return _c.mutation
}

// Save creates the BundlePlanGroupQuota in the database.
func (_c *BundlePlanGroupQuotaCreate) Save(ctx context.Context) (*BundlePlanGroupQuota, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BundlePlanGroupQuotaCreate) SaveX(ctx context.Context) *BundlePlanGroupQuota {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BundlePlanGroupQuotaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BundlePlanGroupQuotaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BundlePlanGroupQuotaCreate) defaults() {
	if _, ok := _c.mutation.QuotaScope(); !ok {
		v := bundleplangroupquota.DefaultQuotaScope
		_c.mutation.SetQuotaScope(v)
	}
	if _, ok := _c.mutation.ModelPattern(); !ok {
		v := bundleplangroupquota.DefaultModelPattern
		_c.mutation.SetModelPattern(v)
	}
	if _, ok := _c.mutation.DailyLimitUsd(); !ok {
		v := bundleplangroupquota.DefaultDailyLimitUsd
		_c.mutation.SetDailyLimitUsd(v)
	}
	if _, ok := _c.mutation.WeeklyLimitUsd(); !ok {
		v := bundleplangroupquota.DefaultWeeklyLimitUsd
		_c.mutation.SetWeeklyLimitUsd(v)
	}
	if _, ok := _c.mutation.MonthlyLimitUsd(); !ok {
		v := bundleplangroupquota.DefaultMonthlyLimitUsd
		_c.mutation.SetMonthlyLimitUsd(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BundlePlanGroupQuotaCreate) check() error {
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "BundlePlanGroupQuota.plan_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "BundlePlanGroupQuota.group_id"`)}
	}
	if _, ok := _c.mutation.QuotaScope(); !ok {
		return &ValidationError{Name: "quota_scope", err: errors.New(`ent: missing required field "BundlePlanGroupQuota.quota_scope"`)}
	}
	if _, ok := _c.mutation.ModelPattern(); !ok {
		return &ValidationError{Name: "model_pattern", err: errors.New(`ent: missing required field "BundlePlanGroupQuota.model_pattern"`)}
	}
	if _, ok := _c.mutation.DailyLimitUsd(); !ok {
		return &ValidationError{Name: "daily_limit_usd", err: errors.New(`ent: missing required field "BundlePlanGroupQuota.daily_limit_usd"`)}
	}
	if _, ok := _c.mutation.WeeklyLimitUsd(); !ok {
		return &ValidationError{Name: "weekly_limit_usd", err: errors.New(`ent: missing required field "BundlePlanGroupQuota.weekly_limit_usd"`)}
	}
	if _, ok := _c.mutation.MonthlyLimitUsd(); !ok {
		return &ValidationError{Name: "monthly_limit_usd", err: errors.New(`ent: missing required field "BundlePlanGroupQuota.monthly_limit_usd"`)}
	}
	return nil
}

func (_c *BundlePlanGroupQuotaCreate) sqlSave(ctx context.Context) (*BundlePlanGroupQuota, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BundlePlanGroupQuotaCreate) createSpec() (*BundlePlanGroupQuota, *sqlgraph.CreateSpec) {
	var (
		_node = &BundlePlanGroupQuota{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bundleplangroupquota.Table, sqlgraph.NewFieldSpec(bundleplangroupquota.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.PlanID(); ok {
		_spec.SetField(bundleplangroupquota.FieldPlanID, field.TypeInt64, value)
		_node.PlanID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(bundleplangroupquota.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.QuotaScope(); ok {
		_spec.SetField(bundleplangroupquota.FieldQuotaScope, field.TypeString, value)
		_node.QuotaScope = value
	}
	if value, ok := _c.mutation.ModelPattern(); ok {
		_spec.SetField(bundleplangroupquota.FieldModelPattern, field.TypeString, value)
		_node.ModelPattern = value
	}
	if value, ok := _c.mutation.DailyLimitUsd(); ok {
		_spec.SetField(bundleplangroupquota.FieldDailyLimitUsd, field.TypeFloat64, value)
		_node.DailyLimitUsd = value
	}
	if value, ok := _c.mutation.WeeklyLimitUsd(); ok {
		_spec.SetField(bundleplangroupquota.FieldWeeklyLimitUsd, field.TypeFloat64, value)
		_node.WeeklyLimitUsd = value
	}
	if value, ok := _c.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(bundleplangroupquota.FieldMonthlyLimitUsd, field.TypeFloat64, value)
		_node.MonthlyLimitUsd = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BundlePlanGroupQuota.Create().
//		SetPlanID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BundlePlanGroupQuotaUpsert) {
//			SetPlanID(v+v).
//		}).
//		Exec(ctx)
func (_c *BundlePlanGroupQuotaCreate) OnConflict(opts ...sql.ConflictOption) *BundlePlanGroupQuotaUpsertOne {
	_c.conflict = opts
	return &BundlePlanGroupQuotaUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BundlePlanGroupQuota.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BundlePlanGroupQuotaCreate) OnConflictColumns(columns ...string) *BundlePlanGroupQuotaUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BundlePlanGroupQuotaUpsertOne{
		create: _c,
	}
}

type (
	// BundlePlanGroupQuotaUpsertOne is the builder for "upsert"-ing
	//  one BundlePlanGroupQuota node.
	BundlePlanGroupQuotaUpsertOne struct {
		create *BundlePlanGroupQuotaCreate
	}

	// BundlePlanGroupQuotaUpsert is the "OnConflict" setter.
	BundlePlanGroupQuotaUpsert struct {
		*sql.UpdateSet
	}
)

// SetPlanID sets the "plan_id" field.
func (u *BundlePlanGroupQuotaUpsert) SetPlanID(v int64) *BundlePlanGroupQuotaUpsert {
	u.Set(bundleplangroupquota.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsert) UpdatePlanID() *BundlePlanGroupQuotaUpsert {
	u.SetExcluded(bundleplangroupquota.FieldPlanID)
	return u
}

// AddPlanID adds v to the "plan_id" field.
func (u *BundlePlanGroupQuotaUpsert) AddPlanID(v int64) *BundlePlanGroupQuotaUpsert {
	u.Add(bundleplangroupquota.FieldPlanID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *BundlePlanGroupQuotaUpsert) SetGroupID(v int64) *BundlePlanGroupQuotaUpsert {
	u.Set(bundleplangroupquota.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsert) UpdateGroupID() *BundlePlanGroupQuotaUpsert {
	u.SetExcluded(bundleplangroupquota.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *BundlePlanGroupQuotaUpsert) AddGroupID(v int64) *BundlePlanGroupQuotaUpsert {
	u.Add(bundleplangroupquota.FieldGroupID, v)
	return u
}

// SetQuotaScope sets the "quota_scope" field.
func (u *BundlePlanGroupQuotaUpsert) SetQuotaScope(v string) *BundlePlanGroupQuotaUpsert {
	u.Set(bundleplangroupquota.FieldQuotaScope, v)
	return u
}

// UpdateQuotaScope sets the "quota_scope" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsert) UpdateQuotaScope() *BundlePlanGroupQuotaUpsert {
	u.SetExcluded(bundleplangroupquota.FieldQuotaScope)
	return u
}

// SetModelPattern sets the "model_pattern" field.
func (u *BundlePlanGroupQuotaUpsert) SetModelPattern(v string) *BundlePlanGroupQuotaUpsert {
	u.Set(bundleplangroupquota.FieldModelPattern, v)
	return u
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsert) UpdateModelPattern() *BundlePlanGroupQuotaUpsert {
	u.SetExcluded(bundleplangroupquota.FieldModelPattern)
	return u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsert) SetDailyLimitUsd(v float64) *BundlePlanGroupQuotaUpsert {
	u.Set(bundleplangroupquota.FieldDailyLimitUsd, v)
	return u
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsert) UpdateDailyLimitUsd() *BundlePlanGroupQuotaUpsert {
	u.SetExcluded(bundleplangroupquota.FieldDailyLimitUsd)
	return u
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsert) AddDailyLimitUsd(v float64) *BundlePlanGroupQuotaUpsert {
	u.Add(bundleplangroupquota.FieldDailyLimitUsd, v)
	return u
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsert) SetWeeklyLimitUsd(v float64) *BundlePlanGroupQuotaUpsert {
	u.Set(bundleplangroupquota.FieldWeeklyLimitUsd, v)
	return u
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsert) UpdateWeeklyLimitUsd() *BundlePlanGroupQuotaUpsert {
	u.SetExcluded(bundleplangroupquota.FieldWeeklyLimitUsd)
	return u
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsert) AddWeeklyLimitUsd(v float64) *BundlePlanGroupQuotaUpsert {
	u.Add(bundleplangroupquota.FieldWeeklyLimitUsd, v)
	return u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsert) SetMonthlyLimitUsd(v float64) *BundlePlanGroupQuotaUpsert {
	u.Set(bundleplangroupquota.FieldMonthlyLimitUsd, v)
	return u
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsert) UpdateMonthlyLimitUsd() *BundlePlanGroupQuotaUpsert {
	u.SetExcluded(bundleplangroupquota.FieldMonthlyLimitUsd)
	return u
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsert) AddMonthlyLimitUsd(v float64) *BundlePlanGroupQuotaUpsert {
	u.Add(bundleplangroupquota.FieldMonthlyLimitUsd, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BundlePlanGroupQuota.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BundlePlanGroupQuotaUpsertOne) UpdateNewValues() *BundlePlanGroupQuotaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BundlePlanGroupQuota.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BundlePlanGroupQuotaUpsertOne) Ignore() *BundlePlanGroupQuotaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BundlePlanGroupQuotaUpsertOne) DoNothing() *BundlePlanGroupQuotaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BundlePlanGroupQuotaCreate.OnConflict
// documentation for more info.
func (u *BundlePlanGroupQuotaUpsertOne) Update(set func(*BundlePlanGroupQuotaUpsert)) *BundlePlanGroupQuotaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BundlePlanGroupQuotaUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *BundlePlanGroupQuotaUpsertOne) SetPlanID(v int64) *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *BundlePlanGroupQuotaUpsertOne) AddPlanID(v int64) *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsertOne) UpdatePlanID() *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.UpdatePlanID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *BundlePlanGroupQuotaUpsertOne) SetGroupID(v int64) *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *BundlePlanGroupQuotaUpsertOne) AddGroupID(v int64) *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsertOne) UpdateGroupID() *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.UpdateGroupID()
	})
}

// SetQuotaScope sets the "quota_scope" field.
func (u *BundlePlanGroupQuotaUpsertOne) SetQuotaScope(v string) *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.SetQuotaScope(v)
	})
}

// UpdateQuotaScope sets the "quota_scope" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsertOne) UpdateQuotaScope() *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.UpdateQuotaScope()
	})
}

// SetModelPattern sets the "model_pattern" field.
func (u *BundlePlanGroupQuotaUpsertOne) SetModelPattern(v string) *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.SetModelPattern(v)
	})
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsertOne) UpdateModelPattern() *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.UpdateModelPattern()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsertOne) SetDailyLimitUsd(v float64) *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsertOne) AddDailyLimitUsd(v float64) *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsertOne) UpdateDailyLimitUsd() *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsertOne) SetWeeklyLimitUsd(v float64) *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.SetWeeklyLimitUsd(v)
	})
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsertOne) AddWeeklyLimitUsd(v float64) *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.AddWeeklyLimitUsd(v)
	})
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsertOne) UpdateWeeklyLimitUsd() *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.UpdateWeeklyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsertOne) SetMonthlyLimitUsd(v float64) *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsertOne) AddMonthlyLimitUsd(v float64) *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsertOne) UpdateMonthlyLimitUsd() *BundlePlanGroupQuotaUpsertOne {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// Exec executes the query.
func (u *BundlePlanGroupQuotaUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BundlePlanGroupQuotaCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BundlePlanGroupQuotaUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BundlePlanGroupQuotaUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BundlePlanGroupQuotaUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BundlePlanGroupQuotaCreateBulk is the builder for creating many BundlePlanGroupQuota entities in bulk.
type BundlePlanGroupQuotaCreateBulk struct {
	config
	err      error
	builders []*BundlePlanGroupQuotaCreate
	conflict []sql.ConflictOption
}

// Save creates the BundlePlanGroupQuota entities in the database.
func (_c *BundlePlanGroupQuotaCreateBulk) Save(ctx context.Context) ([]*BundlePlanGroupQuota, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BundlePlanGroupQuota, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BundlePlanGroupQuotaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BundlePlanGroupQuotaCreateBulk) SaveX(ctx context.Context) []*BundlePlanGroupQuota {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BundlePlanGroupQuotaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BundlePlanGroupQuotaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BundlePlanGroupQuota.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BundlePlanGroupQuotaUpsert) {
//			SetPlanID(v+v).
//		}).
//		Exec(ctx)
func (_c *BundlePlanGroupQuotaCreateBulk) OnConflict(opts ...sql.ConflictOption) *BundlePlanGroupQuotaUpsertBulk {
	_c.conflict = opts
	return &BundlePlanGroupQuotaUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BundlePlanGroupQuota.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BundlePlanGroupQuotaCreateBulk) OnConflictColumns(columns ...string) *BundlePlanGroupQuotaUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BundlePlanGroupQuotaUpsertBulk{
		create: _c,
	}
}

// BundlePlanGroupQuotaUpsertBulk is the builder for "upsert"-ing
// a bulk of BundlePlanGroupQuota nodes.
type BundlePlanGroupQuotaUpsertBulk struct {
	create *BundlePlanGroupQuotaCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BundlePlanGroupQuota.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BundlePlanGroupQuotaUpsertBulk) UpdateNewValues() *BundlePlanGroupQuotaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BundlePlanGroupQuota.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BundlePlanGroupQuotaUpsertBulk) Ignore() *BundlePlanGroupQuotaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BundlePlanGroupQuotaUpsertBulk) DoNothing() *BundlePlanGroupQuotaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BundlePlanGroupQuotaCreateBulk.OnConflict
// documentation for more info.
func (u *BundlePlanGroupQuotaUpsertBulk) Update(set func(*BundlePlanGroupQuotaUpsert)) *BundlePlanGroupQuotaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BundlePlanGroupQuotaUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *BundlePlanGroupQuotaUpsertBulk) SetPlanID(v int64) *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *BundlePlanGroupQuotaUpsertBulk) AddPlanID(v int64) *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsertBulk) UpdatePlanID() *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.UpdatePlanID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *BundlePlanGroupQuotaUpsertBulk) SetGroupID(v int64) *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *BundlePlanGroupQuotaUpsertBulk) AddGroupID(v int64) *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsertBulk) UpdateGroupID() *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.UpdateGroupID()
	})
}

// SetQuotaScope sets the "quota_scope" field.
func (u *BundlePlanGroupQuotaUpsertBulk) SetQuotaScope(v string) *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.SetQuotaScope(v)
	})
}

// UpdateQuotaScope sets the "quota_scope" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsertBulk) UpdateQuotaScope() *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.UpdateQuotaScope()
	})
}

// SetModelPattern sets the "model_pattern" field.
func (u *BundlePlanGroupQuotaUpsertBulk) SetModelPattern(v string) *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.SetModelPattern(v)
	})
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsertBulk) UpdateModelPattern() *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.UpdateModelPattern()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsertBulk) SetDailyLimitUsd(v float64) *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsertBulk) AddDailyLimitUsd(v float64) *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsertBulk) UpdateDailyLimitUsd() *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsertBulk) SetWeeklyLimitUsd(v float64) *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.SetWeeklyLimitUsd(v)
	})
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsertBulk) AddWeeklyLimitUsd(v float64) *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.AddWeeklyLimitUsd(v)
	})
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsertBulk) UpdateWeeklyLimitUsd() *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.UpdateWeeklyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsertBulk) SetMonthlyLimitUsd(v float64) *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *BundlePlanGroupQuotaUpsertBulk) AddMonthlyLimitUsd(v float64) *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *BundlePlanGroupQuotaUpsertBulk) UpdateMonthlyLimitUsd() *BundlePlanGroupQuotaUpsertBulk {
	return u.Update(func(s *BundlePlanGroupQuotaUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// Exec executes the query.
func (u *BundlePlanGroupQuotaUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BundlePlanGroupQuotaCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BundlePlanGroupQuotaCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BundlePlanGroupQuotaUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
