// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/bundlesubscriptionusage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BundleSubscriptionUsageUpdate is the builder for updating BundleSubscriptionUsage entities.
type BundleSubscriptionUsageUpdate struct {
	config
	hooks    []Hook
	mutation *BundleSubscriptionUsageMutation
}

// Where appends a list predicates to the BundleSubscriptionUsageUpdate builder.
func (_u *BundleSubscriptionUsageUpdate) Where(ps ...predicate.BundleSubscriptionUsage) *BundleSubscriptionUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBundleSubscriptionID sets the "bundle_subscription_id" field.
func (_u *BundleSubscriptionUsageUpdate) SetBundleSubscriptionID(v int64) *BundleSubscriptionUsageUpdate {
	_u.mutation.ResetBundleSubscriptionID()
	_u.mutation.SetBundleSubscriptionID(v)
	return _u
}

// SetNillableBundleSubscriptionID sets the "bundle_subscription_id" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdate) SetNillableBundleSubscriptionID(v *int64) *BundleSubscriptionUsageUpdate {
	if v != nil {
		_u.SetBundleSubscriptionID(*v)
	}
	return _u
}

// AddBundleSubscriptionID adds value to the "bundle_subscription_id" field.
func (_u *BundleSubscriptionUsageUpdate) AddBundleSubscriptionID(v int64) *BundleSubscriptionUsageUpdate {
	_u.mutation.AddBundleSubscriptionID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *BundleSubscriptionUsageUpdate) SetGroupID(v int64) *BundleSubscriptionUsageUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdate) SetNillableGroupID(v *int64) *BundleSubscriptionUsageUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *BundleSubscriptionUsageUpdate) AddGroupID(v int64) *BundleSubscriptionUsageUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetModelPattern sets the "model_pattern" field.
func (_u *BundleSubscriptionUsageUpdate) SetModelPattern(v string) *BundleSubscriptionUsageUpdate {
	_u.mutation.SetModelPattern(v)
	return _u
}

// SetNillableModelPattern sets the "model_pattern" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdate) SetNillableModelPattern(v *string) *BundleSubscriptionUsageUpdate {
	if v != nil {
		_u.SetModelPattern(*v)
	}
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *BundleSubscriptionUsageUpdate) SetDailyUsageUsd(v float64) *BundleSubscriptionUsageUpdate {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdate) SetNillableDailyUsageUsd(v *float64) *BundleSubscriptionUsageUpdate {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *BundleSubscriptionUsageUpdate) AddDailyUsageUsd(v float64) *BundleSubscriptionUsageUpdate {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_u *BundleSubscriptionUsageUpdate) SetDailyWindowStart(v time.Time) *BundleSubscriptionUsageUpdate {
	_u.mutation.SetDailyWindowStart(v)
	return _u
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdate) SetNillableDailyWindowStart(v *time.Time) *BundleSubscriptionUsageUpdate {
	if v != nil {
		_u.SetDailyWindowStart(*v)
	}
	return _u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_u *BundleSubscriptionUsageUpdate) SetWeeklyUsageUsd(v float64) *BundleSubscriptionUsageUpdate {
	_u.mutation.ResetWeeklyUsageUsd()
	_u.mutation.SetWeeklyUsageUsd(v)
	return _u
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdate) SetNillableWeeklyUsageUsd(v *float64) *BundleSubscriptionUsageUpdate {
	if v != nil {
		_u.SetWeeklyUsageUsd(*v)
	}
	return _u
}

// AddWeeklyUsageUsd adds value to the "weekly_usage_usd" field.
func (_u *BundleSubscriptionUsageUpdate) AddWeeklyUsageUsd(v float64) *BundleSubscriptionUsageUpdate {
	_u.mutation.AddWeeklyUsageUsd(v)
	return _u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_u *BundleSubscriptionUsageUpdate) SetWeeklyWindowStart(v time.Time) *BundleSubscriptionUsageUpdate {
	_u.mutation.SetWeeklyWindowStart(v)
	return _u
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdate) SetNillableWeeklyWindowStart(v *time.Time) *BundleSubscriptionUsageUpdate {
	if v != nil {
		_u.SetWeeklyWindowStart(*v)
	}
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *BundleSubscriptionUsageUpdate) SetMonthlyUsageUsd(v float64) *BundleSubscriptionUsageUpdate {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdate) SetNillableMonthlyUsageUsd(v *float64) *BundleSubscriptionUsageUpdate {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *BundleSubscriptionUsageUpdate) AddMonthlyUsageUsd(v float64) *BundleSubscriptionUsageUpdate {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *BundleSubscriptionUsageUpdate) SetMonthlyWindowStart(v time.Time) *BundleSubscriptionUsageUpdate {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdate) SetNillableMonthlyWindowStart(v *time.Time) *BundleSubscriptionUsageUpdate {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// Mutation returns the BundleSubscriptionUsageMutation object of the builder.
func (_u *BundleSubscriptionUsageUpdate) Mutation() *BundleSubscriptionUsageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BundleSubscriptionUsageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundleSubscriptionUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BundleSubscriptionUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundleSubscriptionUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BundleSubscriptionUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(bundlesubscriptionusage.Table, bundlesubscriptionusage.Columns, sqlgraph.NewFieldSpec(bundlesubscriptionusage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BundleSubscriptionID(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldBundleSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBundleSubscriptionID(); ok {
		_spec.AddField(bundlesubscriptionusage.FieldBundleSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(bundlesubscriptionusage.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ModelPattern(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldModelPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(bundlesubscriptionusage.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DailyWindowStart(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldDailyWindowStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyUsageUsd(); ok {
		_spec.AddField(bundlesubscriptionusage.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldWeeklyWindowStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(bundlesubscriptionusage.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundlesubscriptionusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BundleSubscriptionUsageUpdateOne is the builder for updating a single BundleSubscriptionUsage entity.
type BundleSubscriptionUsageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BundleSubscriptionUsageMutation
}

// SetBundleSubscriptionID sets the "bundle_subscription_id" field.
func (_u *BundleSubscriptionUsageUpdateOne) SetBundleSubscriptionID(v int64) *BundleSubscriptionUsageUpdateOne {
	_u.mutation.ResetBundleSubscriptionID()
	_u.mutation.SetBundleSubscriptionID(v)
	return _u
}

// SetNillableBundleSubscriptionID sets the "bundle_subscription_id" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdateOne) SetNillableBundleSubscriptionID(v *int64) *BundleSubscriptionUsageUpdateOne {
	if v != nil {
		_u.SetBundleSubscriptionID(*v)
	}
	return _u
}

// AddBundleSubscriptionID adds value to the "bundle_subscription_id" field.
func (_u *BundleSubscriptionUsageUpdateOne) AddBundleSubscriptionID(v int64) *BundleSubscriptionUsageUpdateOne {
	_u.mutation.AddBundleSubscriptionID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *BundleSubscriptionUsageUpdateOne) SetGroupID(v int64) *BundleSubscriptionUsageUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdateOne) SetNillableGroupID(v *int64) *BundleSubscriptionUsageUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *BundleSubscriptionUsageUpdateOne) AddGroupID(v int64) *BundleSubscriptionUsageUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetModelPattern sets the "model_pattern" field.
func (_u *BundleSubscriptionUsageUpdateOne) SetModelPattern(v string) *BundleSubscriptionUsageUpdateOne {
	_u.mutation.SetModelPattern(v)
	return _u
}

// SetNillableModelPattern sets the "model_pattern" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdateOne) SetNillableModelPattern(v *string) *BundleSubscriptionUsageUpdateOne {
	if v != nil {
		_u.SetModelPattern(*v)
	}
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *BundleSubscriptionUsageUpdateOne) SetDailyUsageUsd(v float64) *BundleSubscriptionUsageUpdateOne {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdateOne) SetNillableDailyUsageUsd(v *float64) *BundleSubscriptionUsageUpdateOne {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *BundleSubscriptionUsageUpdateOne) AddDailyUsageUsd(v float64) *BundleSubscriptionUsageUpdateOne {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_u *BundleSubscriptionUsageUpdateOne) SetDailyWindowStart(v time.Time) *BundleSubscriptionUsageUpdateOne {
	_u.mutation.SetDailyWindowStart(v)
	return _u
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdateOne) SetNillableDailyWindowStart(v *time.Time) *BundleSubscriptionUsageUpdateOne {
	if v != nil {
		_u.SetDailyWindowStart(*v)
	}
	return _u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_u *BundleSubscriptionUsageUpdateOne) SetWeeklyUsageUsd(v float64) *BundleSubscriptionUsageUpdateOne {
	_u.mutation.ResetWeeklyUsageUsd()
	_u.mutation.SetWeeklyUsageUsd(v)
	return _u
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdateOne) SetNillableWeeklyUsageUsd(v *float64) *BundleSubscriptionUsageUpdateOne {
	if v != nil {
		_u.SetWeeklyUsageUsd(*v)
	}
	return _u
}

// AddWeeklyUsageUsd adds value to the "weekly_usage_usd" field.
func (_u *BundleSubscriptionUsageUpdateOne) AddWeeklyUsageUsd(v float64) *BundleSubscriptionUsageUpdateOne {
	_u.mutation.AddWeeklyUsageUsd(v)
	return _u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_u *BundleSubscriptionUsageUpdateOne) SetWeeklyWindowStart(v time.Time) *BundleSubscriptionUsageUpdateOne {
	_u.mutation.SetWeeklyWindowStart(v)
	return _u
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdateOne) SetNillableWeeklyWindowStart(v *time.Time) *BundleSubscriptionUsageUpdateOne {
	if v != nil {
		_u.SetWeeklyWindowStart(*v)
	}
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *BundleSubscriptionUsageUpdateOne) SetMonthlyUsageUsd(v float64) *BundleSubscriptionUsageUpdateOne {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdateOne) SetNillableMonthlyUsageUsd(v *float64) *BundleSubscriptionUsageUpdateOne {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *BundleSubscriptionUsageUpdateOne) AddMonthlyUsageUsd(v float64) *BundleSubscriptionUsageUpdateOne {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *BundleSubscriptionUsageUpdateOne) SetMonthlyWindowStart(v time.Time) *BundleSubscriptionUsageUpdateOne {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *BundleSubscriptionUsageUpdateOne) SetNillableMonthlyWindowStart(v *time.Time) *BundleSubscriptionUsageUpdateOne {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// Mutation returns the BundleSubscriptionUsageMutation object of the builder.
func (_u *BundleSubscriptionUsageUpdateOne) Mutation() *BundleSubscriptionUsageMutation {
	return _u.mutation
}

// Where appends a list predicates to the BundleSubscriptionUsageUpdate builder.
func (_u *BundleSubscriptionUsageUpdateOne) Where(ps ...predicate.BundleSubscriptionUsage) *BundleSubscriptionUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BundleSubscriptionUsageUpdateOne) Select(field string, fields ...string) *BundleSubscriptionUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BundleSubscriptionUsage entity.
func (_u *BundleSubscriptionUsageUpdateOne) Save(ctx context.Context) (*BundleSubscriptionUsage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundleSubscriptionUsageUpdateOne) SaveX(ctx context.Context) *BundleSubscriptionUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BundleSubscriptionUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundleSubscriptionUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BundleSubscriptionUsageUpdateOne) sqlSave(ctx context.Context) (_node *BundleSubscriptionUsage, err error) {
	_spec := sqlgraph.NewUpdateSpec(bundlesubscriptionusage.Table, bundlesubscriptionusage.Columns, sqlgraph.NewFieldSpec(bundlesubscriptionusage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BundleSubscriptionUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bundlesubscriptionusage.FieldID)
		for _, f := range fields {
			if !bundlesubscriptionusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bundlesubscriptionusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BundleSubscriptionID(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldBundleSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBundleSubscriptionID(); ok {
		_spec.AddField(bundlesubscriptionusage.FieldBundleSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(bundlesubscriptionusage.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ModelPattern(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldModelPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(bundlesubscriptionusage.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DailyWindowStart(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldDailyWindowStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyUsageUsd(); ok {
		_spec.AddField(bundlesubscriptionusage.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldWeeklyWindowStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(bundlesubscriptionusage.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(bundlesubscriptionusage.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	_node = &BundleSubscriptionUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundlesubscriptionusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
