// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogdisplay"
)

// ModelCatalogDisplayCreate is the builder for creating a ModelCatalogDisplay entity.
type ModelCatalogDisplayCreate struct {
	config
	mutation *ModelCatalogDisplayMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPlatform sets the "platform" field.
func (_c *ModelCatalogDisplayCreate) SetPlatform(v string) *ModelCatalogDisplayCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetModelName sets the "model_name" field.
func (_c *ModelCatalogDisplayCreate) SetModelName(v string) *ModelCatalogDisplayCreate {
	_c.mutation.SetModelName(v)
	return _c
}

// SetPinned sets the "pinned" field.
func (_c *ModelCatalogDisplayCreate) SetPinned(v bool) *ModelCatalogDisplayCreate {
	_c.mutation.SetPinned(v)
	return _c
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_c *ModelCatalogDisplayCreate) SetNillablePinned(v *bool) *ModelCatalogDisplayCreate {
	if v != nil {
		_c.SetPinned(*v)
	}
	return _c
}

// SetSortWeight sets the "sort_weight" field.
func (_c *ModelCatalogDisplayCreate) SetSortWeight(v int) *ModelCatalogDisplayCreate {
	_c.mutation.SetSortWeight(v)
	return _c
}

// SetNillableSortWeight sets the "sort_weight" field if the given value is not nil.
func (_c *ModelCatalogDisplayCreate) SetNillableSortWeight(v *int) *ModelCatalogDisplayCreate {
	if v != nil {
		_c.SetSortWeight(*v)
	}
	return _c
}

// SetCustomTags sets the "custom_tags" field.
func (_c *ModelCatalogDisplayCreate) SetCustomTags(v []string) *ModelCatalogDisplayCreate {
	_c.mutation.SetCustomTags(v)
	return _c
}

// SetFeaturedUntil sets the "featured_until" field.
func (_c *ModelCatalogDisplayCreate) SetFeaturedUntil(v time.Time) *ModelCatalogDisplayCreate {
	_c.mutation.SetFeaturedUntil(v)
	return _c
}

// SetNillableFeaturedUntil sets the "featured_until" field if the given value is not nil.
func (_c *ModelCatalogDisplayCreate) SetNillableFeaturedUntil(v *time.Time) *ModelCatalogDisplayCreate {
	if v != nil {
		_c.SetFeaturedUntil(*v)
	}
	return _c
}

// SetHidden sets the "hidden" field.
func (_c *ModelCatalogDisplayCreate) SetHidden(v bool) *ModelCatalogDisplayCreate {
	_c.mutation.SetHidden(v)
	return _c
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (_c *ModelCatalogDisplayCreate) SetNillableHidden(v *bool) *ModelCatalogDisplayCreate {
	if v != nil {
		_c.SetHidden(*v)
	}
	return _c
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_c *ModelCatalogDisplayCreate) SetFirstSeenAt(v time.Time) *ModelCatalogDisplayCreate {
	_c.mutation.SetFirstSeenAt(v)
	return _c
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_c *ModelCatalogDisplayCreate) SetNillableFirstSeenAt(v *time.Time) *ModelCatalogDisplayCreate {
	if v != nil {
		_c.SetFirstSeenAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelCatalogDisplayCreate) SetCreatedAt(v time.Time) *ModelCatalogDisplayCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelCatalogDisplayCreate) SetNillableCreatedAt(v *time.Time) *ModelCatalogDisplayCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelCatalogDisplayCreate) SetUpdatedAt(v time.Time) *ModelCatalogDisplayCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelCatalogDisplayCreate) SetNillableUpdatedAt(v *time.Time) *ModelCatalogDisplayCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ModelCatalogDisplayMutation object of the builder.
func (_c *ModelCatalogDisplayCreate) Mutation() *ModelCatalogDisplayMutation {
	return _c.mutation
}

// Save creates the ModelCatalogDisplay in the database.
func (_c *ModelCatalogDisplayCreate) Save(ctx context.Context) (*ModelCatalogDisplay, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelCatalogDisplayCreate) SaveX(ctx context.Context) *ModelCatalogDisplay {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCatalogDisplayCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCatalogDisplayCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelCatalogDisplayCreate) defaults() {
	if _, ok := _c.mutation.Pinned(); !ok {
		v := modelcatalogdisplay.DefaultPinned
		_c.mutation.SetPinned(v)
	}
	if _, ok := _c.mutation.SortWeight(); !ok {
		v := modelcatalogdisplay.DefaultSortWeight
		_c.mutation.SetSortWeight(v)
	}
	if _, ok := _c.mutation.CustomTags(); !ok {
		v := modelcatalogdisplay.DefaultCustomTags
		_c.mutation.SetCustomTags(v)
	}
	if _, ok := _c.mutation.Hidden(); !ok {
		v := modelcatalogdisplay.DefaultHidden
		_c.mutation.SetHidden(v)
	}
	if _, ok := _c.mutation.FirstSeenAt(); !ok {
		v := modelcatalogdisplay.DefaultFirstSeenAt()
		_c.mutation.SetFirstSeenAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelcatalogdisplay.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelcatalogdisplay.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelCatalogDisplayCreate) check() error {
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "ModelCatalogDisplay.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := modelcatalogdisplay.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogDisplay.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelName(); !ok {
		return &ValidationError{Name: "model_name", err: errors.New(`ent: missing required field "ModelCatalogDisplay.model_name"`)}
	}
	if v, ok := _c.mutation.ModelName(); ok {
		if err := modelcatalogdisplay.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogDisplay.model_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Pinned(); !ok {
		return &ValidationError{Name: "pinned", err: errors.New(`ent: missing required field "ModelCatalogDisplay.pinned"`)}
	}
	if _, ok := _c.mutation.SortWeight(); !ok {
		return &ValidationError{Name: "sort_weight", err: errors.New(`ent: missing required field "ModelCatalogDisplay.sort_weight"`)}
	}
	if _, ok := _c.mutation.CustomTags(); !ok {
		return &ValidationError{Name: "custom_tags", err: errors.New(`ent: missing required field "ModelCatalogDisplay.custom_tags"`)}
	}
	if _, ok := _c.mutation.Hidden(); !ok {
		return &ValidationError{Name: "hidden", err: errors.New(`ent: missing required field "ModelCatalogDisplay.hidden"`)}
	}
	if _, ok := _c.mutation.FirstSeenAt(); !ok {
		return &ValidationError{Name: "first_seen_at", err: errors.New(`ent: missing required field "ModelCatalogDisplay.first_seen_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelCatalogDisplay.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelCatalogDisplay.updated_at"`)}
	}
	return nil
}

func (_c *ModelCatalogDisplayCreate) sqlSave(ctx context.Context) (*ModelCatalogDisplay, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelCatalogDisplayCreate) createSpec() (*ModelCatalogDisplay, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelCatalogDisplay{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelcatalogdisplay.Table, sqlgraph.NewFieldSpec(modelcatalogdisplay.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(modelcatalogdisplay.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.ModelName(); ok {
		_spec.SetField(modelcatalogdisplay.FieldModelName, field.TypeString, value)
		_node.ModelName = value
	}
	if value, ok := _c.mutation.Pinned(); ok {
		_spec.SetField(modelcatalogdisplay.FieldPinned, field.TypeBool, value)
		_node.Pinned = value
	}
	if value, ok := _c.mutation.SortWeight(); ok {
		_spec.SetField(modelcatalogdisplay.FieldSortWeight, field.TypeInt, value)
		_node.SortWeight = value
	}
	if value, ok := _c.mutation.CustomTags(); ok {
		_spec.SetField(modelcatalogdisplay.FieldCustomTags, field.TypeJSON, value)
		_node.CustomTags = value
	}
	if value, ok := _c.mutation.FeaturedUntil(); ok {
		_spec.SetField(modelcatalogdisplay.FieldFeaturedUntil, field.TypeTime, value)
		_node.FeaturedUntil = &value
	}
	if value, ok := _c.mutation.Hidden(); ok {
		_spec.SetField(modelcatalogdisplay.FieldHidden, field.TypeBool, value)
		_node.Hidden = value
	}
	if value, ok := _c.mutation.FirstSeenAt(); ok {
		_spec.SetField(modelcatalogdisplay.FieldFirstSeenAt, field.TypeTime, value)
		_node.FirstSeenAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelcatalogdisplay.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalogdisplay.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelCatalogDisplay.Create().
//		SetPlatform(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelCatalogDisplayUpsert) {
//			SetPlatform(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelCatalogDisplayCreate) OnConflict(opts ...sql.ConflictOption) *ModelCatalogDisplayUpsertOne {
	_c.conflict = opts
	return &ModelCatalogDisplayUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelCatalogDisplay.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelCatalogDisplayCreate) OnConflictColumns(columns ...string) *ModelCatalogDisplayUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelCatalogDisplayUpsertOne{
		create: _c,
	}
}

type (
	// ModelCatalogDisplayUpsertOne is the builder for "upsert"-ing
	//  one ModelCatalogDisplay node.
	ModelCatalogDisplayUpsertOne struct {
		create *ModelCatalogDisplayCreate
	}

	// ModelCatalogDisplayUpsert is the "OnConflict" setter.
	ModelCatalogDisplayUpsert struct {
		*sql.UpdateSet
	}
)

// SetPlatform sets the "platform" field.
func (u *ModelCatalogDisplayUpsert) SetPlatform(v string) *ModelCatalogDisplayUpsert {
	u.Set(modelcatalogdisplay.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsert) UpdatePlatform() *ModelCatalogDisplayUpsert {
	u.SetExcluded(modelcatalogdisplay.FieldPlatform)
	return u
}

// SetModelName sets the "model_name" field.
func (u *ModelCatalogDisplayUpsert) SetModelName(v string) *ModelCatalogDisplayUpsert {
	u.Set(modelcatalogdisplay.FieldModelName, v)
	return u
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsert) UpdateModelName() *ModelCatalogDisplayUpsert {
	u.SetExcluded(modelcatalogdisplay.FieldModelName)
	return u
}

// SetPinned sets the "pinned" field.
func (u *ModelCatalogDisplayUpsert) SetPinned(v bool) *ModelCatalogDisplayUpsert {
	u.Set(modelcatalogdisplay.FieldPinned, v)
	return u
}

// UpdatePinned sets the "pinned" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsert) UpdatePinned() *ModelCatalogDisplayUpsert {
	u.SetExcluded(modelcatalogdisplay.FieldPinned)
	return u
}

// SetSortWeight sets the "sort_weight" field.
func (u *ModelCatalogDisplayUpsert) SetSortWeight(v int) *ModelCatalogDisplayUpsert {
	u.Set(modelcatalogdisplay.FieldSortWeight, v)
	return u
}

// UpdateSortWeight sets the "sort_weight" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsert) UpdateSortWeight() *ModelCatalogDisplayUpsert {
	u.SetExcluded(modelcatalogdisplay.FieldSortWeight)
	return u
}

// AddSortWeight adds v to the "sort_weight" field.
func (u *ModelCatalogDisplayUpsert) AddSortWeight(v int) *ModelCatalogDisplayUpsert {
	u.Add(modelcatalogdisplay.FieldSortWeight, v)
	return u
}

// SetCustomTags sets the "custom_tags" field.
func (u *ModelCatalogDisplayUpsert) SetCustomTags(v []string) *ModelCatalogDisplayUpsert {
	u.Set(modelcatalogdisplay.FieldCustomTags, v)
	return u
}

// UpdateCustomTags sets the "custom_tags" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsert) UpdateCustomTags() *ModelCatalogDisplayUpsert {
	u.SetExcluded(modelcatalogdisplay.FieldCustomTags)
	return u
}

// SetFeaturedUntil sets the "featured_until" field.
func (u *ModelCatalogDisplayUpsert) SetFeaturedUntil(v time.Time) *ModelCatalogDisplayUpsert {
	u.Set(modelcatalogdisplay.FieldFeaturedUntil, v)
	return u
}

// UpdateFeaturedUntil sets the "featured_until" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsert) UpdateFeaturedUntil() *ModelCatalogDisplayUpsert {
	u.SetExcluded(modelcatalogdisplay.FieldFeaturedUntil)
	return u
}

// ClearFeaturedUntil clears the value of the "featured_until" field.
func (u *ModelCatalogDisplayUpsert) ClearFeaturedUntil() *ModelCatalogDisplayUpsert {
	u.SetNull(modelcatalogdisplay.FieldFeaturedUntil)
	return u
}

// SetHidden sets the "hidden" field.
func (u *ModelCatalogDisplayUpsert) SetHidden(v bool) *ModelCatalogDisplayUpsert {
	u.Set(modelcatalogdisplay.FieldHidden, v)
	return u
}

// UpdateHidden sets the "hidden" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsert) UpdateHidden() *ModelCatalogDisplayUpsert {
	u.SetExcluded(modelcatalogdisplay.FieldHidden)
	return u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (u *ModelCatalogDisplayUpsert) SetFirstSeenAt(v time.Time) *ModelCatalogDisplayUpsert {
	u.Set(modelcatalogdisplay.FieldFirstSeenAt, v)
	return u
}

// UpdateFirstSeenAt sets the "first_seen_at" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsert) UpdateFirstSeenAt() *ModelCatalogDisplayUpsert {
	u.SetExcluded(modelcatalogdisplay.FieldFirstSeenAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCatalogDisplayUpsert) SetUpdatedAt(v time.Time) *ModelCatalogDisplayUpsert {
	u.Set(modelcatalogdisplay.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsert) UpdateUpdatedAt() *ModelCatalogDisplayUpsert {
	u.SetExcluded(modelcatalogdisplay.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelCatalogDisplay.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelCatalogDisplayUpsertOne) UpdateNewValues() *ModelCatalogDisplayUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelcatalogdisplay.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelCatalogDisplay.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelCatalogDisplayUpsertOne) Ignore() *ModelCatalogDisplayUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelCatalogDisplayUpsertOne) DoNothing() *ModelCatalogDisplayUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelCatalogDisplayCreate.OnConflict
// documentation for more info.
func (u *ModelCatalogDisplayUpsertOne) Update(set func(*ModelCatalogDisplayUpsert)) *ModelCatalogDisplayUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelCatalogDisplayUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlatform sets the "platform" field.
func (u *ModelCatalogDisplayUpsertOne) SetPlatform(v string) *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertOne) UpdatePlatform() *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdatePlatform()
	})
}

// SetModelName sets the "model_name" field.
func (u *ModelCatalogDisplayUpsertOne) SetModelName(v string) *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertOne) UpdateModelName() *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdateModelName()
	})
}

// SetPinned sets the "pinned" field.
func (u *ModelCatalogDisplayUpsertOne) SetPinned(v bool) *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetPinned(v)
	})
}

// UpdatePinned sets the "pinned" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertOne) UpdatePinned() *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdatePinned()
	})
}

// SetSortWeight sets the "sort_weight" field.
func (u *ModelCatalogDisplayUpsertOne) SetSortWeight(v int) *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetSortWeight(v)
	})
}

// AddSortWeight adds v to the "sort_weight" field.
func (u *ModelCatalogDisplayUpsertOne) AddSortWeight(v int) *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.AddSortWeight(v)
	})
}

// UpdateSortWeight sets the "sort_weight" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertOne) UpdateSortWeight() *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdateSortWeight()
	})
}

// SetCustomTags sets the "custom_tags" field.
func (u *ModelCatalogDisplayUpsertOne) SetCustomTags(v []string) *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetCustomTags(v)
	})
}

// UpdateCustomTags sets the "custom_tags" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertOne) UpdateCustomTags() *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdateCustomTags()
	})
}

// SetFeaturedUntil sets the "featured_until" field.
func (u *ModelCatalogDisplayUpsertOne) SetFeaturedUntil(v time.Time) *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetFeaturedUntil(v)
	})
}

// UpdateFeaturedUntil sets the "featured_until" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertOne) UpdateFeaturedUntil() *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdateFeaturedUntil()
	})
}

// ClearFeaturedUntil clears the value of the "featured_until" field.
func (u *ModelCatalogDisplayUpsertOne) ClearFeaturedUntil() *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.ClearFeaturedUntil()
	})
}

// SetHidden sets the "hidden" field.
func (u *ModelCatalogDisplayUpsertOne) SetHidden(v bool) *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetHidden(v)
	})
}

// UpdateHidden sets the "hidden" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertOne) UpdateHidden() *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdateHidden()
	})
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (u *ModelCatalogDisplayUpsertOne) SetFirstSeenAt(v time.Time) *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetFirstSeenAt(v)
	})
}

// UpdateFirstSeenAt sets the "first_seen_at" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertOne) UpdateFirstSeenAt() *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdateFirstSeenAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCatalogDisplayUpsertOne) SetUpdatedAt(v time.Time) *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertOne) UpdateUpdatedAt() *ModelCatalogDisplayUpsertOne {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ModelCatalogDisplayUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelCatalogDisplayCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelCatalogDisplayUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelCatalogDisplayUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelCatalogDisplayUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelCatalogDisplayCreateBulk is the builder for creating many ModelCatalogDisplay entities in bulk.
type ModelCatalogDisplayCreateBulk struct {
	config
	err      error
	builders []*ModelCatalogDisplayCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelCatalogDisplay entities in the database.
func (_c *ModelCatalogDisplayCreateBulk) Save(ctx context.Context) ([]*ModelCatalogDisplay, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelCatalogDisplay, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelCatalogDisplayMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelCatalogDisplayCreateBulk) SaveX(ctx context.Context) []*ModelCatalogDisplay {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCatalogDisplayCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCatalogDisplayCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelCatalogDisplay.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelCatalogDisplayUpsert) {
//			SetPlatform(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelCatalogDisplayCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelCatalogDisplayUpsertBulk {
	_c.conflict = opts
	return &ModelCatalogDisplayUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelCatalogDisplay.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelCatalogDisplayCreateBulk) OnConflictColumns(columns ...string) *ModelCatalogDisplayUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelCatalogDisplayUpsertBulk{
		create: _c,
	}
}

// ModelCatalogDisplayUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelCatalogDisplay nodes.
type ModelCatalogDisplayUpsertBulk struct {
	create *ModelCatalogDisplayCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelCatalogDisplay.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelCatalogDisplayUpsertBulk) UpdateNewValues() *ModelCatalogDisplayUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelcatalogdisplay.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelCatalogDisplay.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelCatalogDisplayUpsertBulk) Ignore() *ModelCatalogDisplayUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelCatalogDisplayUpsertBulk) DoNothing() *ModelCatalogDisplayUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelCatalogDisplayCreateBulk.OnConflict
// documentation for more info.
func (u *ModelCatalogDisplayUpsertBulk) Update(set func(*ModelCatalogDisplayUpsert)) *ModelCatalogDisplayUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelCatalogDisplayUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlatform sets the "platform" field.
func (u *ModelCatalogDisplayUpsertBulk) SetPlatform(v string) *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertBulk) UpdatePlatform() *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdatePlatform()
	})
}

// SetModelName sets the "model_name" field.
func (u *ModelCatalogDisplayUpsertBulk) SetModelName(v string) *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertBulk) UpdateModelName() *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdateModelName()
	})
}

// SetPinned sets the "pinned" field.
func (u *ModelCatalogDisplayUpsertBulk) SetPinned(v bool) *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetPinned(v)
	})
}

// UpdatePinned sets the "pinned" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertBulk) UpdatePinned() *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdatePinned()
	})
}

// SetSortWeight sets the "sort_weight" field.
func (u *ModelCatalogDisplayUpsertBulk) SetSortWeight(v int) *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetSortWeight(v)
	})
}

// AddSortWeight adds v to the "sort_weight" field.
func (u *ModelCatalogDisplayUpsertBulk) AddSortWeight(v int) *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.AddSortWeight(v)
	})
}

// UpdateSortWeight sets the "sort_weight" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertBulk) UpdateSortWeight() *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdateSortWeight()
	})
}

// SetCustomTags sets the "custom_tags" field.
func (u *ModelCatalogDisplayUpsertBulk) SetCustomTags(v []string) *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetCustomTags(v)
	})
}

// UpdateCustomTags sets the "custom_tags" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertBulk) UpdateCustomTags() *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdateCustomTags()
	})
}

// SetFeaturedUntil sets the "featured_until" field.
func (u *ModelCatalogDisplayUpsertBulk) SetFeaturedUntil(v time.Time) *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetFeaturedUntil(v)
	})
}

// UpdateFeaturedUntil sets the "featured_until" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertBulk) UpdateFeaturedUntil() *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdateFeaturedUntil()
	})
}

// ClearFeaturedUntil clears the value of the "featured_until" field.
func (u *ModelCatalogDisplayUpsertBulk) ClearFeaturedUntil() *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.ClearFeaturedUntil()
	})
}

// SetHidden sets the "hidden" field.
func (u *ModelCatalogDisplayUpsertBulk) SetHidden(v bool) *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetHidden(v)
	})
}

// UpdateHidden sets the "hidden" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertBulk) UpdateHidden() *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdateHidden()
	})
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (u *ModelCatalogDisplayUpsertBulk) SetFirstSeenAt(v time.Time) *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetFirstSeenAt(v)
	})
}

// UpdateFirstSeenAt sets the "first_seen_at" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertBulk) UpdateFirstSeenAt() *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdateFirstSeenAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCatalogDisplayUpsertBulk) SetUpdatedAt(v time.Time) *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCatalogDisplayUpsertBulk) UpdateUpdatedAt() *ModelCatalogDisplayUpsertBulk {
	return u.Update(func(s *ModelCatalogDisplayUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ModelCatalogDisplayUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelCatalogDisplayCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelCatalogDisplayCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelCatalogDisplayUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
