// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogdisplay"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelCatalogDisplayUpdate is the builder for updating ModelCatalogDisplay entities.
type ModelCatalogDisplayUpdate struct {
	config
	hooks    []Hook
	mutation *ModelCatalogDisplayMutation
}

// Where appends a list predicates to the ModelCatalogDisplayUpdate builder.
func (_u *ModelCatalogDisplayUpdate) Where(ps ...predicate.ModelCatalogDisplay) *ModelCatalogDisplayUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ModelCatalogDisplayUpdate) SetPlatform(v string) *ModelCatalogDisplayUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdate) SetNillablePlatform(v *string) *ModelCatalogDisplayUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *ModelCatalogDisplayUpdate) SetModelName(v string) *ModelCatalogDisplayUpdate {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdate) SetNillableModelName(v *string) *ModelCatalogDisplayUpdate {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetPinned sets the "pinned" field.
func (_u *ModelCatalogDisplayUpdate) SetPinned(v bool) *ModelCatalogDisplayUpdate {
	_u.mutation.SetPinned(v)
	return _u
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdate) SetNillablePinned(v *bool) *ModelCatalogDisplayUpdate {
	if v != nil {
		_u.SetPinned(*v)
	}
	return _u
}

// SetSortWeight sets the "sort_weight" field.
func (_u *ModelCatalogDisplayUpdate) SetSortWeight(v int) *ModelCatalogDisplayUpdate {
	_u.mutation.ResetSortWeight()
	_u.mutation.SetSortWeight(v)
	return _u
}

// SetNillableSortWeight sets the "sort_weight" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdate) SetNillableSortWeight(v *int) *ModelCatalogDisplayUpdate {
	if v != nil {
		_u.SetSortWeight(*v)
	}
	return _u
}

// AddSortWeight adds value to the "sort_weight" field.
func (_u *ModelCatalogDisplayUpdate) AddSortWeight(v int) *ModelCatalogDisplayUpdate {
	_u.mutation.AddSortWeight(v)
	return _u
}

// SetCustomTags sets the "custom_tags" field.
func (_u *ModelCatalogDisplayUpdate) SetCustomTags(v []string) *ModelCatalogDisplayUpdate {
	_u.mutation.SetCustomTags(v)
	return _u
}

// AppendCustomTags appends value to the "custom_tags" field.
func (_u *ModelCatalogDisplayUpdate) AppendCustomTags(v []string) *ModelCatalogDisplayUpdate {
	_u.mutation.AppendCustomTags(v)
	return _u
}

// SetFeaturedUntil sets the "featured_until" field.
func (_u *ModelCatalogDisplayUpdate) SetFeaturedUntil(v time.Time) *ModelCatalogDisplayUpdate {
	_u.mutation.SetFeaturedUntil(v)
	return _u
}

// SetNillableFeaturedUntil sets the "featured_until" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdate) SetNillableFeaturedUntil(v *time.Time) *ModelCatalogDisplayUpdate {
	if v != nil {
		_u.SetFeaturedUntil(*v)
	}
	return _u
}

// ClearFeaturedUntil clears the value of the "featured_until" field.
func (_u *ModelCatalogDisplayUpdate) ClearFeaturedUntil() *ModelCatalogDisplayUpdate {
	_u.mutation.ClearFeaturedUntil()
	return _u
}

// SetHidden sets the "hidden" field.
func (_u *ModelCatalogDisplayUpdate) SetHidden(v bool) *ModelCatalogDisplayUpdate {
	_u.mutation.SetHidden(v)
	return _u
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdate) SetNillableHidden(v *bool) *ModelCatalogDisplayUpdate {
	if v != nil {
		_u.SetHidden(*v)
	}
	return _u
}

// SetIsNew sets the "is_new" field.
func (_u *ModelCatalogDisplayUpdate) SetIsNew(v bool) *ModelCatalogDisplayUpdate {
	_u.mutation.SetIsNew(v)
	return _u
}

// SetNillableIsNew sets the "is_new" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdate) SetNillableIsNew(v *bool) *ModelCatalogDisplayUpdate {
	if v != nil {
		_u.SetIsNew(*v)
	}
	return _u
}

// SetFeatured sets the "featured" field.
func (_u *ModelCatalogDisplayUpdate) SetFeatured(v bool) *ModelCatalogDisplayUpdate {
	_u.mutation.SetFeatured(v)
	return _u
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdate) SetNillableFeatured(v *bool) *ModelCatalogDisplayUpdate {
	if v != nil {
		_u.SetFeatured(*v)
	}
	return _u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_u *ModelCatalogDisplayUpdate) SetFirstSeenAt(v time.Time) *ModelCatalogDisplayUpdate {
	_u.mutation.SetFirstSeenAt(v)
	return _u
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdate) SetNillableFirstSeenAt(v *time.Time) *ModelCatalogDisplayUpdate {
	if v != nil {
		_u.SetFirstSeenAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCatalogDisplayUpdate) SetUpdatedAt(v time.Time) *ModelCatalogDisplayUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ModelCatalogDisplayMutation object of the builder.
func (_u *ModelCatalogDisplayUpdate) Mutation() *ModelCatalogDisplayMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelCatalogDisplayUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCatalogDisplayUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelCatalogDisplayUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCatalogDisplayUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCatalogDisplayUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcatalogdisplay.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCatalogDisplayUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := modelcatalogdisplay.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogDisplay.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelName(); ok {
		if err := modelcatalogdisplay.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogDisplay.model_name": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelCatalogDisplayUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcatalogdisplay.Table, modelcatalogdisplay.Columns, sqlgraph.NewFieldSpec(modelcatalogdisplay.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(modelcatalogdisplay.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(modelcatalogdisplay.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pinned(); ok {
		_spec.SetField(modelcatalogdisplay.FieldPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortWeight(); ok {
		_spec.SetField(modelcatalogdisplay.FieldSortWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortWeight(); ok {
		_spec.AddField(modelcatalogdisplay.FieldSortWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CustomTags(); ok {
		_spec.SetField(modelcatalogdisplay.FieldCustomTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCustomTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalogdisplay.FieldCustomTags, value)
		})
	}
	if value, ok := _u.mutation.FeaturedUntil(); ok {
		_spec.SetField(modelcatalogdisplay.FieldFeaturedUntil, field.TypeTime, value)
	}
	if _u.mutation.FeaturedUntilCleared() {
		_spec.ClearField(modelcatalogdisplay.FieldFeaturedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.Hidden(); ok {
		_spec.SetField(modelcatalogdisplay.FieldHidden, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsNew(); ok {
		_spec.SetField(modelcatalogdisplay.FieldIsNew, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Featured(); ok {
		_spec.SetField(modelcatalogdisplay.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FirstSeenAt(); ok {
		_spec.SetField(modelcatalogdisplay.FieldFirstSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalogdisplay.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcatalogdisplay.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelCatalogDisplayUpdateOne is the builder for updating a single ModelCatalogDisplay entity.
type ModelCatalogDisplayUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelCatalogDisplayMutation
}

// SetPlatform sets the "platform" field.
func (_u *ModelCatalogDisplayUpdateOne) SetPlatform(v string) *ModelCatalogDisplayUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdateOne) SetNillablePlatform(v *string) *ModelCatalogDisplayUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *ModelCatalogDisplayUpdateOne) SetModelName(v string) *ModelCatalogDisplayUpdateOne {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdateOne) SetNillableModelName(v *string) *ModelCatalogDisplayUpdateOne {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetPinned sets the "pinned" field.
func (_u *ModelCatalogDisplayUpdateOne) SetPinned(v bool) *ModelCatalogDisplayUpdateOne {
	_u.mutation.SetPinned(v)
	return _u
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdateOne) SetNillablePinned(v *bool) *ModelCatalogDisplayUpdateOne {
	if v != nil {
		_u.SetPinned(*v)
	}
	return _u
}

// SetSortWeight sets the "sort_weight" field.
func (_u *ModelCatalogDisplayUpdateOne) SetSortWeight(v int) *ModelCatalogDisplayUpdateOne {
	_u.mutation.ResetSortWeight()
	_u.mutation.SetSortWeight(v)
	return _u
}

// SetNillableSortWeight sets the "sort_weight" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdateOne) SetNillableSortWeight(v *int) *ModelCatalogDisplayUpdateOne {
	if v != nil {
		_u.SetSortWeight(*v)
	}
	return _u
}

// AddSortWeight adds value to the "sort_weight" field.
func (_u *ModelCatalogDisplayUpdateOne) AddSortWeight(v int) *ModelCatalogDisplayUpdateOne {
	_u.mutation.AddSortWeight(v)
	return _u
}

// SetCustomTags sets the "custom_tags" field.
func (_u *ModelCatalogDisplayUpdateOne) SetCustomTags(v []string) *ModelCatalogDisplayUpdateOne {
	_u.mutation.SetCustomTags(v)
	return _u
}

// AppendCustomTags appends value to the "custom_tags" field.
func (_u *ModelCatalogDisplayUpdateOne) AppendCustomTags(v []string) *ModelCatalogDisplayUpdateOne {
	_u.mutation.AppendCustomTags(v)
	return _u
}

// SetFeaturedUntil sets the "featured_until" field.
func (_u *ModelCatalogDisplayUpdateOne) SetFeaturedUntil(v time.Time) *ModelCatalogDisplayUpdateOne {
	_u.mutation.SetFeaturedUntil(v)
	return _u
}

// SetNillableFeaturedUntil sets the "featured_until" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdateOne) SetNillableFeaturedUntil(v *time.Time) *ModelCatalogDisplayUpdateOne {
	if v != nil {
		_u.SetFeaturedUntil(*v)
	}
	return _u
}

// ClearFeaturedUntil clears the value of the "featured_until" field.
func (_u *ModelCatalogDisplayUpdateOne) ClearFeaturedUntil() *ModelCatalogDisplayUpdateOne {
	_u.mutation.ClearFeaturedUntil()
	return _u
}

// SetHidden sets the "hidden" field.
func (_u *ModelCatalogDisplayUpdateOne) SetHidden(v bool) *ModelCatalogDisplayUpdateOne {
	_u.mutation.SetHidden(v)
	return _u
}

// SetNillableHidden sets the "hidden" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdateOne) SetNillableHidden(v *bool) *ModelCatalogDisplayUpdateOne {
	if v != nil {
		_u.SetHidden(*v)
	}
	return _u
}

// SetIsNew sets the "is_new" field.
func (_u *ModelCatalogDisplayUpdateOne) SetIsNew(v bool) *ModelCatalogDisplayUpdateOne {
	_u.mutation.SetIsNew(v)
	return _u
}

// SetNillableIsNew sets the "is_new" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdateOne) SetNillableIsNew(v *bool) *ModelCatalogDisplayUpdateOne {
	if v != nil {
		_u.SetIsNew(*v)
	}
	return _u
}

// SetFeatured sets the "featured" field.
func (_u *ModelCatalogDisplayUpdateOne) SetFeatured(v bool) *ModelCatalogDisplayUpdateOne {
	_u.mutation.SetFeatured(v)
	return _u
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdateOne) SetNillableFeatured(v *bool) *ModelCatalogDisplayUpdateOne {
	if v != nil {
		_u.SetFeatured(*v)
	}
	return _u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_u *ModelCatalogDisplayUpdateOne) SetFirstSeenAt(v time.Time) *ModelCatalogDisplayUpdateOne {
	_u.mutation.SetFirstSeenAt(v)
	return _u
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_u *ModelCatalogDisplayUpdateOne) SetNillableFirstSeenAt(v *time.Time) *ModelCatalogDisplayUpdateOne {
	if v != nil {
		_u.SetFirstSeenAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCatalogDisplayUpdateOne) SetUpdatedAt(v time.Time) *ModelCatalogDisplayUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ModelCatalogDisplayMutation object of the builder.
func (_u *ModelCatalogDisplayUpdateOne) Mutation() *ModelCatalogDisplayMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelCatalogDisplayUpdate builder.
func (_u *ModelCatalogDisplayUpdateOne) Where(ps ...predicate.ModelCatalogDisplay) *ModelCatalogDisplayUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelCatalogDisplayUpdateOne) Select(field string, fields ...string) *ModelCatalogDisplayUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelCatalogDisplay entity.
func (_u *ModelCatalogDisplayUpdateOne) Save(ctx context.Context) (*ModelCatalogDisplay, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCatalogDisplayUpdateOne) SaveX(ctx context.Context) *ModelCatalogDisplay {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelCatalogDisplayUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCatalogDisplayUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCatalogDisplayUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcatalogdisplay.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCatalogDisplayUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := modelcatalogdisplay.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogDisplay.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelName(); ok {
		if err := modelcatalogdisplay.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogDisplay.model_name": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelCatalogDisplayUpdateOne) sqlSave(ctx context.Context) (_node *ModelCatalogDisplay, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcatalogdisplay.Table, modelcatalogdisplay.Columns, sqlgraph.NewFieldSpec(modelcatalogdisplay.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelCatalogDisplay.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelcatalogdisplay.FieldID)
		for _, f := range fields {
			if !modelcatalogdisplay.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelcatalogdisplay.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(modelcatalogdisplay.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(modelcatalogdisplay.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pinned(); ok {
		_spec.SetField(modelcatalogdisplay.FieldPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortWeight(); ok {
		_spec.SetField(modelcatalogdisplay.FieldSortWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortWeight(); ok {
		_spec.AddField(modelcatalogdisplay.FieldSortWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CustomTags(); ok {
		_spec.SetField(modelcatalogdisplay.FieldCustomTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCustomTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalogdisplay.FieldCustomTags, value)
		})
	}
	if value, ok := _u.mutation.FeaturedUntil(); ok {
		_spec.SetField(modelcatalogdisplay.FieldFeaturedUntil, field.TypeTime, value)
	}
	if _u.mutation.FeaturedUntilCleared() {
		_spec.ClearField(modelcatalogdisplay.FieldFeaturedUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.Hidden(); ok {
		_spec.SetField(modelcatalogdisplay.FieldHidden, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsNew(); ok {
		_spec.SetField(modelcatalogdisplay.FieldIsNew, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Featured(); ok {
		_spec.SetField(modelcatalogdisplay.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FirstSeenAt(); ok {
		_spec.SetField(modelcatalogdisplay.FieldFirstSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalogdisplay.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ModelCatalogDisplay{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcatalogdisplay.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
