// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreampricesource"
)

// UpstreamPriceSource is the model entity for the UpstreamPriceSource schema.
type UpstreamPriceSource struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 来源名称
	Name string `json:"name,omitempty"`
	// 上游基础地址，如 https://api.example.com
	BaseURL string `json:"base_url,omitempty"`
	// 价格接口路径
	PricingEndpoint string `json:"pricing_endpoint,omitempty"`
	// AES-256-GCM 加密后的上游 API Key（service 层加解密）
	APIKey string `json:"-"`
	// 解析器类型: one_api / new_api / custom
	ParserType string `json:"parser_type,omitempty"`
	// 解析器配置（JSON）
	ParserConfig map[string]interface{} `json:"parser_config,omitempty"`
	// 上游模型名 → 本地模型名 映射
	ModelAliasMap map[string]string `json:"model_alias_map,omitempty"`
	// 同步间隔（分钟）
	SyncIntervalMinutes int `json:"sync_interval_minutes,omitempty"`
	// 价格变动告警阈值（百分比，0=不告警）
	AlertThresholdPct float64 `json:"alert_threshold_pct,omitempty"`
	// 告警冷却时间（分钟）
	CooldownMinutes int `json:"cooldown_minutes,omitempty"`
	// 是否启用
	Enabled bool `json:"enabled,omitempty"`
	// 上次同步时间
	LastSyncAt *time.Time `json:"last_sync_at,omitempty"`
	// 上次同步状态: success / failed / partial
	LastSyncStatus string `json:"last_sync_status,omitempty"`
	// 上次同步错误信息
	LastSyncError string `json:"last_sync_error,omitempty"`
	// 上次同步内容的哈希值（用于变更检测）
	LastHash string `json:"last_hash,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UpstreamPriceSourceQuery when eager-loading is set.
	Edges        UpstreamPriceSourceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UpstreamPriceSourceEdges holds the relations/edges for other nodes in the graph.
type UpstreamPriceSourceEdges struct {
	// Prices holds the value of the prices edge.
	Prices []*UpstreamModelPrice `json:"prices,omitempty"`
	// Changes holds the value of the changes edge.
	Changes []*UpstreamPriceChange `json:"changes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PricesOrErr returns the Prices value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamPriceSourceEdges) PricesOrErr() ([]*UpstreamModelPrice, error) {
	if e.loadedTypes[0] {
		return e.Prices, nil
	}
	return nil, &NotLoadedError{edge: "prices"}
}

// ChangesOrErr returns the Changes value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamPriceSourceEdges) ChangesOrErr() ([]*UpstreamPriceChange, error) {
	if e.loadedTypes[1] {
		return e.Changes, nil
	}
	return nil, &NotLoadedError{edge: "changes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamPriceSource) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreampricesource.FieldParserConfig, upstreampricesource.FieldModelAliasMap:
			values[i] = new([]byte)
		case upstreampricesource.FieldEnabled:
			values[i] = new(sql.NullBool)
		case upstreampricesource.FieldAlertThresholdPct:
			values[i] = new(sql.NullFloat64)
		case upstreampricesource.FieldID, upstreampricesource.FieldSyncIntervalMinutes, upstreampricesource.FieldCooldownMinutes:
			values[i] = new(sql.NullInt64)
		case upstreampricesource.FieldName, upstreampricesource.FieldBaseURL, upstreampricesource.FieldPricingEndpoint, upstreampricesource.FieldAPIKey, upstreampricesource.FieldParserType, upstreampricesource.FieldLastSyncStatus, upstreampricesource.FieldLastSyncError, upstreampricesource.FieldLastHash:
			values[i] = new(sql.NullString)
		case upstreampricesource.FieldLastSyncAt, upstreampricesource.FieldCreatedAt, upstreampricesource.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamPriceSource fields.
func (_m *UpstreamPriceSource) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreampricesource.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreampricesource.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case upstreampricesource.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case upstreampricesource.FieldPricingEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pricing_endpoint", values[i])
			} else if value.Valid {
				_m.PricingEndpoint = value.String
			}
		case upstreampricesource.FieldAPIKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key", values[i])
			} else if value.Valid {
				_m.APIKey = value.String
			}
		case upstreampricesource.FieldParserType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parser_type", values[i])
			} else if value.Valid {
				_m.ParserType = value.String
			}
		case upstreampricesource.FieldParserConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field parser_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ParserConfig); err != nil {
					return fmt.Errorf("unmarshal field parser_config: %w", err)
				}
			}
		case upstreampricesource.FieldModelAliasMap:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field model_alias_map", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ModelAliasMap); err != nil {
					return fmt.Errorf("unmarshal field model_alias_map: %w", err)
				}
			}
		case upstreampricesource.FieldSyncIntervalMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sync_interval_minutes", values[i])
			} else if value.Valid {
				_m.SyncIntervalMinutes = int(value.Int64)
			}
		case upstreampricesource.FieldAlertThresholdPct:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field alert_threshold_pct", values[i])
			} else if value.Valid {
				_m.AlertThresholdPct = value.Float64
			}
		case upstreampricesource.FieldCooldownMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cooldown_minutes", values[i])
			} else if value.Valid {
				_m.CooldownMinutes = int(value.Int64)
			}
		case upstreampricesource.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case upstreampricesource.FieldLastSyncAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_at", values[i])
			} else if value.Valid {
				_m.LastSyncAt = new(time.Time)
				*_m.LastSyncAt = value.Time
			}
		case upstreampricesource.FieldLastSyncStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_status", values[i])
			} else if value.Valid {
				_m.LastSyncStatus = value.String
			}
		case upstreampricesource.FieldLastSyncError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_error", values[i])
			} else if value.Valid {
				_m.LastSyncError = value.String
			}
		case upstreampricesource.FieldLastHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_hash", values[i])
			} else if value.Valid {
				_m.LastHash = value.String
			}
		case upstreampricesource.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstreampricesource.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamPriceSource.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamPriceSource) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPrices queries the "prices" edge of the UpstreamPriceSource entity.
func (_m *UpstreamPriceSource) QueryPrices() *UpstreamModelPriceQuery {
	return NewUpstreamPriceSourceClient(_m.config).QueryPrices(_m)
}

// QueryChanges queries the "changes" edge of the UpstreamPriceSource entity.
func (_m *UpstreamPriceSource) QueryChanges() *UpstreamPriceChangeQuery {
	return NewUpstreamPriceSourceClient(_m.config).QueryChanges(_m)
}

// Update returns a builder for updating this UpstreamPriceSource.
// Note that you need to call UpstreamPriceSource.Unwrap() before calling this method if this UpstreamPriceSource
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamPriceSource) Update() *UpstreamPriceSourceUpdateOne {
	return NewUpstreamPriceSourceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamPriceSource entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamPriceSource) Unwrap() *UpstreamPriceSource {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamPriceSource is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamPriceSource) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamPriceSource(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	builder.WriteString("pricing_endpoint=")
	builder.WriteString(_m.PricingEndpoint)
	builder.WriteString(", ")
	builder.WriteString("api_key=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("parser_type=")
	builder.WriteString(_m.ParserType)
	builder.WriteString(", ")
	builder.WriteString("parser_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParserConfig))
	builder.WriteString(", ")
	builder.WriteString("model_alias_map=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelAliasMap))
	builder.WriteString(", ")
	builder.WriteString("sync_interval_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncIntervalMinutes))
	builder.WriteString(", ")
	builder.WriteString("alert_threshold_pct=")
	builder.WriteString(fmt.Sprintf("%v", _m.AlertThresholdPct))
	builder.WriteString(", ")
	builder.WriteString("cooldown_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.CooldownMinutes))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	if v := _m.LastSyncAt; v != nil {
		builder.WriteString("last_sync_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_sync_status=")
	builder.WriteString(_m.LastSyncStatus)
	builder.WriteString(", ")
	builder.WriteString("last_sync_error=")
	builder.WriteString(_m.LastSyncError)
	builder.WriteString(", ")
	builder.WriteString("last_hash=")
	builder.WriteString(_m.LastHash)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamPriceSources is a parsable slice of UpstreamPriceSource.
type UpstreamPriceSources []*UpstreamPriceSource
