// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreampricesource"
)

// UpstreamPriceSourceDelete is the builder for deleting a UpstreamPriceSource entity.
type UpstreamPriceSourceDelete struct {
	config
	hooks    []Hook
	mutation *UpstreamPriceSourceMutation
}

// Where appends a list predicates to the UpstreamPriceSourceDelete builder.
func (_d *UpstreamPriceSourceDelete) Where(ps ...predicate.UpstreamPriceSource) *UpstreamPriceSourceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UpstreamPriceSourceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UpstreamPriceSourceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UpstreamPriceSourceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(upstreampricesource.Table, sqlgraph.NewFieldSpec(upstreampricesource.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UpstreamPriceSourceDeleteOne is the builder for deleting a single UpstreamPriceSource entity.
type UpstreamPriceSourceDeleteOne struct {
	_d *UpstreamPriceSourceDelete
}

// Where appends a list predicates to the UpstreamPriceSourceDelete builder.
func (_d *UpstreamPriceSourceDeleteOne) Where(ps ...predicate.UpstreamPriceSource) *UpstreamPriceSourceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UpstreamPriceSourceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{upstreampricesource.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UpstreamPriceSourceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
