// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstreampricechange"
	"github.com/Wei-Shaw/sub2api/ent/upstreampricesource"
)

// UpstreamPriceChangeCreate is the builder for creating a UpstreamPriceChange entity.
type UpstreamPriceChangeCreate struct {
	config
	mutation *UpstreamPriceChangeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSourceID sets the "source_id" field.
func (_c *UpstreamPriceChangeCreate) SetSourceID(v int64) *UpstreamPriceChangeCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetModelName sets the "model_name" field.
func (_c *UpstreamPriceChangeCreate) SetModelName(v string) *UpstreamPriceChangeCreate {
	_c.mutation.SetModelName(v)
	return _c
}

// SetLocalModelName sets the "local_model_name" field.
func (_c *UpstreamPriceChangeCreate) SetLocalModelName(v string) *UpstreamPriceChangeCreate {
	_c.mutation.SetLocalModelName(v)
	return _c
}

// SetNillableLocalModelName sets the "local_model_name" field if the given value is not nil.
func (_c *UpstreamPriceChangeCreate) SetNillableLocalModelName(v *string) *UpstreamPriceChangeCreate {
	if v != nil {
		_c.SetLocalModelName(*v)
	}
	return _c
}

// SetChangeType sets the "change_type" field.
func (_c *UpstreamPriceChangeCreate) SetChangeType(v string) *UpstreamPriceChangeCreate {
	_c.mutation.SetChangeType(v)
	return _c
}

// SetPrevInputPrice sets the "prev_input_price" field.
func (_c *UpstreamPriceChangeCreate) SetPrevInputPrice(v float64) *UpstreamPriceChangeCreate {
	_c.mutation.SetPrevInputPrice(v)
	return _c
}

// SetNillablePrevInputPrice sets the "prev_input_price" field if the given value is not nil.
func (_c *UpstreamPriceChangeCreate) SetNillablePrevInputPrice(v *float64) *UpstreamPriceChangeCreate {
	if v != nil {
		_c.SetPrevInputPrice(*v)
	}
	return _c
}

// SetPrevOutputPrice sets the "prev_output_price" field.
func (_c *UpstreamPriceChangeCreate) SetPrevOutputPrice(v float64) *UpstreamPriceChangeCreate {
	_c.mutation.SetPrevOutputPrice(v)
	return _c
}

// SetNillablePrevOutputPrice sets the "prev_output_price" field if the given value is not nil.
func (_c *UpstreamPriceChangeCreate) SetNillablePrevOutputPrice(v *float64) *UpstreamPriceChangeCreate {
	if v != nil {
		_c.SetPrevOutputPrice(*v)
	}
	return _c
}

// SetCurrInputPrice sets the "curr_input_price" field.
func (_c *UpstreamPriceChangeCreate) SetCurrInputPrice(v float64) *UpstreamPriceChangeCreate {
	_c.mutation.SetCurrInputPrice(v)
	return _c
}

// SetCurrOutputPrice sets the "curr_output_price" field.
func (_c *UpstreamPriceChangeCreate) SetCurrOutputPrice(v float64) *UpstreamPriceChangeCreate {
	_c.mutation.SetCurrOutputPrice(v)
	return _c
}

// SetInputDeltaPct sets the "input_delta_pct" field.
func (_c *UpstreamPriceChangeCreate) SetInputDeltaPct(v float64) *UpstreamPriceChangeCreate {
	_c.mutation.SetInputDeltaPct(v)
	return _c
}

// SetNillableInputDeltaPct sets the "input_delta_pct" field if the given value is not nil.
func (_c *UpstreamPriceChangeCreate) SetNillableInputDeltaPct(v *float64) *UpstreamPriceChangeCreate {
	if v != nil {
		_c.SetInputDeltaPct(*v)
	}
	return _c
}

// SetOutputDeltaPct sets the "output_delta_pct" field.
func (_c *UpstreamPriceChangeCreate) SetOutputDeltaPct(v float64) *UpstreamPriceChangeCreate {
	_c.mutation.SetOutputDeltaPct(v)
	return _c
}

// SetNillableOutputDeltaPct sets the "output_delta_pct" field if the given value is not nil.
func (_c *UpstreamPriceChangeCreate) SetNillableOutputDeltaPct(v *float64) *UpstreamPriceChangeCreate {
	if v != nil {
		_c.SetOutputDeltaPct(*v)
	}
	return _c
}

// SetDetectedAt sets the "detected_at" field.
func (_c *UpstreamPriceChangeCreate) SetDetectedAt(v time.Time) *UpstreamPriceChangeCreate {
	_c.mutation.SetDetectedAt(v)
	return _c
}

// SetNillableDetectedAt sets the "detected_at" field if the given value is not nil.
func (_c *UpstreamPriceChangeCreate) SetNillableDetectedAt(v *time.Time) *UpstreamPriceChangeCreate {
	if v != nil {
		_c.SetDetectedAt(*v)
	}
	return _c
}

// SetNotified sets the "notified" field.
func (_c *UpstreamPriceChangeCreate) SetNotified(v bool) *UpstreamPriceChangeCreate {
	_c.mutation.SetNotified(v)
	return _c
}

// SetNillableNotified sets the "notified" field if the given value is not nil.
func (_c *UpstreamPriceChangeCreate) SetNillableNotified(v *bool) *UpstreamPriceChangeCreate {
	if v != nil {
		_c.SetNotified(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UpstreamPriceChangeCreate) SetStatus(v string) *UpstreamPriceChangeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UpstreamPriceChangeCreate) SetNillableStatus(v *string) *UpstreamPriceChangeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSuggestedInputPrice sets the "suggested_input_price" field.
func (_c *UpstreamPriceChangeCreate) SetSuggestedInputPrice(v float64) *UpstreamPriceChangeCreate {
	_c.mutation.SetSuggestedInputPrice(v)
	return _c
}

// SetNillableSuggestedInputPrice sets the "suggested_input_price" field if the given value is not nil.
func (_c *UpstreamPriceChangeCreate) SetNillableSuggestedInputPrice(v *float64) *UpstreamPriceChangeCreate {
	if v != nil {
		_c.SetSuggestedInputPrice(*v)
	}
	return _c
}

// SetSuggestedOutputPrice sets the "suggested_output_price" field.
func (_c *UpstreamPriceChangeCreate) SetSuggestedOutputPrice(v float64) *UpstreamPriceChangeCreate {
	_c.mutation.SetSuggestedOutputPrice(v)
	return _c
}

// SetNillableSuggestedOutputPrice sets the "suggested_output_price" field if the given value is not nil.
func (_c *UpstreamPriceChangeCreate) SetNillableSuggestedOutputPrice(v *float64) *UpstreamPriceChangeCreate {
	if v != nil {
		_c.SetSuggestedOutputPrice(*v)
	}
	return _c
}

// SetSuggestedMultiplier sets the "suggested_multiplier" field.
func (_c *UpstreamPriceChangeCreate) SetSuggestedMultiplier(v float64) *UpstreamPriceChangeCreate {
	_c.mutation.SetSuggestedMultiplier(v)
	return _c
}

// SetNillableSuggestedMultiplier sets the "suggested_multiplier" field if the given value is not nil.
func (_c *UpstreamPriceChangeCreate) SetNillableSuggestedMultiplier(v *float64) *UpstreamPriceChangeCreate {
	if v != nil {
		_c.SetSuggestedMultiplier(*v)
	}
	return _c
}

// SetAppliedAt sets the "applied_at" field.
func (_c *UpstreamPriceChangeCreate) SetAppliedAt(v time.Time) *UpstreamPriceChangeCreate {
	_c.mutation.SetAppliedAt(v)
	return _c
}

// SetNillableAppliedAt sets the "applied_at" field if the given value is not nil.
func (_c *UpstreamPriceChangeCreate) SetNillableAppliedAt(v *time.Time) *UpstreamPriceChangeCreate {
	if v != nil {
		_c.SetAppliedAt(*v)
	}
	return _c
}

// SetAppliedBy sets the "applied_by" field.
func (_c *UpstreamPriceChangeCreate) SetAppliedBy(v int64) *UpstreamPriceChangeCreate {
	_c.mutation.SetAppliedBy(v)
	return _c
}

// SetNillableAppliedBy sets the "applied_by" field if the given value is not nil.
func (_c *UpstreamPriceChangeCreate) SetNillableAppliedBy(v *int64) *UpstreamPriceChangeCreate {
	if v != nil {
		_c.SetAppliedBy(*v)
	}
	return _c
}

// SetAppliedTarget sets the "applied_target" field.
func (_c *UpstreamPriceChangeCreate) SetAppliedTarget(v string) *UpstreamPriceChangeCreate {
	_c.mutation.SetAppliedTarget(v)
	return _c
}

// SetNillableAppliedTarget sets the "applied_target" field if the given value is not nil.
func (_c *UpstreamPriceChangeCreate) SetNillableAppliedTarget(v *string) *UpstreamPriceChangeCreate {
	if v != nil {
		_c.SetAppliedTarget(*v)
	}
	return _c
}

// SetAppliedTargetID sets the "applied_target_id" field.
func (_c *UpstreamPriceChangeCreate) SetAppliedTargetID(v int64) *UpstreamPriceChangeCreate {
	_c.mutation.SetAppliedTargetID(v)
	return _c
}

// SetNillableAppliedTargetID sets the "applied_target_id" field if the given value is not nil.
func (_c *UpstreamPriceChangeCreate) SetNillableAppliedTargetID(v *int64) *UpstreamPriceChangeCreate {
	if v != nil {
		_c.SetAppliedTargetID(*v)
	}
	return _c
}

// SetSource sets the "source" edge to the UpstreamPriceSource entity.
func (_c *UpstreamPriceChangeCreate) SetSource(v *UpstreamPriceSource) *UpstreamPriceChangeCreate {
	return _c.SetSourceID(v.ID)
}

// Mutation returns the UpstreamPriceChangeMutation object of the builder.
func (_c *UpstreamPriceChangeCreate) Mutation() *UpstreamPriceChangeMutation {
	return _c.mutation
}

// Save creates the UpstreamPriceChange in the database.
func (_c *UpstreamPriceChangeCreate) Save(ctx context.Context) (*UpstreamPriceChange, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamPriceChangeCreate) SaveX(ctx context.Context) *UpstreamPriceChange {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamPriceChangeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamPriceChangeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamPriceChangeCreate) defaults() {
	if _, ok := _c.mutation.InputDeltaPct(); !ok {
		v := upstreampricechange.DefaultInputDeltaPct
		_c.mutation.SetInputDeltaPct(v)
	}
	if _, ok := _c.mutation.OutputDeltaPct(); !ok {
		v := upstreampricechange.DefaultOutputDeltaPct
		_c.mutation.SetOutputDeltaPct(v)
	}
	if _, ok := _c.mutation.DetectedAt(); !ok {
		v := upstreampricechange.DefaultDetectedAt()
		_c.mutation.SetDetectedAt(v)
	}
	if _, ok := _c.mutation.Notified(); !ok {
		v := upstreampricechange.DefaultNotified
		_c.mutation.SetNotified(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := upstreampricechange.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SuggestedInputPrice(); !ok {
		v := upstreampricechange.DefaultSuggestedInputPrice
		_c.mutation.SetSuggestedInputPrice(v)
	}
	if _, ok := _c.mutation.SuggestedOutputPrice(); !ok {
		v := upstreampricechange.DefaultSuggestedOutputPrice
		_c.mutation.SetSuggestedOutputPrice(v)
	}
	if _, ok := _c.mutation.AppliedTargetID(); !ok {
		v := upstreampricechange.DefaultAppliedTargetID
		_c.mutation.SetAppliedTargetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamPriceChangeCreate) check() error {
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "UpstreamPriceChange.source_id"`)}
	}
	if _, ok := _c.mutation.ModelName(); !ok {
		return &ValidationError{Name: "model_name", err: errors.New(`ent: missing required field "UpstreamPriceChange.model_name"`)}
	}
	if v, ok := _c.mutation.ModelName(); ok {
		if err := upstreampricechange.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "UpstreamPriceChange.model_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChangeType(); !ok {
		return &ValidationError{Name: "change_type", err: errors.New(`ent: missing required field "UpstreamPriceChange.change_type"`)}
	}
	if v, ok := _c.mutation.ChangeType(); ok {
		if err := upstreampricechange.ChangeTypeValidator(v); err != nil {
			return &ValidationError{Name: "change_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamPriceChange.change_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CurrInputPrice(); !ok {
		return &ValidationError{Name: "curr_input_price", err: errors.New(`ent: missing required field "UpstreamPriceChange.curr_input_price"`)}
	}
	if _, ok := _c.mutation.CurrOutputPrice(); !ok {
		return &ValidationError{Name: "curr_output_price", err: errors.New(`ent: missing required field "UpstreamPriceChange.curr_output_price"`)}
	}
	if _, ok := _c.mutation.InputDeltaPct(); !ok {
		return &ValidationError{Name: "input_delta_pct", err: errors.New(`ent: missing required field "UpstreamPriceChange.input_delta_pct"`)}
	}
	if _, ok := _c.mutation.OutputDeltaPct(); !ok {
		return &ValidationError{Name: "output_delta_pct", err: errors.New(`ent: missing required field "UpstreamPriceChange.output_delta_pct"`)}
	}
	if _, ok := _c.mutation.DetectedAt(); !ok {
		return &ValidationError{Name: "detected_at", err: errors.New(`ent: missing required field "UpstreamPriceChange.detected_at"`)}
	}
	if _, ok := _c.mutation.Notified(); !ok {
		return &ValidationError{Name: "notified", err: errors.New(`ent: missing required field "UpstreamPriceChange.notified"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UpstreamPriceChange.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := upstreampricechange.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamPriceChange.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SuggestedInputPrice(); !ok {
		return &ValidationError{Name: "suggested_input_price", err: errors.New(`ent: missing required field "UpstreamPriceChange.suggested_input_price"`)}
	}
	if _, ok := _c.mutation.SuggestedOutputPrice(); !ok {
		return &ValidationError{Name: "suggested_output_price", err: errors.New(`ent: missing required field "UpstreamPriceChange.suggested_output_price"`)}
	}
	if v, ok := _c.mutation.AppliedTarget(); ok {
		if err := upstreampricechange.AppliedTargetValidator(v); err != nil {
			return &ValidationError{Name: "applied_target", err: fmt.Errorf(`ent: validator failed for field "UpstreamPriceChange.applied_target": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AppliedTargetID(); !ok {
		return &ValidationError{Name: "applied_target_id", err: errors.New(`ent: missing required field "UpstreamPriceChange.applied_target_id"`)}
	}
	if len(_c.mutation.SourceIDs()) == 0 {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required edge "UpstreamPriceChange.source"`)}
	}
	return nil
}

func (_c *UpstreamPriceChangeCreate) sqlSave(ctx context.Context) (*UpstreamPriceChange, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamPriceChangeCreate) createSpec() (*UpstreamPriceChange, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamPriceChange{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreampricechange.Table, sqlgraph.NewFieldSpec(upstreampricechange.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ModelName(); ok {
		_spec.SetField(upstreampricechange.FieldModelName, field.TypeString, value)
		_node.ModelName = value
	}
	if value, ok := _c.mutation.LocalModelName(); ok {
		_spec.SetField(upstreampricechange.FieldLocalModelName, field.TypeString, value)
		_node.LocalModelName = value
	}
	if value, ok := _c.mutation.ChangeType(); ok {
		_spec.SetField(upstreampricechange.FieldChangeType, field.TypeString, value)
		_node.ChangeType = value
	}
	if value, ok := _c.mutation.PrevInputPrice(); ok {
		_spec.SetField(upstreampricechange.FieldPrevInputPrice, field.TypeFloat64, value)
		_node.PrevInputPrice = &value
	}
	if value, ok := _c.mutation.PrevOutputPrice(); ok {
		_spec.SetField(upstreampricechange.FieldPrevOutputPrice, field.TypeFloat64, value)
		_node.PrevOutputPrice = &value
	}
	if value, ok := _c.mutation.CurrInputPrice(); ok {
		_spec.SetField(upstreampricechange.FieldCurrInputPrice, field.TypeFloat64, value)
		_node.CurrInputPrice = value
	}
	if value, ok := _c.mutation.CurrOutputPrice(); ok {
		_spec.SetField(upstreampricechange.FieldCurrOutputPrice, field.TypeFloat64, value)
		_node.CurrOutputPrice = value
	}
	if value, ok := _c.mutation.InputDeltaPct(); ok {
		_spec.SetField(upstreampricechange.FieldInputDeltaPct, field.TypeFloat64, value)
		_node.InputDeltaPct = value
	}
	if value, ok := _c.mutation.OutputDeltaPct(); ok {
		_spec.SetField(upstreampricechange.FieldOutputDeltaPct, field.TypeFloat64, value)
		_node.OutputDeltaPct = value
	}
	if value, ok := _c.mutation.DetectedAt(); ok {
		_spec.SetField(upstreampricechange.FieldDetectedAt, field.TypeTime, value)
		_node.DetectedAt = value
	}
	if value, ok := _c.mutation.Notified(); ok {
		_spec.SetField(upstreampricechange.FieldNotified, field.TypeBool, value)
		_node.Notified = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(upstreampricechange.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SuggestedInputPrice(); ok {
		_spec.SetField(upstreampricechange.FieldSuggestedInputPrice, field.TypeFloat64, value)
		_node.SuggestedInputPrice = value
	}
	if value, ok := _c.mutation.SuggestedOutputPrice(); ok {
		_spec.SetField(upstreampricechange.FieldSuggestedOutputPrice, field.TypeFloat64, value)
		_node.SuggestedOutputPrice = value
	}
	if value, ok := _c.mutation.SuggestedMultiplier(); ok {
		_spec.SetField(upstreampricechange.FieldSuggestedMultiplier, field.TypeFloat64, value)
		_node.SuggestedMultiplier = &value
	}
	if value, ok := _c.mutation.AppliedAt(); ok {
		_spec.SetField(upstreampricechange.FieldAppliedAt, field.TypeTime, value)
		_node.AppliedAt = &value
	}
	if value, ok := _c.mutation.AppliedBy(); ok {
		_spec.SetField(upstreampricechange.FieldAppliedBy, field.TypeInt64, value)
		_node.AppliedBy = &value
	}
	if value, ok := _c.mutation.AppliedTarget(); ok {
		_spec.SetField(upstreampricechange.FieldAppliedTarget, field.TypeString, value)
		_node.AppliedTarget = value
	}
	if value, ok := _c.mutation.AppliedTargetID(); ok {
		_spec.SetField(upstreampricechange.FieldAppliedTargetID, field.TypeInt64, value)
		_node.AppliedTargetID = value
	}
	if nodes := _c.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreampricechange.SourceTable,
			Columns: []string{upstreampricechange.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreampricesource.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SourceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamPriceChange.Create().
//		SetSourceID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamPriceChangeUpsert) {
//			SetSourceID(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamPriceChangeCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamPriceChangeUpsertOne {
	_c.conflict = opts
	return &UpstreamPriceChangeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamPriceChange.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamPriceChangeCreate) OnConflictColumns(columns ...string) *UpstreamPriceChangeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamPriceChangeUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamPriceChangeUpsertOne is the builder for "upsert"-ing
	//  one UpstreamPriceChange node.
	UpstreamPriceChangeUpsertOne struct {
		create *UpstreamPriceChangeCreate
	}

	// UpstreamPriceChangeUpsert is the "OnConflict" setter.
	UpstreamPriceChangeUpsert struct {
		*sql.UpdateSet
	}
)

// SetSourceID sets the "source_id" field.
func (u *UpstreamPriceChangeUpsert) SetSourceID(v int64) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateSourceID() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldSourceID)
	return u
}

// SetModelName sets the "model_name" field.
func (u *UpstreamPriceChangeUpsert) SetModelName(v string) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldModelName, v)
	return u
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateModelName() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldModelName)
	return u
}

// SetLocalModelName sets the "local_model_name" field.
func (u *UpstreamPriceChangeUpsert) SetLocalModelName(v string) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldLocalModelName, v)
	return u
}

// UpdateLocalModelName sets the "local_model_name" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateLocalModelName() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldLocalModelName)
	return u
}

// ClearLocalModelName clears the value of the "local_model_name" field.
func (u *UpstreamPriceChangeUpsert) ClearLocalModelName() *UpstreamPriceChangeUpsert {
	u.SetNull(upstreampricechange.FieldLocalModelName)
	return u
}

// SetChangeType sets the "change_type" field.
func (u *UpstreamPriceChangeUpsert) SetChangeType(v string) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldChangeType, v)
	return u
}

// UpdateChangeType sets the "change_type" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateChangeType() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldChangeType)
	return u
}

// SetPrevInputPrice sets the "prev_input_price" field.
func (u *UpstreamPriceChangeUpsert) SetPrevInputPrice(v float64) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldPrevInputPrice, v)
	return u
}

// UpdatePrevInputPrice sets the "prev_input_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdatePrevInputPrice() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldPrevInputPrice)
	return u
}

// AddPrevInputPrice adds v to the "prev_input_price" field.
func (u *UpstreamPriceChangeUpsert) AddPrevInputPrice(v float64) *UpstreamPriceChangeUpsert {
	u.Add(upstreampricechange.FieldPrevInputPrice, v)
	return u
}

// ClearPrevInputPrice clears the value of the "prev_input_price" field.
func (u *UpstreamPriceChangeUpsert) ClearPrevInputPrice() *UpstreamPriceChangeUpsert {
	u.SetNull(upstreampricechange.FieldPrevInputPrice)
	return u
}

// SetPrevOutputPrice sets the "prev_output_price" field.
func (u *UpstreamPriceChangeUpsert) SetPrevOutputPrice(v float64) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldPrevOutputPrice, v)
	return u
}

// UpdatePrevOutputPrice sets the "prev_output_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdatePrevOutputPrice() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldPrevOutputPrice)
	return u
}

// AddPrevOutputPrice adds v to the "prev_output_price" field.
func (u *UpstreamPriceChangeUpsert) AddPrevOutputPrice(v float64) *UpstreamPriceChangeUpsert {
	u.Add(upstreampricechange.FieldPrevOutputPrice, v)
	return u
}

// ClearPrevOutputPrice clears the value of the "prev_output_price" field.
func (u *UpstreamPriceChangeUpsert) ClearPrevOutputPrice() *UpstreamPriceChangeUpsert {
	u.SetNull(upstreampricechange.FieldPrevOutputPrice)
	return u
}

// SetCurrInputPrice sets the "curr_input_price" field.
func (u *UpstreamPriceChangeUpsert) SetCurrInputPrice(v float64) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldCurrInputPrice, v)
	return u
}

// UpdateCurrInputPrice sets the "curr_input_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateCurrInputPrice() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldCurrInputPrice)
	return u
}

// AddCurrInputPrice adds v to the "curr_input_price" field.
func (u *UpstreamPriceChangeUpsert) AddCurrInputPrice(v float64) *UpstreamPriceChangeUpsert {
	u.Add(upstreampricechange.FieldCurrInputPrice, v)
	return u
}

// SetCurrOutputPrice sets the "curr_output_price" field.
func (u *UpstreamPriceChangeUpsert) SetCurrOutputPrice(v float64) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldCurrOutputPrice, v)
	return u
}

// UpdateCurrOutputPrice sets the "curr_output_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateCurrOutputPrice() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldCurrOutputPrice)
	return u
}

// AddCurrOutputPrice adds v to the "curr_output_price" field.
func (u *UpstreamPriceChangeUpsert) AddCurrOutputPrice(v float64) *UpstreamPriceChangeUpsert {
	u.Add(upstreampricechange.FieldCurrOutputPrice, v)
	return u
}

// SetInputDeltaPct sets the "input_delta_pct" field.
func (u *UpstreamPriceChangeUpsert) SetInputDeltaPct(v float64) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldInputDeltaPct, v)
	return u
}

// UpdateInputDeltaPct sets the "input_delta_pct" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateInputDeltaPct() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldInputDeltaPct)
	return u
}

// AddInputDeltaPct adds v to the "input_delta_pct" field.
func (u *UpstreamPriceChangeUpsert) AddInputDeltaPct(v float64) *UpstreamPriceChangeUpsert {
	u.Add(upstreampricechange.FieldInputDeltaPct, v)
	return u
}

// SetOutputDeltaPct sets the "output_delta_pct" field.
func (u *UpstreamPriceChangeUpsert) SetOutputDeltaPct(v float64) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldOutputDeltaPct, v)
	return u
}

// UpdateOutputDeltaPct sets the "output_delta_pct" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateOutputDeltaPct() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldOutputDeltaPct)
	return u
}

// AddOutputDeltaPct adds v to the "output_delta_pct" field.
func (u *UpstreamPriceChangeUpsert) AddOutputDeltaPct(v float64) *UpstreamPriceChangeUpsert {
	u.Add(upstreampricechange.FieldOutputDeltaPct, v)
	return u
}

// SetDetectedAt sets the "detected_at" field.
func (u *UpstreamPriceChangeUpsert) SetDetectedAt(v time.Time) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldDetectedAt, v)
	return u
}

// UpdateDetectedAt sets the "detected_at" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateDetectedAt() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldDetectedAt)
	return u
}

// SetNotified sets the "notified" field.
func (u *UpstreamPriceChangeUpsert) SetNotified(v bool) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldNotified, v)
	return u
}

// UpdateNotified sets the "notified" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateNotified() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldNotified)
	return u
}

// SetStatus sets the "status" field.
func (u *UpstreamPriceChangeUpsert) SetStatus(v string) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateStatus() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldStatus)
	return u
}

// SetSuggestedInputPrice sets the "suggested_input_price" field.
func (u *UpstreamPriceChangeUpsert) SetSuggestedInputPrice(v float64) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldSuggestedInputPrice, v)
	return u
}

// UpdateSuggestedInputPrice sets the "suggested_input_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateSuggestedInputPrice() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldSuggestedInputPrice)
	return u
}

// AddSuggestedInputPrice adds v to the "suggested_input_price" field.
func (u *UpstreamPriceChangeUpsert) AddSuggestedInputPrice(v float64) *UpstreamPriceChangeUpsert {
	u.Add(upstreampricechange.FieldSuggestedInputPrice, v)
	return u
}

// SetSuggestedOutputPrice sets the "suggested_output_price" field.
func (u *UpstreamPriceChangeUpsert) SetSuggestedOutputPrice(v float64) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldSuggestedOutputPrice, v)
	return u
}

// UpdateSuggestedOutputPrice sets the "suggested_output_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateSuggestedOutputPrice() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldSuggestedOutputPrice)
	return u
}

// AddSuggestedOutputPrice adds v to the "suggested_output_price" field.
func (u *UpstreamPriceChangeUpsert) AddSuggestedOutputPrice(v float64) *UpstreamPriceChangeUpsert {
	u.Add(upstreampricechange.FieldSuggestedOutputPrice, v)
	return u
}

// SetSuggestedMultiplier sets the "suggested_multiplier" field.
func (u *UpstreamPriceChangeUpsert) SetSuggestedMultiplier(v float64) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldSuggestedMultiplier, v)
	return u
}

// UpdateSuggestedMultiplier sets the "suggested_multiplier" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateSuggestedMultiplier() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldSuggestedMultiplier)
	return u
}

// AddSuggestedMultiplier adds v to the "suggested_multiplier" field.
func (u *UpstreamPriceChangeUpsert) AddSuggestedMultiplier(v float64) *UpstreamPriceChangeUpsert {
	u.Add(upstreampricechange.FieldSuggestedMultiplier, v)
	return u
}

// ClearSuggestedMultiplier clears the value of the "suggested_multiplier" field.
func (u *UpstreamPriceChangeUpsert) ClearSuggestedMultiplier() *UpstreamPriceChangeUpsert {
	u.SetNull(upstreampricechange.FieldSuggestedMultiplier)
	return u
}

// SetAppliedAt sets the "applied_at" field.
func (u *UpstreamPriceChangeUpsert) SetAppliedAt(v time.Time) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldAppliedAt, v)
	return u
}

// UpdateAppliedAt sets the "applied_at" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateAppliedAt() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldAppliedAt)
	return u
}

// ClearAppliedAt clears the value of the "applied_at" field.
func (u *UpstreamPriceChangeUpsert) ClearAppliedAt() *UpstreamPriceChangeUpsert {
	u.SetNull(upstreampricechange.FieldAppliedAt)
	return u
}

// SetAppliedBy sets the "applied_by" field.
func (u *UpstreamPriceChangeUpsert) SetAppliedBy(v int64) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldAppliedBy, v)
	return u
}

// UpdateAppliedBy sets the "applied_by" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateAppliedBy() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldAppliedBy)
	return u
}

// AddAppliedBy adds v to the "applied_by" field.
func (u *UpstreamPriceChangeUpsert) AddAppliedBy(v int64) *UpstreamPriceChangeUpsert {
	u.Add(upstreampricechange.FieldAppliedBy, v)
	return u
}

// ClearAppliedBy clears the value of the "applied_by" field.
func (u *UpstreamPriceChangeUpsert) ClearAppliedBy() *UpstreamPriceChangeUpsert {
	u.SetNull(upstreampricechange.FieldAppliedBy)
	return u
}

// SetAppliedTarget sets the "applied_target" field.
func (u *UpstreamPriceChangeUpsert) SetAppliedTarget(v string) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldAppliedTarget, v)
	return u
}

// UpdateAppliedTarget sets the "applied_target" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateAppliedTarget() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldAppliedTarget)
	return u
}

// ClearAppliedTarget clears the value of the "applied_target" field.
func (u *UpstreamPriceChangeUpsert) ClearAppliedTarget() *UpstreamPriceChangeUpsert {
	u.SetNull(upstreampricechange.FieldAppliedTarget)
	return u
}

// SetAppliedTargetID sets the "applied_target_id" field.
func (u *UpstreamPriceChangeUpsert) SetAppliedTargetID(v int64) *UpstreamPriceChangeUpsert {
	u.Set(upstreampricechange.FieldAppliedTargetID, v)
	return u
}

// UpdateAppliedTargetID sets the "applied_target_id" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsert) UpdateAppliedTargetID() *UpstreamPriceChangeUpsert {
	u.SetExcluded(upstreampricechange.FieldAppliedTargetID)
	return u
}

// AddAppliedTargetID adds v to the "applied_target_id" field.
func (u *UpstreamPriceChangeUpsert) AddAppliedTargetID(v int64) *UpstreamPriceChangeUpsert {
	u.Add(upstreampricechange.FieldAppliedTargetID, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamPriceChange.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamPriceChangeUpsertOne) UpdateNewValues() *UpstreamPriceChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamPriceChange.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamPriceChangeUpsertOne) Ignore() *UpstreamPriceChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamPriceChangeUpsertOne) DoNothing() *UpstreamPriceChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamPriceChangeCreate.OnConflict
// documentation for more info.
func (u *UpstreamPriceChangeUpsertOne) Update(set func(*UpstreamPriceChangeUpsert)) *UpstreamPriceChangeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamPriceChangeUpsert{UpdateSet: update})
	}))
	return u
}

// SetSourceID sets the "source_id" field.
func (u *UpstreamPriceChangeUpsertOne) SetSourceID(v int64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateSourceID() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateSourceID()
	})
}

// SetModelName sets the "model_name" field.
func (u *UpstreamPriceChangeUpsertOne) SetModelName(v string) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateModelName() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateModelName()
	})
}

// SetLocalModelName sets the "local_model_name" field.
func (u *UpstreamPriceChangeUpsertOne) SetLocalModelName(v string) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetLocalModelName(v)
	})
}

// UpdateLocalModelName sets the "local_model_name" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateLocalModelName() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateLocalModelName()
	})
}

// ClearLocalModelName clears the value of the "local_model_name" field.
func (u *UpstreamPriceChangeUpsertOne) ClearLocalModelName() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.ClearLocalModelName()
	})
}

// SetChangeType sets the "change_type" field.
func (u *UpstreamPriceChangeUpsertOne) SetChangeType(v string) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetChangeType(v)
	})
}

// UpdateChangeType sets the "change_type" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateChangeType() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateChangeType()
	})
}

// SetPrevInputPrice sets the "prev_input_price" field.
func (u *UpstreamPriceChangeUpsertOne) SetPrevInputPrice(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetPrevInputPrice(v)
	})
}

// AddPrevInputPrice adds v to the "prev_input_price" field.
func (u *UpstreamPriceChangeUpsertOne) AddPrevInputPrice(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddPrevInputPrice(v)
	})
}

// UpdatePrevInputPrice sets the "prev_input_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdatePrevInputPrice() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdatePrevInputPrice()
	})
}

// ClearPrevInputPrice clears the value of the "prev_input_price" field.
func (u *UpstreamPriceChangeUpsertOne) ClearPrevInputPrice() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.ClearPrevInputPrice()
	})
}

// SetPrevOutputPrice sets the "prev_output_price" field.
func (u *UpstreamPriceChangeUpsertOne) SetPrevOutputPrice(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetPrevOutputPrice(v)
	})
}

// AddPrevOutputPrice adds v to the "prev_output_price" field.
func (u *UpstreamPriceChangeUpsertOne) AddPrevOutputPrice(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddPrevOutputPrice(v)
	})
}

// UpdatePrevOutputPrice sets the "prev_output_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdatePrevOutputPrice() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdatePrevOutputPrice()
	})
}

// ClearPrevOutputPrice clears the value of the "prev_output_price" field.
func (u *UpstreamPriceChangeUpsertOne) ClearPrevOutputPrice() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.ClearPrevOutputPrice()
	})
}

// SetCurrInputPrice sets the "curr_input_price" field.
func (u *UpstreamPriceChangeUpsertOne) SetCurrInputPrice(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetCurrInputPrice(v)
	})
}

// AddCurrInputPrice adds v to the "curr_input_price" field.
func (u *UpstreamPriceChangeUpsertOne) AddCurrInputPrice(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddCurrInputPrice(v)
	})
}

// UpdateCurrInputPrice sets the "curr_input_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateCurrInputPrice() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateCurrInputPrice()
	})
}

// SetCurrOutputPrice sets the "curr_output_price" field.
func (u *UpstreamPriceChangeUpsertOne) SetCurrOutputPrice(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetCurrOutputPrice(v)
	})
}

// AddCurrOutputPrice adds v to the "curr_output_price" field.
func (u *UpstreamPriceChangeUpsertOne) AddCurrOutputPrice(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddCurrOutputPrice(v)
	})
}

// UpdateCurrOutputPrice sets the "curr_output_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateCurrOutputPrice() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateCurrOutputPrice()
	})
}

// SetInputDeltaPct sets the "input_delta_pct" field.
func (u *UpstreamPriceChangeUpsertOne) SetInputDeltaPct(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetInputDeltaPct(v)
	})
}

// AddInputDeltaPct adds v to the "input_delta_pct" field.
func (u *UpstreamPriceChangeUpsertOne) AddInputDeltaPct(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddInputDeltaPct(v)
	})
}

// UpdateInputDeltaPct sets the "input_delta_pct" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateInputDeltaPct() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateInputDeltaPct()
	})
}

// SetOutputDeltaPct sets the "output_delta_pct" field.
func (u *UpstreamPriceChangeUpsertOne) SetOutputDeltaPct(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetOutputDeltaPct(v)
	})
}

// AddOutputDeltaPct adds v to the "output_delta_pct" field.
func (u *UpstreamPriceChangeUpsertOne) AddOutputDeltaPct(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddOutputDeltaPct(v)
	})
}

// UpdateOutputDeltaPct sets the "output_delta_pct" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateOutputDeltaPct() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateOutputDeltaPct()
	})
}

// SetDetectedAt sets the "detected_at" field.
func (u *UpstreamPriceChangeUpsertOne) SetDetectedAt(v time.Time) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetDetectedAt(v)
	})
}

// UpdateDetectedAt sets the "detected_at" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateDetectedAt() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateDetectedAt()
	})
}

// SetNotified sets the "notified" field.
func (u *UpstreamPriceChangeUpsertOne) SetNotified(v bool) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetNotified(v)
	})
}

// UpdateNotified sets the "notified" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateNotified() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateNotified()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamPriceChangeUpsertOne) SetStatus(v string) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateStatus() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateStatus()
	})
}

// SetSuggestedInputPrice sets the "suggested_input_price" field.
func (u *UpstreamPriceChangeUpsertOne) SetSuggestedInputPrice(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetSuggestedInputPrice(v)
	})
}

// AddSuggestedInputPrice adds v to the "suggested_input_price" field.
func (u *UpstreamPriceChangeUpsertOne) AddSuggestedInputPrice(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddSuggestedInputPrice(v)
	})
}

// UpdateSuggestedInputPrice sets the "suggested_input_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateSuggestedInputPrice() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateSuggestedInputPrice()
	})
}

// SetSuggestedOutputPrice sets the "suggested_output_price" field.
func (u *UpstreamPriceChangeUpsertOne) SetSuggestedOutputPrice(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetSuggestedOutputPrice(v)
	})
}

// AddSuggestedOutputPrice adds v to the "suggested_output_price" field.
func (u *UpstreamPriceChangeUpsertOne) AddSuggestedOutputPrice(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddSuggestedOutputPrice(v)
	})
}

// UpdateSuggestedOutputPrice sets the "suggested_output_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateSuggestedOutputPrice() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateSuggestedOutputPrice()
	})
}

// SetSuggestedMultiplier sets the "suggested_multiplier" field.
func (u *UpstreamPriceChangeUpsertOne) SetSuggestedMultiplier(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetSuggestedMultiplier(v)
	})
}

// AddSuggestedMultiplier adds v to the "suggested_multiplier" field.
func (u *UpstreamPriceChangeUpsertOne) AddSuggestedMultiplier(v float64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddSuggestedMultiplier(v)
	})
}

// UpdateSuggestedMultiplier sets the "suggested_multiplier" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateSuggestedMultiplier() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateSuggestedMultiplier()
	})
}

// ClearSuggestedMultiplier clears the value of the "suggested_multiplier" field.
func (u *UpstreamPriceChangeUpsertOne) ClearSuggestedMultiplier() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.ClearSuggestedMultiplier()
	})
}

// SetAppliedAt sets the "applied_at" field.
func (u *UpstreamPriceChangeUpsertOne) SetAppliedAt(v time.Time) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetAppliedAt(v)
	})
}

// UpdateAppliedAt sets the "applied_at" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateAppliedAt() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateAppliedAt()
	})
}

// ClearAppliedAt clears the value of the "applied_at" field.
func (u *UpstreamPriceChangeUpsertOne) ClearAppliedAt() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.ClearAppliedAt()
	})
}

// SetAppliedBy sets the "applied_by" field.
func (u *UpstreamPriceChangeUpsertOne) SetAppliedBy(v int64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetAppliedBy(v)
	})
}

// AddAppliedBy adds v to the "applied_by" field.
func (u *UpstreamPriceChangeUpsertOne) AddAppliedBy(v int64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddAppliedBy(v)
	})
}

// UpdateAppliedBy sets the "applied_by" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateAppliedBy() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateAppliedBy()
	})
}

// ClearAppliedBy clears the value of the "applied_by" field.
func (u *UpstreamPriceChangeUpsertOne) ClearAppliedBy() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.ClearAppliedBy()
	})
}

// SetAppliedTarget sets the "applied_target" field.
func (u *UpstreamPriceChangeUpsertOne) SetAppliedTarget(v string) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetAppliedTarget(v)
	})
}

// UpdateAppliedTarget sets the "applied_target" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateAppliedTarget() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateAppliedTarget()
	})
}

// ClearAppliedTarget clears the value of the "applied_target" field.
func (u *UpstreamPriceChangeUpsertOne) ClearAppliedTarget() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.ClearAppliedTarget()
	})
}

// SetAppliedTargetID sets the "applied_target_id" field.
func (u *UpstreamPriceChangeUpsertOne) SetAppliedTargetID(v int64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetAppliedTargetID(v)
	})
}

// AddAppliedTargetID adds v to the "applied_target_id" field.
func (u *UpstreamPriceChangeUpsertOne) AddAppliedTargetID(v int64) *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddAppliedTargetID(v)
	})
}

// UpdateAppliedTargetID sets the "applied_target_id" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertOne) UpdateAppliedTargetID() *UpstreamPriceChangeUpsertOne {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateAppliedTargetID()
	})
}

// Exec executes the query.
func (u *UpstreamPriceChangeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamPriceChangeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamPriceChangeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamPriceChangeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamPriceChangeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamPriceChangeCreateBulk is the builder for creating many UpstreamPriceChange entities in bulk.
type UpstreamPriceChangeCreateBulk struct {
	config
	err      error
	builders []*UpstreamPriceChangeCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamPriceChange entities in the database.
func (_c *UpstreamPriceChangeCreateBulk) Save(ctx context.Context) ([]*UpstreamPriceChange, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamPriceChange, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamPriceChangeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamPriceChangeCreateBulk) SaveX(ctx context.Context) []*UpstreamPriceChange {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamPriceChangeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamPriceChangeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamPriceChange.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamPriceChangeUpsert) {
//			SetSourceID(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamPriceChangeCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamPriceChangeUpsertBulk {
	_c.conflict = opts
	return &UpstreamPriceChangeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamPriceChange.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamPriceChangeCreateBulk) OnConflictColumns(columns ...string) *UpstreamPriceChangeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamPriceChangeUpsertBulk{
		create: _c,
	}
}

// UpstreamPriceChangeUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamPriceChange nodes.
type UpstreamPriceChangeUpsertBulk struct {
	create *UpstreamPriceChangeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamPriceChange.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamPriceChangeUpsertBulk) UpdateNewValues() *UpstreamPriceChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamPriceChange.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamPriceChangeUpsertBulk) Ignore() *UpstreamPriceChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamPriceChangeUpsertBulk) DoNothing() *UpstreamPriceChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamPriceChangeCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamPriceChangeUpsertBulk) Update(set func(*UpstreamPriceChangeUpsert)) *UpstreamPriceChangeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamPriceChangeUpsert{UpdateSet: update})
	}))
	return u
}

// SetSourceID sets the "source_id" field.
func (u *UpstreamPriceChangeUpsertBulk) SetSourceID(v int64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateSourceID() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateSourceID()
	})
}

// SetModelName sets the "model_name" field.
func (u *UpstreamPriceChangeUpsertBulk) SetModelName(v string) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateModelName() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateModelName()
	})
}

// SetLocalModelName sets the "local_model_name" field.
func (u *UpstreamPriceChangeUpsertBulk) SetLocalModelName(v string) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetLocalModelName(v)
	})
}

// UpdateLocalModelName sets the "local_model_name" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateLocalModelName() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateLocalModelName()
	})
}

// ClearLocalModelName clears the value of the "local_model_name" field.
func (u *UpstreamPriceChangeUpsertBulk) ClearLocalModelName() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.ClearLocalModelName()
	})
}

// SetChangeType sets the "change_type" field.
func (u *UpstreamPriceChangeUpsertBulk) SetChangeType(v string) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetChangeType(v)
	})
}

// UpdateChangeType sets the "change_type" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateChangeType() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateChangeType()
	})
}

// SetPrevInputPrice sets the "prev_input_price" field.
func (u *UpstreamPriceChangeUpsertBulk) SetPrevInputPrice(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetPrevInputPrice(v)
	})
}

// AddPrevInputPrice adds v to the "prev_input_price" field.
func (u *UpstreamPriceChangeUpsertBulk) AddPrevInputPrice(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddPrevInputPrice(v)
	})
}

// UpdatePrevInputPrice sets the "prev_input_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdatePrevInputPrice() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdatePrevInputPrice()
	})
}

// ClearPrevInputPrice clears the value of the "prev_input_price" field.
func (u *UpstreamPriceChangeUpsertBulk) ClearPrevInputPrice() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.ClearPrevInputPrice()
	})
}

// SetPrevOutputPrice sets the "prev_output_price" field.
func (u *UpstreamPriceChangeUpsertBulk) SetPrevOutputPrice(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetPrevOutputPrice(v)
	})
}

// AddPrevOutputPrice adds v to the "prev_output_price" field.
func (u *UpstreamPriceChangeUpsertBulk) AddPrevOutputPrice(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddPrevOutputPrice(v)
	})
}

// UpdatePrevOutputPrice sets the "prev_output_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdatePrevOutputPrice() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdatePrevOutputPrice()
	})
}

// ClearPrevOutputPrice clears the value of the "prev_output_price" field.
func (u *UpstreamPriceChangeUpsertBulk) ClearPrevOutputPrice() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.ClearPrevOutputPrice()
	})
}

// SetCurrInputPrice sets the "curr_input_price" field.
func (u *UpstreamPriceChangeUpsertBulk) SetCurrInputPrice(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetCurrInputPrice(v)
	})
}

// AddCurrInputPrice adds v to the "curr_input_price" field.
func (u *UpstreamPriceChangeUpsertBulk) AddCurrInputPrice(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddCurrInputPrice(v)
	})
}

// UpdateCurrInputPrice sets the "curr_input_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateCurrInputPrice() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateCurrInputPrice()
	})
}

// SetCurrOutputPrice sets the "curr_output_price" field.
func (u *UpstreamPriceChangeUpsertBulk) SetCurrOutputPrice(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetCurrOutputPrice(v)
	})
}

// AddCurrOutputPrice adds v to the "curr_output_price" field.
func (u *UpstreamPriceChangeUpsertBulk) AddCurrOutputPrice(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddCurrOutputPrice(v)
	})
}

// UpdateCurrOutputPrice sets the "curr_output_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateCurrOutputPrice() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateCurrOutputPrice()
	})
}

// SetInputDeltaPct sets the "input_delta_pct" field.
func (u *UpstreamPriceChangeUpsertBulk) SetInputDeltaPct(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetInputDeltaPct(v)
	})
}

// AddInputDeltaPct adds v to the "input_delta_pct" field.
func (u *UpstreamPriceChangeUpsertBulk) AddInputDeltaPct(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddInputDeltaPct(v)
	})
}

// UpdateInputDeltaPct sets the "input_delta_pct" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateInputDeltaPct() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateInputDeltaPct()
	})
}

// SetOutputDeltaPct sets the "output_delta_pct" field.
func (u *UpstreamPriceChangeUpsertBulk) SetOutputDeltaPct(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetOutputDeltaPct(v)
	})
}

// AddOutputDeltaPct adds v to the "output_delta_pct" field.
func (u *UpstreamPriceChangeUpsertBulk) AddOutputDeltaPct(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddOutputDeltaPct(v)
	})
}

// UpdateOutputDeltaPct sets the "output_delta_pct" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateOutputDeltaPct() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateOutputDeltaPct()
	})
}

// SetDetectedAt sets the "detected_at" field.
func (u *UpstreamPriceChangeUpsertBulk) SetDetectedAt(v time.Time) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetDetectedAt(v)
	})
}

// UpdateDetectedAt sets the "detected_at" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateDetectedAt() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateDetectedAt()
	})
}

// SetNotified sets the "notified" field.
func (u *UpstreamPriceChangeUpsertBulk) SetNotified(v bool) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetNotified(v)
	})
}

// UpdateNotified sets the "notified" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateNotified() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateNotified()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamPriceChangeUpsertBulk) SetStatus(v string) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateStatus() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateStatus()
	})
}

// SetSuggestedInputPrice sets the "suggested_input_price" field.
func (u *UpstreamPriceChangeUpsertBulk) SetSuggestedInputPrice(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetSuggestedInputPrice(v)
	})
}

// AddSuggestedInputPrice adds v to the "suggested_input_price" field.
func (u *UpstreamPriceChangeUpsertBulk) AddSuggestedInputPrice(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddSuggestedInputPrice(v)
	})
}

// UpdateSuggestedInputPrice sets the "suggested_input_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateSuggestedInputPrice() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateSuggestedInputPrice()
	})
}

// SetSuggestedOutputPrice sets the "suggested_output_price" field.
func (u *UpstreamPriceChangeUpsertBulk) SetSuggestedOutputPrice(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetSuggestedOutputPrice(v)
	})
}

// AddSuggestedOutputPrice adds v to the "suggested_output_price" field.
func (u *UpstreamPriceChangeUpsertBulk) AddSuggestedOutputPrice(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddSuggestedOutputPrice(v)
	})
}

// UpdateSuggestedOutputPrice sets the "suggested_output_price" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateSuggestedOutputPrice() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateSuggestedOutputPrice()
	})
}

// SetSuggestedMultiplier sets the "suggested_multiplier" field.
func (u *UpstreamPriceChangeUpsertBulk) SetSuggestedMultiplier(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetSuggestedMultiplier(v)
	})
}

// AddSuggestedMultiplier adds v to the "suggested_multiplier" field.
func (u *UpstreamPriceChangeUpsertBulk) AddSuggestedMultiplier(v float64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddSuggestedMultiplier(v)
	})
}

// UpdateSuggestedMultiplier sets the "suggested_multiplier" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateSuggestedMultiplier() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateSuggestedMultiplier()
	})
}

// ClearSuggestedMultiplier clears the value of the "suggested_multiplier" field.
func (u *UpstreamPriceChangeUpsertBulk) ClearSuggestedMultiplier() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.ClearSuggestedMultiplier()
	})
}

// SetAppliedAt sets the "applied_at" field.
func (u *UpstreamPriceChangeUpsertBulk) SetAppliedAt(v time.Time) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetAppliedAt(v)
	})
}

// UpdateAppliedAt sets the "applied_at" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateAppliedAt() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateAppliedAt()
	})
}

// ClearAppliedAt clears the value of the "applied_at" field.
func (u *UpstreamPriceChangeUpsertBulk) ClearAppliedAt() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.ClearAppliedAt()
	})
}

// SetAppliedBy sets the "applied_by" field.
func (u *UpstreamPriceChangeUpsertBulk) SetAppliedBy(v int64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetAppliedBy(v)
	})
}

// AddAppliedBy adds v to the "applied_by" field.
func (u *UpstreamPriceChangeUpsertBulk) AddAppliedBy(v int64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddAppliedBy(v)
	})
}

// UpdateAppliedBy sets the "applied_by" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateAppliedBy() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateAppliedBy()
	})
}

// ClearAppliedBy clears the value of the "applied_by" field.
func (u *UpstreamPriceChangeUpsertBulk) ClearAppliedBy() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.ClearAppliedBy()
	})
}

// SetAppliedTarget sets the "applied_target" field.
func (u *UpstreamPriceChangeUpsertBulk) SetAppliedTarget(v string) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetAppliedTarget(v)
	})
}

// UpdateAppliedTarget sets the "applied_target" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateAppliedTarget() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateAppliedTarget()
	})
}

// ClearAppliedTarget clears the value of the "applied_target" field.
func (u *UpstreamPriceChangeUpsertBulk) ClearAppliedTarget() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.ClearAppliedTarget()
	})
}

// SetAppliedTargetID sets the "applied_target_id" field.
func (u *UpstreamPriceChangeUpsertBulk) SetAppliedTargetID(v int64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.SetAppliedTargetID(v)
	})
}

// AddAppliedTargetID adds v to the "applied_target_id" field.
func (u *UpstreamPriceChangeUpsertBulk) AddAppliedTargetID(v int64) *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.AddAppliedTargetID(v)
	})
}

// UpdateAppliedTargetID sets the "applied_target_id" field to the value that was provided on create.
func (u *UpstreamPriceChangeUpsertBulk) UpdateAppliedTargetID() *UpstreamPriceChangeUpsertBulk {
	return u.Update(func(s *UpstreamPriceChangeUpsert) {
		s.UpdateAppliedTargetID()
	})
}

// Exec executes the query.
func (u *UpstreamPriceChangeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamPriceChangeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamPriceChangeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamPriceChangeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
