// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreampricechange"
	"github.com/Wei-Shaw/sub2api/ent/upstreampricesource"
)

// UpstreamPriceChange is the model entity for the UpstreamPriceChange schema.
type UpstreamPriceChange struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID int64 `json:"source_id,omitempty"`
	// 发生变动的上游模型名
	ModelName string `json:"model_name,omitempty"`
	// 映射后的本地模型名（可空）
	LocalModelName string `json:"local_model_name,omitempty"`
	// 变动类型: added / removed / price_change
	ChangeType string `json:"change_type,omitempty"`
	// 变动前输入价格（新增模型时为空）
	PrevInputPrice *float64 `json:"prev_input_price,omitempty"`
	// 变动前输出价格（新增模型时为空）
	PrevOutputPrice *float64 `json:"prev_output_price,omitempty"`
	// 当前输入价格
	CurrInputPrice float64 `json:"curr_input_price,omitempty"`
	// 当前输出价格
	CurrOutputPrice float64 `json:"curr_output_price,omitempty"`
	// 输入价格变动百分比
	InputDeltaPct float64 `json:"input_delta_pct,omitempty"`
	// 输出价格变动百分比
	OutputDeltaPct float64 `json:"output_delta_pct,omitempty"`
	// 检测到变动的时间
	DetectedAt time.Time `json:"detected_at,omitempty"`
	// 是否已发送告警通知
	Notified bool `json:"notified,omitempty"`
	// 处理状态: pending / applied / dismissed
	Status string `json:"status,omitempty"`
	// 建议输入价格（SuggestionCalculator 生成）
	SuggestedInputPrice float64 `json:"suggested_input_price,omitempty"`
	// 建议输出价格（SuggestionCalculator 生成）
	SuggestedOutputPrice float64 `json:"suggested_output_price,omitempty"`
	// 建议计费倍率（可空）
	SuggestedMultiplier *float64 `json:"suggested_multiplier,omitempty"`
	// 应用建议的时间
	AppliedAt *time.Time `json:"applied_at,omitempty"`
	// 操作人用户ID
	AppliedBy *int64 `json:"applied_by,omitempty"`
	// 应用目标类型: account / group / model_config
	AppliedTarget string `json:"applied_target,omitempty"`
	// 应用目标记录ID
	AppliedTargetID int64 `json:"applied_target_id,omitempty"`
	// 应用前 channel 该模型的实际输入单价快照（用于撤销回滚）
	AppliedPrevInputPrice *float64 `json:"applied_prev_input_price,omitempty"`
	// 应用前 channel 该模型的实际输出单价快照（用于撤销回滚）
	AppliedPrevOutputPrice *float64 `json:"applied_prev_output_price,omitempty"`
	// 应用时实际写入单价的 channel_id（撤销回滚锚点）
	AppliedChannelID *int64 `json:"applied_channel_id,omitempty"`
	// 应用前 group 的实际倍率快照（仅 lock_price，用于撤销回滚）
	PrevMultiplier *float64 `json:"prev_multiplier,omitempty"`
	// 撤销应用的时间
	RevertedAt *time.Time `json:"reverted_at,omitempty"`
	// 执行撤销的管理员用户ID
	RevertedBy *int64 `json:"reverted_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UpstreamPriceChangeQuery when eager-loading is set.
	Edges        UpstreamPriceChangeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UpstreamPriceChangeEdges holds the relations/edges for other nodes in the graph.
type UpstreamPriceChangeEdges struct {
	// Source holds the value of the source edge.
	Source *UpstreamPriceSource `json:"source,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SourceOrErr returns the Source value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UpstreamPriceChangeEdges) SourceOrErr() (*UpstreamPriceSource, error) {
	if e.Source != nil {
		return e.Source, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: upstreampricesource.Label}
	}
	return nil, &NotLoadedError{edge: "source"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamPriceChange) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreampricechange.FieldNotified:
			values[i] = new(sql.NullBool)
		case upstreampricechange.FieldPrevInputPrice, upstreampricechange.FieldPrevOutputPrice, upstreampricechange.FieldCurrInputPrice, upstreampricechange.FieldCurrOutputPrice, upstreampricechange.FieldInputDeltaPct, upstreampricechange.FieldOutputDeltaPct, upstreampricechange.FieldSuggestedInputPrice, upstreampricechange.FieldSuggestedOutputPrice, upstreampricechange.FieldSuggestedMultiplier, upstreampricechange.FieldAppliedPrevInputPrice, upstreampricechange.FieldAppliedPrevOutputPrice, upstreampricechange.FieldPrevMultiplier:
			values[i] = new(sql.NullFloat64)
		case upstreampricechange.FieldID, upstreampricechange.FieldSourceID, upstreampricechange.FieldAppliedBy, upstreampricechange.FieldAppliedTargetID, upstreampricechange.FieldAppliedChannelID, upstreampricechange.FieldRevertedBy:
			values[i] = new(sql.NullInt64)
		case upstreampricechange.FieldModelName, upstreampricechange.FieldLocalModelName, upstreampricechange.FieldChangeType, upstreampricechange.FieldStatus, upstreampricechange.FieldAppliedTarget:
			values[i] = new(sql.NullString)
		case upstreampricechange.FieldDetectedAt, upstreampricechange.FieldAppliedAt, upstreampricechange.FieldRevertedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamPriceChange fields.
func (_m *UpstreamPriceChange) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreampricechange.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreampricechange.FieldSourceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.Int64
			}
		case upstreampricechange.FieldModelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_name", values[i])
			} else if value.Valid {
				_m.ModelName = value.String
			}
		case upstreampricechange.FieldLocalModelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_model_name", values[i])
			} else if value.Valid {
				_m.LocalModelName = value.String
			}
		case upstreampricechange.FieldChangeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field change_type", values[i])
			} else if value.Valid {
				_m.ChangeType = value.String
			}
		case upstreampricechange.FieldPrevInputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field prev_input_price", values[i])
			} else if value.Valid {
				_m.PrevInputPrice = new(float64)
				*_m.PrevInputPrice = value.Float64
			}
		case upstreampricechange.FieldPrevOutputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field prev_output_price", values[i])
			} else if value.Valid {
				_m.PrevOutputPrice = new(float64)
				*_m.PrevOutputPrice = value.Float64
			}
		case upstreampricechange.FieldCurrInputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field curr_input_price", values[i])
			} else if value.Valid {
				_m.CurrInputPrice = value.Float64
			}
		case upstreampricechange.FieldCurrOutputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field curr_output_price", values[i])
			} else if value.Valid {
				_m.CurrOutputPrice = value.Float64
			}
		case upstreampricechange.FieldInputDeltaPct:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field input_delta_pct", values[i])
			} else if value.Valid {
				_m.InputDeltaPct = value.Float64
			}
		case upstreampricechange.FieldOutputDeltaPct:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field output_delta_pct", values[i])
			} else if value.Valid {
				_m.OutputDeltaPct = value.Float64
			}
		case upstreampricechange.FieldDetectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field detected_at", values[i])
			} else if value.Valid {
				_m.DetectedAt = value.Time
			}
		case upstreampricechange.FieldNotified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field notified", values[i])
			} else if value.Valid {
				_m.Notified = value.Bool
			}
		case upstreampricechange.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case upstreampricechange.FieldSuggestedInputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field suggested_input_price", values[i])
			} else if value.Valid {
				_m.SuggestedInputPrice = value.Float64
			}
		case upstreampricechange.FieldSuggestedOutputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field suggested_output_price", values[i])
			} else if value.Valid {
				_m.SuggestedOutputPrice = value.Float64
			}
		case upstreampricechange.FieldSuggestedMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field suggested_multiplier", values[i])
			} else if value.Valid {
				_m.SuggestedMultiplier = new(float64)
				*_m.SuggestedMultiplier = value.Float64
			}
		case upstreampricechange.FieldAppliedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field applied_at", values[i])
			} else if value.Valid {
				_m.AppliedAt = new(time.Time)
				*_m.AppliedAt = value.Time
			}
		case upstreampricechange.FieldAppliedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field applied_by", values[i])
			} else if value.Valid {
				_m.AppliedBy = new(int64)
				*_m.AppliedBy = value.Int64
			}
		case upstreampricechange.FieldAppliedTarget:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field applied_target", values[i])
			} else if value.Valid {
				_m.AppliedTarget = value.String
			}
		case upstreampricechange.FieldAppliedTargetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field applied_target_id", values[i])
			} else if value.Valid {
				_m.AppliedTargetID = value.Int64
			}
		case upstreampricechange.FieldAppliedPrevInputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field applied_prev_input_price", values[i])
			} else if value.Valid {
				_m.AppliedPrevInputPrice = new(float64)
				*_m.AppliedPrevInputPrice = value.Float64
			}
		case upstreampricechange.FieldAppliedPrevOutputPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field applied_prev_output_price", values[i])
			} else if value.Valid {
				_m.AppliedPrevOutputPrice = new(float64)
				*_m.AppliedPrevOutputPrice = value.Float64
			}
		case upstreampricechange.FieldAppliedChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field applied_channel_id", values[i])
			} else if value.Valid {
				_m.AppliedChannelID = new(int64)
				*_m.AppliedChannelID = value.Int64
			}
		case upstreampricechange.FieldPrevMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field prev_multiplier", values[i])
			} else if value.Valid {
				_m.PrevMultiplier = new(float64)
				*_m.PrevMultiplier = value.Float64
			}
		case upstreampricechange.FieldRevertedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reverted_at", values[i])
			} else if value.Valid {
				_m.RevertedAt = new(time.Time)
				*_m.RevertedAt = value.Time
			}
		case upstreampricechange.FieldRevertedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reverted_by", values[i])
			} else if value.Valid {
				_m.RevertedBy = new(int64)
				*_m.RevertedBy = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamPriceChange.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamPriceChange) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySource queries the "source" edge of the UpstreamPriceChange entity.
func (_m *UpstreamPriceChange) QuerySource() *UpstreamPriceSourceQuery {
	return NewUpstreamPriceChangeClient(_m.config).QuerySource(_m)
}

// Update returns a builder for updating this UpstreamPriceChange.
// Note that you need to call UpstreamPriceChange.Unwrap() before calling this method if this UpstreamPriceChange
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamPriceChange) Update() *UpstreamPriceChangeUpdateOne {
	return NewUpstreamPriceChangeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamPriceChange entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamPriceChange) Unwrap() *UpstreamPriceChange {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamPriceChange is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamPriceChange) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamPriceChange(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceID))
	builder.WriteString(", ")
	builder.WriteString("model_name=")
	builder.WriteString(_m.ModelName)
	builder.WriteString(", ")
	builder.WriteString("local_model_name=")
	builder.WriteString(_m.LocalModelName)
	builder.WriteString(", ")
	builder.WriteString("change_type=")
	builder.WriteString(_m.ChangeType)
	builder.WriteString(", ")
	if v := _m.PrevInputPrice; v != nil {
		builder.WriteString("prev_input_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PrevOutputPrice; v != nil {
		builder.WriteString("prev_output_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("curr_input_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrInputPrice))
	builder.WriteString(", ")
	builder.WriteString("curr_output_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrOutputPrice))
	builder.WriteString(", ")
	builder.WriteString("input_delta_pct=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputDeltaPct))
	builder.WriteString(", ")
	builder.WriteString("output_delta_pct=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputDeltaPct))
	builder.WriteString(", ")
	builder.WriteString("detected_at=")
	builder.WriteString(_m.DetectedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("notified=")
	builder.WriteString(fmt.Sprintf("%v", _m.Notified))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("suggested_input_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuggestedInputPrice))
	builder.WriteString(", ")
	builder.WriteString("suggested_output_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuggestedOutputPrice))
	builder.WriteString(", ")
	if v := _m.SuggestedMultiplier; v != nil {
		builder.WriteString("suggested_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AppliedAt; v != nil {
		builder.WriteString("applied_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AppliedBy; v != nil {
		builder.WriteString("applied_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("applied_target=")
	builder.WriteString(_m.AppliedTarget)
	builder.WriteString(", ")
	builder.WriteString("applied_target_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AppliedTargetID))
	builder.WriteString(", ")
	if v := _m.AppliedPrevInputPrice; v != nil {
		builder.WriteString("applied_prev_input_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AppliedPrevOutputPrice; v != nil {
		builder.WriteString("applied_prev_output_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AppliedChannelID; v != nil {
		builder.WriteString("applied_channel_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PrevMultiplier; v != nil {
		builder.WriteString("prev_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RevertedAt; v != nil {
		builder.WriteString("reverted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevertedBy; v != nil {
		builder.WriteString("reverted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamPriceChanges is a parsable slice of UpstreamPriceChange.
type UpstreamPriceChanges []*UpstreamPriceChange
